### ISSUE TITLE
Change Splunk consumer to use JSON Arrays

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-telemetry-streaming#101]
### Is your feature request related to a problem? Please describe.
Stats output for the Splunk consumer does not employ the usage of JSON based arrays for metric sets.

### Describe the solution you'd like
In order to provide an easier method for Splunk to parse, consume, and aggregate data. JSON Array ( [ ] ) based constructs should be used for objects that have multiple repeating values.  

In Splunk, when using the features KV_MODE=JSON and spath it automatically generates field names from the JSON message. The iRules object is broken out into fields like: iRules./Actuarial/Shared/USR_actuarial_HTML_rewrite_Rule.events.CLIENT_ACCEPTED.avgCycles. Splunk’s built-in functions are designed to only work with explicitly typed named fields, and not fields matching a name pattern. The iRules’ value needs to be change from a JSON object into an array to take advantage of Extract and expand JSON events with multi-valued fields. 

Current
```json
{
    "iRules": {
        "/Actuarial/Shared/USR_actuarial_HTML_rewrite_Rule": {
            "events": {
                "CLIENT_ACCEPTED": {
                    "avgCycles": 15820,
                    "totalExecutions": 86160
                }
            },
            "name": "/Actuarial/Shared/USR_actuarial_HTML_rewrite_Rule",
        }
    }
}
```

Proposed
```json
{
    "iRules": [
        {
            "events": [
                {
                    "name": "CLIENT_ACCEPTED",
                    "avgCycles": 15820,
                    "totalExecutions": 86160
                }
            ],
            "name": "/Actuarial/Shared/USR_actuarial_HTML_rewrite_Rule",
        }
    ]
}
Events being an array should make it so summing up all of an iRules' event types needn't require hardcoding all the differently named events in an eval statement, instead summing up whatever events are present in the message.

```

### Describe alternatives you've considered
In order to parse the event in the current structure requires significant CPU expense on the Splunk side to re-parse (re-chunk the events) so that it can be visualized within a graph.  We also have to hard code a number of values for event names in an eval statement so that we can properly tally the data.  This creates extra burden on Splunk when new events are introduced.

**Comment by dstokesf5** [comment]
Does the multi-metric output solve your issue? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#splunk-multi-metric-format

**Comment by walterk82** [comment]
Yes, the does improve the situation at the expense of learning how to use metric data types.  However, if you are still supporting the non multi-metric output, I would think this request still has merit.

**Comment by dstokesf5** [comment]
Does forwarding the data through an Open Telemetry collector provide the data in a better format for your use case?
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#opent
