### ISSUE TITLE
Reduce event size for Splunk consumer

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-telemetry-streaming#102]
### Is your feature request related to a problem? Please describe.
When a BIG-IP is considered "large" i.e. MANY VIPs for multiple tenants and many iRules being deployed, the size the telemetry data can be come very large.  This isn't necessarily a problem in of itself but it becomes an issues with the way that TS performs an event publish at each marked interval.  When the interval fires, all event data is wrapped into a single JSON message to be sent to the registered consumer.  In the case of Splunk, this JSON event can be in excess of 1MB for each sampling interval.  Because there is so much data buried in this event, customers are not able to selectively filter event data.  Additionally, performing stats aggregation becomes CPU intensive since so much data has to be processed.

### Describe the solution you'd like
The default system poller should provide a method in which the top level items can be pruned down, or provide a way to only have 1 top level metric type to limit the size of the resulting JSON document.  Other options for filtering could be to define Administrative Partitions (maybe based on regex or for every) for which stats should be emitted.

Maybe events for each sampling interval could be emitted in these cases:
- General Device Stats
    - CPU / Memory
- _Common_ Partition
    - Virtuals
    - iRules
    - SSL Profiles
- Customer Defined Partition(s)
    - Virtuals
    - iRules
    - SSL Profiles

### Describe alternatives you've considered
I am looking to see if we can use multiple system pollers using the include / exclude options to prune down the size of the default event.  However, I don't see any options that pertain to partition specific boundaries.

**Comment by dstokesf5** [comment]
Does forwarding the data through an Open Telemetry collector provide the data in a better format for your use case?
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#opent

**Comment by walterk82** [comment]
That sounds interesting, but would also require that I have OTel setup for Splunk, which I don't at this time.  https://www.splunk.com/en_us/blog/conf-splunklive/announcing-native-opentelemetry-support-in-splunk-apm.html

I think that has some metric, but does add to the complexity for conversion.  I know that you just add Splunk MultiMetric consumer, which I am using and I know know how OTel with Splunk would handle these metric data types going forward.

**Comment by dstokesf5** [comment]
You can use an OTel collector to receive the data from Telemetry Streaming and have it export the data in the Splunk HEC format: https://github.com/open-telemetry/opentelemetry-collector-contrib/
