### ISSUE TITLE
Support TLS Client Authentication for Generic HTTP Consumer

### ISSUE THREAD

**Issue by chhyde** [F5Networks/f5-telemetry-streaming#104]
### Is your feature request related to a problem? Please describe.
I am working with a customer that requires TLS client authentication for connections to an HTTP process on their Apache NiFi server.  The HTTP process for the NiFi server supports basic authentication and TLS client authentication.  The F5 Telemetry Streaming package would connect to this HTTP process using a Generic HTTP consumer and this consumer allows for an APIkey or possibly a authorization header included as an HTTP header.  It does not look like TLS client authentication is an option.

### Describe the solution you'd like
Add support for TLS Client Authentication to the F5 Telemetry Streaming client for Generic HTTP consumers.

### Describe alternatives you've considered
While Apache NiFi does support an APIKey for authentication, the customer's policy does not support direct API connection to the NiFI server for this use case.  This is the reason for the use of the HTTP process on the NiFi server with the associated limitation on the supported authentication mechanisms.

**Comment by dstokesf5** [comment]
I have added this request to our internal product backlog as AUTOTOOL-2149.

**Comment by dstokesf5** [comment]
This was resolved with the 1.18.0 release of Telemetry Streaming.
