### ISSUE TITLE
Add CPU plane metrics to Prometheus pull consumer

### ISSUE THREAD

**Issue by ajgerace** [F5Networks/f5-telemetry-streaming#106]
### Is your feature request related to a problem? Please describe.
Currently the only CPU stats available via prometheus are f5_system_cpu and f5_system_tmmCpu. As part of the BIG-IP Dashboard we can see Control Plane CPU usage. It would be great if we could make this accessible to prometheus. 

### Describe the solution you'd like
Add new metrics for f5_system_controlPlaneCpu and f5_system_analyticsPlaneCpu

### Describe alternatives you've considered
Was going to look at custom_endpoints to see if I could pull data directly from REST

**Comment by dstokesf5** [comment]
Telemetry Streaming sources data from iControl REST. I am trying to find an endpoint that will provide this information.

Do you know any way, besides the GUI, to get control plane CPU usage of the BIG-IP?

**Comment by dstokesf5** [comment]
Have you tried using the `analytics/realtime/cpu` endpoint with Telemetry Streaming's custom endpoint feature? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/custom-endpoints.html
