### ISSUE TITLE
Telemetry API returns IP%25RD(RoutedomainID) in pool member name if pool member is added with name as IP%RD(RoutedomainID)

### ISSUE THREAD

**Issue by vishwajeetgslab** [F5Networks/f5-telemetry-streaming#108]
### Environment
 * Telemetry Streaming Version:1.16.0
 * BIG-IP Version:15.1.0.5

### Summary
Telemetry API returns IP%25RD(RoutedomainID) in pool member name if pool member is added with name as IP%RD(RoutedomainID)
e.g Pool member added with name as 198.198.1.1%26 on BIG-IP return 198.198.1.1%2526 for telemetry API pool member name

### Steps To Reproduce
1.Add a pool member to a pool with name and address as IP%RD (eg-198.198.1.1%26) . Note- 26 is the route domain for that node.

2.Check Telemetry API response to get the telemetry stats for that pool-
https://BIG-IP/mgmt/shared/telemetry/pullconsumer/My_Pull_Consumer

Please find below response for pool having RD pool member -
"/RD_without_Default_ID/http_RD":{"activeMemberCnt":0,"curPriogrp":0,"highestPriogrp":0,"lowestPriogrp":0,"mr.msgIn":0,"mr.msgOut":0,"mr.reqIn":0,"mr.reqOut":0,"mr.respIn":0,"mr.respOut":0,"serverside.bitsIn":0,"serverside.bitsOut":0,"serverside.curConns":0,"serverside.maxConns":0,"serverside.pktsIn":0,"serverside.pktsOut":0,"serverside.totConns":0,"availabilityState":"unknown","enabledState":"enabled","status.statusReason":"The children pool member(s) either don't have service checking enabled, or service check results are not available yet","totRequests":0,"name":"/RD_without_Default_ID/http_RD","members":{"/RD_without_Default_ID/198.198.1.1%2526:80":{"addr":"198.198.1.1%26","monitorStatus":"checking","mr.msgIn":0,"mr.msgOut":0,"mr.reqIn":0,"mr.reqOut":0,"mr.respIn":0,"mr.respOut":0,"port":80,"serverside.bitsIn":0,"serverside.bitsOut":0,"serverside.curConns":0,"serverside.maxConns":0,"serverside.pktsIn":0,"serverside.pktsOut":0,"serverside.totConns":0,"availabilityState":"unknown","enabledState":"enabled","status.statusReason":"Pool member service checking is enabled, but result is not available yet","totRequests":0}},"tenant":"RD_without_Default_ID"}}

### Expected Behavior
Telemetry API response should return pool name same as on BIG-IP for route domain node (eg. IP%RD)

### Actual Behavior
Telemetry API returns IP%25RD(RoutedomainID) in pool member name if pool member is added with name as IP%RD(RoutedomainID)

**Comment by dstokesf5** [comment]
This is due to URL encoding of the name. I have added AUTOTOOL-2164 to our internal product backlog to investigate if this encoding is necessary and to either remove it or appropriately document it.

**Comment by dstokesf5** [comment]
This issue was resolved in the 1.19.0 release.
