### ISSUE TITLE
Splunk debug output does not log HTTP Response payload

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-telemetry-streaming#109]
### Is your feature request related to a problem? Please describe.
When enable TS debug mode and a Splunk consumer is in use that HTTP status code is logged (403) but the response payload is only logged as:
Tue, 12 Jan 2021 20:04:25 GMT - finest: [telemetry.Splunk.Splunk_Consumer] response: 403 Forbidden
Tue, 12 Jan 2021 20:04:25 GMT - finest: [telemetry.Splunk.Splunk_Consumer] response body: [object Object]

### Describe the solution you'd like
the response body should be logged as Splunk also uses detailed response codes to indicate the type of failure in the case of an http stats 400 error

https://docs.splunk.com/Documentation/Splunk/8.1.1/Data/TroubleshootHTTPEventCollector#Possible_error_codes

### Describe alternatives you've considered
None

### Additional context
```json
    "Controls": {
        "class": "Controls",
        "logLevel": "debug"
    },
    "Splunk_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Splunk",
        "protocol": "https",
        "host": "splunkhec.domain.com",
        "port": 443,
        "passphrase": {
            "cipherText": "apikey"
        },
        "format": "multiMetric",
        "enable": true,
        "trace": "/shared/tmp/ts-splunk_metrics-trace.log"
    }
```

**Comment by dstokesf5** [comment]
This issue was resolved in the 1.19.0 release.
