### ISSUE TITLE
Virtual server clientside-curConns always show 0.

### ISSUE THREAD

**Issue by DJR-FP** [F5Networks/f5-telemetry-streaming#110]
### Environment
 * Telemetry Streaming Version:1.16.0
 * BIG-IP Version:15.1.0.3

### Summary
I have an F5 streaming to Graphie/Statd this looks to be working and displaying the stats required although with the exception of the virtual server clientside-curConns. This always show 0. Any advise on the issue or point me to logs that may point to the issue ?

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "message": "success",
    "declaration": {
        "class": "Telemetry",
        "FPlabs_TelemetrySystem": {
            "class": "Telemetry_System",
            "allowSelfSignedCert": true,
            "systemPoller": {
                "interval": 60,
                "enable": true,
                "actions": [
                    {
                        "setTag": {
                            "tenant": "`T`",
                            "application": "`A`"
                        },
                        "enable": true
                    }
                ]
            },
            "enable": true,
            "host": "localhost",
            "port": 8100,
            "protocol": "http"
        },
        "GraphiteConsumer": {
            "class": "Telemetry_Consumer",
            "type": "Graphite",
            "host": "192.168.70.52",
            "protocol": "http",
            "port": 80,
            "enable": true,
            "trace": false,
            "allowSelfSignedCert": false,
            "path": "/events/"
        },
        "StatsdConsumer": {
            "class": "Telemetry_Consumer",
            "type": "Statsd",
            "host": "192.168.70.52",
            "protocol": "udp",
            "port": 8125,
            "enable": true,
            "trace": false,
            "allowSelfSignedCert": false
        },
        "MyTelemetryListener": {
            "class": "Telemetry_Listener",
            "port": 6514,
            "enable": true,
            "trace": false,
            "match": "",
            "actions": [
                {
                    "setTag": {
                        "tenant": "`T`",
                        "application": "`A`"
                    },
                    "enable": true
                }
            ]
        },
        "schemaVersion": "1.16.0"
    }
}
```
##
Graphite shows 0 connections
```
stats.gauges.f5telemetry.testbox1-lab20-com.virtualServers.-Common-owasp_fplabs_vs.clientside.curConns
```

at the same time get from postmans shows
https://172.16.51.70/mgmt/tm/ltm/virtual/~Common~owasp_fplabs_vs/stats
```
 "clientside.curConns": {
                        "value": 56
                    },
```
#####

Updated the telemtry package to f5-telemetry-1.17.0-4.noarch	

Updated BIG-IP to 15.1.2

no difference, still 0 on curConns

**Comment by dstokesf5** [comment]
Is graphite always showing 0 connections, or do you just see an occasional and unexpected value of 0? A quick review of our testing shows that the value should be forwarded from iControl REST to Graphite, so I am trying to get a better idea of the issue you are encountering.

**Comment by DJR-FP** [comment]
Most of the time it shows 0 connections, It's only if I leave a browser open to a webpage / virtual server I eventually get the connections to go to one. Although the actual connection count is double figures.

**Comment by DJR-FP** [comment]
I have a fix for the issues I was having. I I spin up a VM with a passthrough to the physical NIC I get all the stats in realtime, so looks like a strange issue in the virtual NIC world. I am going to do some testing with different NIC's yo see if I can narrow down the issue.

**Comment by dstokesf5** [comment]
Were you able to narrow down the issue with further testing?

**Comment by DJR-FP** [comment]
never got any closer to the issue, I can only assume that its something to do with the virtual network adaptor, I did try different types and on different hardware but the results were the same. I'm happy to reproduce the issue and gather any stats if needed.

**Comment by dstokesf5** [comment]
Are you able to confirm if tmsh and iControlREST also report a zero when you get a zero in Graphite? I know you posted some iControlREST output. However, it is unclear to me if there is any time delay between the Graphite and iControl REST reading.
