### ISSUE TITLE
Cloudwatch metrics: change of the metrics' dimensions

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#113]
### Is your feature request related to a problem? Please describe.

I'm looking for a way to change the cloudwatch metrics dimensions.
The one used by default are not relevant for a VE device on the cloud (AWS), such as
- chassisId
- machineId
- platformId

I haven't found any thing relvant in the documentation. Only directly in the code I do see:
https://github.com/F5Networks/f5-telemetry-streaming/blob/2eedf62193f60c83f7a05a3114f0e24f94b7129f/src/lib/consumers/AWS_CloudWatch/index.js#L29-L32
and the source
https://github.com/F5Networks/f5-telemetry-streaming/blob/2eedf62193f60c83f7a05a3114f0e24f94b7129f/src/lib/consumers/AWS_CloudWatch/awsUtil.js#L97-L111

### Describe the solution you'd like

I would like to be able to select my own dimensions. And also some custom ones (constant string that I set, representing my cluster-id for example)

### Describe alternatives you've considered
Apart changing the code directly, I haven't considered any.

### Additional context
![image](https://user-images.githubusercontent.com/17331976/107548897-7af1c780-6bcf-11eb-8fab-313a6424ae60.png)

**Comment by dstokesf5** [comment]
Have you considered using the [Data Modification](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/data-modification.html) feature set to filter out some of the data before sending it to the consumer?

**Comment by amolari** [comment]
As far as I understand, with Data modification I would be able to add/change/remove metrics, but not the dimensions sent with the metrics, isn't it?

**Comment by dstokesf5** [comment]
I believe you are correct. It looks like that would not affect the dimensions that are being sent.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this feature request to our internal product backlog as AUTOTOOL-2597.

**Comment by dstokesf5** [comment]
Is this a feature that you are still interested in? We would like to remove it from our product backlog if you no longer need it.

**Comment by amolari** [comment]
@dstokesf5 it's ok for me if it's removed.

**Comment by dstokesf5** [comment]
Thank you! I am closing this issue. If someone else needs it, they are more than welcome to file a new issue.
