### ISSUE TITLE
Add customizable metric "dimensions" to Statsd consumer

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#116]
### Is your feature request related to a problem? Please describe.
The metrics sent actually with Statsd are too "poor", as the only useful dimension is the hostname (in addition to the default `f5telemetry` "namespace"). Example:
`f5telemetry.ip-whatever-eu-west-1-compute-internal.iRules.-Common-_sys_auth_ssl_ocsp.events.CLIENT_ACCEPTED.priority:500|g`

### Describe the solution you'd like
We would like to add more dimensions to the metric, configurable in the consumer configuration. Example:
`f5telemetry.<customParam_cluster_id>.<customParam_instance-id>.<customParam_version>.<customParam_whatever>.ip-whatever-eu-west-1-compute-internal.iRules.-Common-_sys_auth_ssl_ocsp.events.CLIENT_ACCEPTED.priority:500|g`

Additionally, please make the `f5telemetry` "namespace" also customizable.

### Describe alternatives you've considered
None. Statsd is tcp or udp, so we can't send extra parameters (such as with HTTP... tags in the header) to get metric enrichment on an intermediate system such as Logstash, that would transform Statsd to Statsd.

**Comment by dstokesf5** [comment]
@amolari Would a fixed prefix/namespace string be sufficient (e.g 'f5telemetry.cluster-1.instance-3'), or do you need some variable replacement (e.g. 'f5telemetry.${cluster-id}.${instance-id}'?

**Comment by amolari** [comment]
@dstokesf5 I need some variable replacement, I could pass in the declaration. The order should be settable. 

The namespace "f5telemetry" should be the default value, but it should be possible to set it (as in AWS_Cloudwatch consumer)

**Comment by dstokesf5** [comment]
I have added AUTOTOOL-2309 to our internal product backlog to be able to specify custom dimensions for the StatsD consumer.

**Comment by dstokesf5** [comment]
Is this a feature that you are still interested in? We would like to remove it from our product backlog if you no longer need it.

**Comment by dstokesf5** [comment]
Thank you! I am closing this issue. If someone else needs it, they are more than welcome to file a new issue.
