### ISSUE TITLE
Issue: events not sent with timestamp in iso-date format, after setting syslog iso-date enabled

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#117]
### Environment
 * Telemetry Streaming Version: 1.17
 * BIG-IP Version: 14.1.3.1

### Summary
Setting my syslog properties to iso-date=enabled
My local logs then have the proper timestamp format:
`2021-03-01T18:27:22.730+01:00 <hostname_masked> info audit_forwarder[30858]: audit_forwarder started.`

Events sent through Telemetry Listener -> Generic_HTTP still use the previous timestamp (default) format, not the new one.
Restarted restnoded, issue persists.

Ref: https://github.com/F5Networks/f5-telemetry-streaming/issues/4

### Steps To Reproduce
```
tmsh modify sys syslog iso-date enabled
bigstart restart restnoded
```
### Expected Behavior
Events' timestamp sent by consumers should be in iso format (local logs have it in that format).

### Actual Behavior
No change in timestamp format

Output from a tcpdump:
 ```
       POST /event HTTP/1.1
        content-type: application/json
        x-api-key: blob
        User-Agent: f5-telemetry/1.17.0
        host: <masked>
        content-length: 264
        Connection: close

        {"data":"<133>Mar  2 01:11:02.960 <hostname_masked> notice icrd_child[25844]: 25844,25967,    iControl REST Child Daemon,WARNING,[api-status-warning]: ltm/pool: no status; properties: deprecated: ltm/pool/autoscale-group-id","telemetryEventCategory":"event"}
```

**Comment by dstokesf5** [comment]
It looks like the data that is being sent to Telemetry Streaming has the wrong date format. This may be a BIG-IP bug where the `iso-date` property is not being applied to remote syslog messages.

**Comment by dstokesf5** [comment]
@amolari I suggest filing an F5 support case about `iso-date` not applying to remote syslogs. As for Telemetry Streaming, we could convert this issue over to a feature request for an option to overwrite the timestamp of syslog events if you are interested in that.
