### ISSUE TITLE
AWS CloudWatch metrics, diskStorage Capacity not seen

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#119]
### Environment
 * Telemetry Streaming Version: 1.18
 * BIG-IP Version: 14.1.3.1

### Summary
In AWS CloudWatch, the metric `F5_system_diskStorage_Capacity` is not visible (but `F5_system_diskStorage_1024-blocks` is).

### Expected Behavior
We can see the metric `F5_system_diskStorage_Capacity`, as it's configured in the properties.json:
https://github.com/F5Networks/f5-telemetry-streaming/blob/52fadd4b1e393cd91e8d11b4f1afc1ffb608b887/src/lib/properties.json#L226-L234

Note: wouldn't it make sense to get metrics *only* for non tempfs/devtempfs devices? Replacing the command
https://github.com/F5Networks/f5-telemetry-streaming/blob/52fadd4b1e393cd91e8d11b4f1afc1ffb608b887/src/lib/paths.json#L149

with
`/bin/df -P -x tmpfs -x devtmpfs | /usr/bin/tr -s ' ' ','`
### Actual Behavior
In AWS CloudWatch, only the metrics `F5_system_diskStorage_1024-blocks` are visible.

**Comment by amolari** [comment]
It seems to be an issue on the AWS CloudWatch consumer side: with the Generic_HTTP consumer I can see the metric.

**Comment by dstokesf5** [comment]
I believe this is occurring because most metrics only TS consumers filter out non-metrics data. In this case, the percent character in the capacity field is likely preventing it from being used. I have filed this bug in our internal product backlog as     AUTOTOOL-2311.

**Comment by amolari** [comment]
@dstokesf5 You are right, if I change the path.json to be
`"utilCmdArgs": "-c \"/bin/df -P -xdevtmpfs -xtmpfs | /usr/bin/tr -s ' ' ',' | /usr/bin/tr -d '%'\""`
it works.
Would you agree to change it that way (including exclusion of devtmpfs and tmpfs)?

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 1.20.0 release.
