### ISSUE TITLE
TS with per-app VE

### ISSUE THREAD

**Issue by chrislan16** [F5Networks/f5-telemetry-streaming#12]
##### ISSUE TYPE
 - Documentation Report

##### Telemetry Streaming BUILD/ VERSION
1.3.0

##### BIGIP VERSION
14.1.0.3

##### SUMMARY
There is no information provided how to setup TS with tmm IPv6 link local address under https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/userguide/event-listener.html#configure-the-log-publisher-using-tmsh

##### EXPECTED RESULTS
Would be nice to have a step by step guide how to configure TS with IPv6 link local address.
Are there any concerns why you can't always use it (not only with per App VE)?

##### ACTUAL RESULTS
I have tried to add all IPv link local addresses provided by ifconfig to the telemetry pool but no member was reachable via tcp healthcheck.
[TS-declaration.txt](https://github.com/F5Networks/f5-telemetry-streaming/files/3250555/TS-declaration.txt)

**Comment by focrensh** [comment]
Investigating proper way to provision this. TS is able to receive data via TMM IPv6 link-local address.

**Comment by petrov-serg** [comment]
@chrislan16 

1) IPv6 link local address 
```
# ip -6 a s tmm scope link
7: tmm: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::298:76ff:fe54:3210/64 scope link
       valid_lft forever preferred_lft forever
```

2) Create pool
```
tmsh create ltm pool telemetry members replace-all-with { fe80::298:76ff:fe54:3210.6514 }
```

3) Continue configuration from step #4 (https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/userguide/event-listener.html#configure-the-log-publisher-using-tmsh)

**Comment by dstokesf5** [comment]
The documentation was updated as part of the 1.8.0 release. Closing this issue. If you are still experiencing a problem, please create a new issue or reopen this one.
