### ISSUE TITLE
TS has no information about the CPU usage of virtual server

### ISSUE THREAD

**Issue by jinnery** [F5Networks/f5-telemetry-streaming#121]
TS has no information about the CPU usage of virtual server

My configuration:
{
    "class": "Telemetry",
    "My_System": {
        "class": "Telemetry_System",
        "systemPoller": {
            "interval": 60
        }
    },
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514
    },
    "My_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Generic_HTTP",
        "host": "192.168.40.239",
        "protocol": "http",
        "port": 9880,
        "path": "/fluentd.tag",
        "method": "POST",
        "headers": [
            {
                "name": "content-type",
                "value": "application/json"
            }
        ]
    }
}

fluentd output：
![image](https://user-images.githubusercontent.com/18481273/111410966-b1fa5200-8714-11eb-8134-2da3913a3986.png)

CPU utilization AVG is very important to me

 help me please！

**Comment by dstokesf5** [comment]
Please resubmit this issue following one of the provided issue templates. That will help us more easily investigate and track your issue.
