### ISSUE TITLE
Add virtual server stat "clientside.slowKilled"

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-telemetry-streaming#125]
### Describe the solution you'd like
Report virtual server metric name "clientside.slowKilled" via Splunk Multi-Metric Consumer

### Describe alternatives you've considered
Custom Endpoints are an option, however the data isn't normalized and aggregated with splunk multi-metric since they use a different storage format.

### Additional context
This metric datapoint is require for proper health monitoring for BIG-IP slow flow eviction policies. https://support.f5.com/csp/article/K15821

**Comment by walterk82** [comment]
It's possible that "clientside.evictedConns" should also be reported at the same time also related to eviction policies.

**Comment by walterk82** [comment]
There is a similar device level metric under 
/mgmt/tm/sys/tmm-traffic/stats

**Comment by dstokesf5** [comment]
Thank you for this feature request. I have added it to our internal product backlog as AUTOTOOL-2600.

**Comment by dstokesf5** [comment]
This issue has been resolved with the 1.22.0 release of Telemetry Streaming.
