### ISSUE TITLE
Statistics anomaly : f5_counterBitsIn showing 1.1 Tbps throughput

### ISSUE THREAD

**Issue by meghdivya** [F5Networks/f5-telemetry-streaming#126]
### Environment
 * Telemetry Streaming Version: 1.12.0
 * BIG-IP Version: 13.1.1.4

### Summary
Please also include information about the reproducibility and the severity/impact of the issue.

### Steps To Reproduce
1. Submit the following declaration:
```
{
    "class": "Telemetry",
    "My_Poller": {
        "class": "Telemetry_System_Poller",
        "interval": 60
    },
    "Custom_Endpoints": {
    "class": "Telemetry_Endpoints",
        "items": {
             "detailedCPU": {
                 "name": "detailedCPU",
                 "path": "/mgmt/tm/sys/host-info"
             },
             "systemHostname": {
                 "name": "system",
                 "path": "/mgmt/tm/sys/global-settings"
            }
        }
    },
    "Custom_System_Poller1": {
        "class": "Telemetry_System_Poller",
        "interval": 60,
        "endpointList": "Custom_Endpoints"
    },
    "My_Pull_Consumer": {
        "class": "Telemetry_Pull_Consumer",
       "type": "Prometheus",
        "systemPoller": ["My_Poller", "Custom_System_Poller1"]
    },
    "My_System": {
        "class": "Telemetry_System",
        "enable": "true",
        "systemPoller": ["My_Poller", "Custom_System_Poller1"]
    }
   }
```

### Expected Behavior
Throughput should not exceed values in MBPS. I confirmed the same from F5 statistics GUI .

### Actual Behavior
Seeing throughput in Tbps in our grafana dashboards

**Comment by dstokesf5** [comment]
Just to make sure we are on the same page, is the metric in question the `f5_counters_bitsIn` metric for a network interface? Also, can you elaborate more on what you mean by "I confirmed the same from F5 statistics GUI". Did you confirm that the GUI displayed the correct value, or did it display the same value that was seen in Grafana? Finally, if you happen to know the endpoint that the property in question is coming from, are you able to confirm if the value is being reported correctly in the iControl REST API?

**Comment by dstokesf5** [comment]
Are you doing anything in Grafana to convert the bitsIn value from a total count to a rate value?

**Comment by meghdivya** [comment]
@dstokesf5 
I meant, GUI displayed the correct value. It's not frequent. I couldn't confirm it with iControl REST APIs. We see the deviation in our grafana rate queries.
We are plotting aggregated views of mgmt and network interface. Please, refer to the query in the end
This anomaly is not limited to one metric. Following metrics were also been reported with undesriable values:
 f5_counters_bitsOut, f5_numberReqs, f5_2xxResp, f5_serverside_bitsIn 
 
Yes, We are using a rate function as below:
sum(rate(f5_counters_bitsIn{host=~"(.+)"} [2m])) by (host)

**Comment by meghdivya** [comment]
It was a spike seen in grafana for networkInterface=1.1 . It lasted only for 1-2 minutes.

**Comment by dstokesf5** [comment]
How often do you see this data anomaly? It would be very helpful to know what the `/mgmt/tm/net/interface/stats` iControl REST endpoint and the Prometheus consumer (`/mgmt/shared/telemetry/pullconsumers/My_Pull_Consumer`) are showing when you see this anomaly. That will help us determine if there is an issue with the iControl REST API, Telemetry Streaming, or your Grafana configuration.

**Comment by meghdivya** [comment]
This anomaly is randomly occurring on different nodes in production. Frequency could be weekly once or twice.
How can I get the historical stats using the iControl REST endpoint?

**Comment by dstokesf5** [comment]
Unfortunately, I am unaware of a way to get historical data from iControl REST.

Do you see this same data anomaly with the new OpenTelemetry consumer? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#opent
