### ISSUE TITLE
Typo in error message "Unable to send data chuck: Error: badResponse"

### ISSUE THREAD

**Issue by M0JFP** [F5Networks/f5-telemetry-streaming#13]
##### ISSUE TYPE

 - Bug Report

##### Telemetry Streaming BUILD/ VERSION

```
1.4.0-1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0.5
  Build       0.0.5
  Edition     Point Release 5
  Date        Tue May 14 11:15:38 PDT 2019
```

##### SUMMARY

when looking at the log I am guessing there is a typo Chunk / Chuck

tail /var/log/restnoded/restnoded.log -f

Mon, 24 Jun 2019 12:13:28 GMT - severe: [telemetry.Splunk] Unable to send data chuck: Error: badResponse
Mon, 24 Jun 2019 12:14:28 GMT - severe: [telemetry.Splunk] sendDataChunk::response error:
{
  "error": {
    "code": "SELF_SIGNED_CERT_IN_CHAIN"
  }
}
Mon, 24 Jun 2019 12:14:28 GMT - severe: [telemetry.Splunk] Unable to send data chuck: Error: badResponse

```

```

##### STEPS TO REPRODUCE

```
tail /var/log/restnoded/restnoded.log -f

output suggested typo:  
Mon, 24 Jun 2019 12:14:28 GMT - severe: [telemetry.Splunk] Unable to send data chuck: Error: badResponse

Chuck should be chunk?
```

##### EXPECTED RESULTS

Mon, 24 Jun 2019 12:14:28 GMT - severe: [telemetry.Splunk] Unable to send data chunk: Error: badResponse

##### ACTUAL RESULTS

Just a typo, nothing major 

```
 tail /var/log/restnoded/restnoded.log -f
```

**Comment by petrov-serg** [comment]
Issue solved in 1.5.0.
