### ISSUE TITLE
Include ASM XML/JSON memory usage in system poller output

### ISSUE THREAD

**Issue by oakh1** [F5Networks/f5-telemetry-streaming#135]
### Describe the solution you'd like
I would like to have the ASM XML/JSON memory usage exported from the system poller. When we've had memory issues it has most commonly been this memory that has been exceeded as it's not "easily" monitored like other memory usage statistics.

The command to extract the statistics is: (taken from https://support.f5.com/csp/article/K91039252)
tmctl asm_memory_util_stats -s total_xml_mem_used,total_xml_max_mem |  awk '(c!=0&&c!=1&&$2) {print $1"KB "$2"KB " $1*100/$2"%"} {c++}'

**Comment by walterk82** [comment]
I would be interested in this value as well because this information is needed to size ASM handling for XML/JSON validation.  Without proper sizing, this value requests will result in a blocked requests.

**Comment by dstokesf5** [comment]
Unfortunately, reporting tmctl data poses some difficulties when it comes to documentation. Do you happen to have a way to gather that data from iControl REST?

**Comment by dstokesf5** [comment]
I have added this feature request to our internal product backlog as AUTOTOOL-2599. However, the use of tmctl to gather the data still poses issues.

**Comment by dstokesf5** [comment]
Without a way to gather this data outside of tmctl, we are unable to support this feature request. If a better way to gather this data is found, please reopen this issue or create a new one.
