### ISSUE TITLE
Remove percentage character in numeric data (such as disk usage)

### ISSUE THREAD

**Issue by oakh1** [F5Networks/f5-telemetry-streaming#136]
### Is your feature request related to a problem? Please describe.
When retreiving output from the system poller, such as the diskUsage statistics, it's viewed as "12%". When sending this (without modifying the data) the receiving log-database (in our case, Elastic) will index it as a string instead of a numeric value. This causes the field to be non aggregatable (not being able to make line-charts/visualization on that value)

### Describe the solution you'd like
Remove the % sign from the diskUsage (and other statistics where its included) so it's a number/integer instead of a string. Or include the numeric value as an additional property.

### Describe alternatives you've considered
Using regex (or equivalent) tool to remove the % signs before indexing it to the database. This is in my eyes an "ugly" solution as it's better if the data is kept untouched as it causes additional overhead/complexity in the logging pipelines.

**Comment by dstokesf5** [comment]
The disk storage as a string with a percent sign is how BIG-IP is reporting the data. Telemetry Streaming does provide an additional "Capacity_Float" field that represents the capacity as a floating point number. An example of this field can be seen in the example output: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/output-example.html.

This additional property was added in version 1.20.0. Does this additional property resolve your issue?

**Comment by oakh1** [comment]
I hadn't seen that, that should definitely be good enough! :) Thanks for the information
