### ISSUE TITLE
The SSL TPS data is not normal

### ISSUE THREAD

**Issue by for-mat** [F5Networks/f5-telemetry-streaming#137]
### Environment
 * Telemetry Streaming Version:  f5-telemetry-1.19.0-3.noarch
 * BIG-IP Version: BIG-IP 13.1.3.6 Build 0.0.4 Point Release 6

### Summary
![image](https://user-images.githubusercontent.com/43637488/122148115-9d049a80-ce8c-11eb-9c6b-a581fb5f8224.png)

I used ’rate(f5_totNativeConns{}[2m])‘  to get the number of SSL connections, but after looking at it for a while, I found that there were occasional abnormal values

### Expected Behavior
I want to know if this is due to the calculation method or if this is the real data, or if the metrics I used are correct.
I hope to get the TPS data of SSL, but due to these abnormal data, I can't normally observe and alarm.

**Comment by for-mat** [comment]
![image](https://user-images.githubusercontent.com/43637488/123721471-fae7a800-d8b8-11eb-866c-d5d912b1bbf2.png)

**Comment by dstokesf5** [comment]
What consumer are you seeing this issue with?

**Comment by for-mat** [comment]
> 你看到这个问题的消费者是什么？

prometheus

**Comment by dstokesf5** [comment]
Do you see this same data anomaly with the new OpenTelemetry consumer? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#opent

**Comment by for-mat** [comment]
> 

I've only used Prometheus, but I've tried different versions of it.Including 1.15.0, 1.19.3, and 1.20.1.

**Comment by for-mat** [comment]
Or if there is a way to mask abnormal noise

**Comment by dstokesf5** [comment]
It looks like users can encounter bad statistics coming from tmsh. Below area a couple of knowledge articles on the subject:
* https://support.f5.com/csp/article/K21811305
* https://support.f5.com/csp/article/K15455

Do these help with your issue?
