### ISSUE TITLE
Splunk Cloud Destination hostname 

### ISSUE THREAD

**Issue by tomomu** [F5Networks/f5-telemetry-streaming#138]
Splunk cloud requires us to enter a URI rather than an IP address. We cannot add a URI to host parameter in the config file:

`"My_Consumer": {
     "class": "Telemetry_Consumer",
     "type": "Splunk",
     "host": "192.0.2.1",
     "protocol": "https",
     "port": "8088",
     "passphrase": {
         "cipherText": "apikey"
     }
 }`

Please allow the use of 'hostname'

**Comment by dstokesf5** [comment]
Please resubmit this issue using one of the provided issue templates. This will allow us to better track and respond to your request.
