### ISSUE TITLE
Splunk Cloud Destination hostname 

### ISSUE THREAD

**Issue by tomomu** [F5Networks/f5-telemetry-streaming#139]
### Is your feature request related to a problem? Please describe.
Splunk cloud requires us to enter a URI rather than an IP address. We cannot add a URI to host parameter in the config file:

"My_Consumer": { "class": "Telemetry_Consumer", "type": "Splunk", "host": "192.0.2.1", "protocol": "https", "port": "8088", "passphrase": { "cipherText": "apikey" } }

### Describe the solution you'd like

Please allow the use of 'hostname' or complete URI

### Additional context
Splunk cloud requires us to send data to a URI so it can be correctly routed to our tenant. We did try adding domain name to the 'host' parameter and path to the 'path' parameter but the F5 then forwarded telemetry traffic to the source VS - 255.255.255.254

**Comment by dstokesf5** [comment]
Thank you for resubmitting the issue.

**Comment by dstokesf5** [comment]
It looks like you can already specify a hostname with the Splunk consumer:
```json
"Splunk_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Splunk",
        "host": "inputs.prd-p-lcr5x.splunkcloud.com",
        "protocol": "https",
        "port": 8088,
        "passphrase": {
            "cipherText": "my-hec-token"
        },
        "allowSelfSignedCert": true,
        "trace": true,
        "enable": true
    }
```

What problem are you encountering trying to use this feature?
