### ISSUE TITLE
DNS Caching for Telemetry Streaming

### ISSUE THREAD

**Issue by firefly2000** [F5Networks/f5-telemetry-streaming#140]
### Is your feature request related to a problem? Please describe.

The DNS Caching (profile) is not currently compatible with the analytic log profile for the virtual server. 

### Describe the solution you'd like

Need telemetry information and statistic information for DNS caching and virtual server associated with DNS caching profile. 

### Describe alternatives you've considered

Tried following by removing request logging profile from virtual server and configuring dns caching profile, but no AVR DNS data showing

**Comment by dstokesf5** [comment]
Are you able to use the custom endpoints feature to gather the data you need? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/custom-endpoints.html
