### ISSUE TITLE
Google Cloud Logging Consumer

### ISSUE THREAD

**Issue by f5-applebaum** [F5Networks/f5-telemetry-streaming#143]
### Is your feature request related to a problem? Please describe.

For autoscale deployments, in addition to sending custom metrics, 

https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#google-cloud-operations-suite-s-cloud-monitoring

it also requires remote logging and would like ability to send waf logs to Google's native logging service  
https://cloud.google.com/logging/docs
https://cloud.google.com/logging/docs/samples/logging-write-log-entry-advanced#logging_write_log_entry_advanced-nodejs

Similar to 
AWS:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#aws-cloudwatch
ex.
https://github.com/F5Networks/f5-aws-cloudformation-v2/blob/main/examples/autoscale/bigip-configurations/runtime-init-conf-payg.yaml#L217

Azure:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#microsoft-azure-log-analytics
ex.
https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/main/examples/autoscale/bigip-configurations/runtime-init-conf-payg.yaml#L251

### Describe alternatives you've considered
There are plenty of other external logging consumers but for parity with AWS/Azure, would like to have option for default = native logging service.

**Comment by dstokesf5** [comment]
Thank you for your feedback. This item is in our internal backlog as AUTOTOOL-2453.

**Comment by cnad001** [comment]
Can you please confirm when is this being released?

**Comment by dstokesf5** [comment]
The Google Cloud logging consumer is currently scheduled for the 1.22.0 release in mid-August.

**Comment by dstokesf5** [comment]
This issue has been resolved with the 1.22.0 release of Telemetry Streaming.
