### ISSUE TITLE
Azure Sentinel - over 500 Object issue

### ISSUE THREAD

**Issue by itlinux** [F5Networks/f5-telemetry-streaming#147]
This is not a VM, but I have had the same issue in the Azure side, not for the NIC to show up, since Azure does not offer 40GB interfaces. So there are two cases into one here. 

### Environment
 * Telemetry Streaming Version:
 * BIG-IP Version: 15

### Summary
 We still see the following issues:
	a:	Missing any interface > 2.4 on the dashboard (i.e. 40 gig interfaces)
	b:	Same error regarding “Data of type F5Telemetry_pools was dropped because number of fields”
	c:	We are also missing a “source” (example: hostname_s) data field in the Table F5Telemetry_virtualServers_CL which means you cannot “join” this table to another table in Azure LogAnalytics and include additional data as there is no “source” for the Virtual Server Telemetry.

### Steps To Reproduce
Declaration pushed by vscode, or TF.
1. Submit the following declaration:
```json
{
    "class": "Telemetry",
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514
    },
    "Poller": {
        "class": "Telemetry_System_Poller",
        "interval": 60,
        "enable": true,
        "trace": false,
        "allowSelfSignedCert": false,
        "host": "localhost",
        "port": 8100,
        "protocol": "http",
        "actions": [
            {
                "enable": true,
                "includeData": {},
                "locations": {
                    "system": true,
                    "virtualServers": true,
                    "httpProfiles": true,
                    "clientSslProfiles": true,
                    "serverSslProfiles": true
                }
            }
        ]
    },
    "Pull_Consumer": {
        "class": "Telemetry_Pull_Consumer",
        "type": "default",
        "systemPoller": [
            "Poller"
        ]
    },
    "Azure_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Azure_Log_Analytics",
        "workspaceId": "${law_id}",
        "passphrase": {
            "cipherText": "${law_primkey}"
        }
    },
    "schemaVersion": "1.12.0"
}
```

### Expected Behavior / Actual Behavior
I think with the new build, there is a race condition since out of the 10 deployment with TF, maybe 3 do complete successfully. Also, if I taint the resource (TS), and rerun the TF, it works 99% of the time.

**Comment by dstokesf5** [comment]
@itlinux Could you please separate the problems you are encountering into separate GitHub issues? This allows us to better track and resolve the issues.
