### ISSUE TITLE
Need telemetry logging of metrics and logs to Oracle Cloud Logging for F5 deployments in Oracle Cloud

### ISSUE THREAD

**Issue by cnad001** [F5Networks/f5-telemetry-streaming#149]
For F5 deployments in Oracle Cloud, Need Metric logging and syslog logging to Oracle Cloud logging similar to AWS, Azure

Similar to

Azure:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#microsoft-azure-log-analytics
ex.
https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/main/examples/autoscale/bigip-configurations/runtime-init-conf-payg.yaml#L251

AWS:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#aws-cloudwatch
ex.
https://github.com/F5Networks/f5-aws-cloudformation-v2/blob/main/examples/autoscale/bigip-configurations/runtime-init-conf-payg.yaml#L217

**Comment by dstokesf5** [comment]
Closing this issue for not following a template. Please open a new issue using one of the provided templates. This helps us better understand and track your issue.
