### ISSUE TITLE
Feature request (support BigIQ)

### ISSUE THREAD

**Issue by M0JFP** [F5Networks/f5-telemetry-streaming#15]
##### ISSUE TYPE

 - Feature Idea

##### Telemetry Streaming BUILD/ VERSION

```
1.4.0-1
```

##### BIGIP VERSION

```
BigIQ 6.1.0 / 7.x
```

##### SUMMARY

```
Would it be possible to use TS on BigIQ, and be able to collect data from other BigIP devices?
```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
AT-490 for internal tracking

**Comment by dstokesf5** [comment]
We have decided to drop this item from our product backlog as out of scope.
