### ISSUE TITLE
asmState pseudo-metric: value is incorrect

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#151]
### Environment
 * Telemetry Streaming Version: 1.21
 * BIG-IP Version: 14.1.4

### Summary
Running the command that produces the output for pseudo-metric "asmState" directly on my system, the output doesn't produce the expected result. Therefor, that pseudo-metric result is not valid.
Please either fix the command:

https://github.com/F5Networks/f5-telemetry-streaming/blob/4db2b55fdfc89bd8c31f7f7c0e69e4367e03081a/src/lib/paths.json#L178-L186

or remove that pseudo-metric asmState.

### Steps To Reproduce

asmState metric is the output of command
`/bin/mysql -uroot -p$(/bin/perl -MPassCrypt -nle 'print PassCrypt::decrypt_password($_)' /var/db/mysqlpw) PLC -B -e 'select CASE WHEN max(event_time) IS NOT NULL THEN "Pending Policy Changes" ELSE "Policies Consistent" END as asm_state, max(event_time) as last_asm_change from PL_CONFIG_LOG where event_type <> 2 and element_type <> 18 and event_time > (select max(from_date) as asm_last_changed from PL_POLICY_HISTORY)' | sed 's/\\t/,/'`

My test system has 2 policies which are in PENDING APPLY.

### Expected Behavior
Output of command (which is the value of pseudo-metric) should be `Pending Policy Changes`

### Actual Behavior
Output of command (which is the value of pseudo-metric) is:
```
asm_state       last_asm_change
Policies Consistent     NULL
```

**Comment by dstokesf5** [comment]
This was resolved with the 1.23.0 release of Telemetry Streaming.
