### ISSUE TITLE
Unable to gather AvailabilityState for VirtualServer using the prometheus pull consumer

### ISSUE THREAD

**Issue by meghdivya** [F5Networks/f5-telemetry-streaming#152]
### Is your feature request related to a problem? Please describe.
Using the prometheus pull consumer, it is currently not possible to get data about Virtual Server availabilityState. I have verified the data is available via the default push/pull consumer, the metric I care most about is the availabilityState per Virtual Server. This is very critical for us as we recently shifted to Prometheus pull consumer in all our deployements.

### Describe the solution you'd like
I found out that the availabilityState field for virtual servers is not included in the Prometheus output because it is a string value, which is not supported by Prometheus.
Best way would be including an integer 1 => available , 0 => down.

### Additional context
It's possible I could find (or try and write) my own plugin for grabbing this one piece of data from the default pull consumer, however that seems a bit excessive.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal product backlog as AUTOTOOL-2663.

**Comment by dstokesf5** [comment]
What integer value do you expect for an availabilityState of unknown?

**Comment by meghdivya** [comment]
So, in push consumer model, I would give a string with "UNKNOWN" right? 
Just to distinguish we can give UNKNOWN state as value 2. We will still consider it as available. If value >0 . 
Moreover for our deployments we are mostly tracking virtual servers with Available state, they don't have Unknown State.

**Comment by dstokesf5** [comment]
This was resolved with the 1.23.0 release of Telemetry Streaming.
