### ISSUE TITLE
GCP: Leverage IAM roles for Metrics and Logging

### ISSUE THREAD

**Issue by f5-applebaum** [F5Networks/f5-telemetry-streaming#154]
Per Cloud Best Practices and consistency,

ex.
AWS:
"In TS 1.9.0 and later, the username and passphrase for CloudWatch are optional. This is because a user can send data from a BIG-IP that has an appropriate IAM role in AWS to AWS CloudWatch without a username and passphrase."

Azure:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#using-microsoft-managed-identities-for-log-analytics

Would like GCP 
Metrics:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#google-cloud-operations-suite-s-cloud-monitoring
Logging:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#google-cloud-logging

consumers to leverage IAM roles for when deployed in GCP.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal product backlog as AUTOTOOL-2798.

**Comment by dstokesf5** [comment]
This has been resolved in the 1.25.0 release.
