### ISSUE TITLE
Datadog consumer: Bad status code: 413 Payload too large

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#157]
### Environment
 * Telemetry Streaming Version: 1.22
 * BIG-IP Version: 14.1.4

### Summary
Consumer: Datadog

We have quite some Virtual servers configured on our device. Data is not ingested by Datadog. In the consumer's trace log we see:
`severe: [telemetry.DataDog.My_Metrics_Namespace::My_Datadog_Metrics_Consumer] error: Bad status code: 413 Payload too large for https://api.datadoghq.eu/api/v1/series`

In the [Datadog API metrics doc](https://docs.datadoghq.com/api/latest/metrics/):

> The metrics end-point allows you to post time-series data that can be graphed on Datadog’s dashboards. The maximum payload size is 3.2 megabytes (3200000 bytes). Compressed payloads must have a decompressed size of less than 62 megabytes (62914560 bytes).

The payload is not sent compressed. Please add compression (similar to Splunk consumer)

Note: no issue on test clusters (which has a minimal amount of configured objects)

**Comment by dstokesf5** [comment]
This was resolved with the 1.23.0 release of Telemetry Streaming.
