### ISSUE TITLE
Datadog: add customizable metrics prefix option

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#158]
### Is your feature request related to a problem? Please describe.
Datadog metrics are sent without any prefix.

### Describe the solution you'd like
Be able to define a customizable prefix in the consumer options, which will prepend all the metrics sent to Datadog.
Maybe "namespace" is an appropriate naming for this prefix, as it's already used in other consumer as such.

Example: namespace = "f5"
We see then in Datadog the following metrics:
f5.system.cpu
f5.system.tmmMemory
f5.pools.activeMemberCnt
....

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal product backlog as AUTOTOOL-2794.

**Comment by amolari** [comment]
I guess it had been fixed in v1.25.0?

**Comment by dstokesf5** [comment]
This has been resolved in the 1.25.0 release.
