### ISSUE TITLE
Datadog: customizable metrics API endpoint

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#159]
### Is your feature request related to a problem? Please describe.
The API endpoint where the metrics are sent to is statically defined in the code. It should be customizable.
Datadog has a couple API endpoints, continent-based. The data must be sent to the appropriate endpoint to get ingested, it's
not only a latency/networking concern.

### Describe the solution you'd like
Be able to set a custom API endpoint FQDN in the consumer options. If not provided, the default one (api.datadoghq.com) should be used.
Alternatively (as those endpoint FQDN seem to be quite static), the selection of the site (US or EU)  could do it.

### Additional context
We need to use the EU site endpoint. FQDN=api.datadoghq.eu

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added AUTOTOOL-2752 to our internal product backlog to add region selection to the Datadog consumer.

**Comment by amolari** [comment]
I guess it had been fixed in release v1.24.0?

**Comment by dstokesf5** [comment]
This has been resolved in the 1.24.0 release.
