### ISSUE TITLE
Datadog: add customizable service field option

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#161]
### Is your feature request related to a problem? Please describe.
The service field option, used by Datadog logging, is not customizable but statically defined in the code.
`const DATA_DOG_SERVICE_FIELD = 'f5-telemetry'`

### Describe the solution you'd like
Be able to set a custom value in the Datadog consumer declaration.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added your request to our internal product backlog as AUTOTOOL-2753.

**Comment by amolari** [comment]
I guess it had been fixed in v1.24.0?

**Comment by dstokesf5** [comment]
This has been resolved in the 1.24.0 release.
