### ISSUE TITLE
Datadog: customizable Logs API endpoint

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-telemetry-streaming#162]
### Is your feature request related to a problem? Please describe.
The API endpoint where the logs are sent to is statically defined in the code. It should be customizable.
Datadog has a couple API endpoints, continent-based. The data must be sent to the appropriate endpoint to get ingested, it's
not only a latency/networking concern.

### Describe the solution you'd like
Be able to set a custom API endpoint FQDN in the consumer options. If not provided, the default one (http-intake.logs.datadoghq.com) should be used.
Alternatively (as those endpoint FQDN seem to be quite static), the selection of the site (US or EU) could do it.

### Additional context
e need to use the EU site endpoint. FQDN=http-intake.logs.datadoghq.eu

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added AUTOTOOL-2752 to our internal product backlog to add region selection to the Datadog consumer.

**Comment by dstokesf5** [comment]
This has been resolved in the 1.24.0 release.
