### ISSUE TITLE
New Metric or additional Label for Http Requests failed at BIG-IP modules (LTM/ASM)

### ISSUE THREAD

**Issue by meghdivya** [F5Networks/f5-telemetry-streaming#163]
### Is your feature request related to a problem? Please describe.
We want to get segregation of HTTP response codes with which requests are rejected by BIG-IP modules ASM/LTM and which are coming from backend pools. We are using Prometheus PULL consumer.
Specially for metrics: f5_4xxResp, f5_5xxResp

### Describe the solution you'd like
Following metric is coming today as below:
f5_4xxResp{host="azt1waf-wus-i5prod-A-03-vmss_2",httpProfiles="/Common/http"}

If we have a new Label attached to , it would be really great
f5_4xxResp{host="azt1waf-wus-i5prod-A-03-vmss_2",httpProfiles="/Common/http", failedAt="ltm" }
f5_4xxResp{host="azt1waf-wus-i5prod-A-03-vmss_2",httpProfiles="/Common/http", failedAt="asm" }

### Describe alternatives you've considered
Another alternative could be to have separate metrics:
f5_4xxResp_asm
f5_4xxResp_ltm

### Additional context
Our SRE/NOC teams are always requesting this data from us. As we have layered architecture and requests can be rejected from any hop. F5 BIGIP is a critical hop for our deployments and we need to help them in debugging on critical issues.

**Comment by dstokesf5** [comment]
Our Open Telemetry consumer gathers some additional tag data that it attaches to metrics. Does forwarding the data through an Open Telemetry Collector solve your issue?
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#opent
