### ISSUE TITLE
Convert event data to json-format key-values

### ISSUE THREAD

**Issue by zongzw** [F5Networks/f5-telemetry-streaming#165]
Is that any way to convert data string to json body in Telemetry_Listener? 

I'm using Telemetry_Listener, 
```
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514,
        "trace": true
    }
```
and using 

`curl -ku admin:admin -X POST https://{{ bigip_hostname }}:443/mgmt/shared/telemetry/eventListener/My_Listener -d '{"mykey": "myvalue"}'` to send data to the listener.

The data received from my downstream ELK is:
```
{
    "data": "{\"mykey\":\"myvalue\"}",
    "telemetryEventCategory": "event"
}
```

Is it possible to handle the string data received by event listener to json before sending it to downstream?

```
{
    "data": {
            "mykey": "myvalue"
    },
    "telemetryEventCategory": "event"
}
```

Because I know exactly the data part is json formatted.

**Comment by dstokesf5** [comment]
It looks like it is not well documented, but you can added a key to your JSON payload to tell Telemetry Streaming to do less processing on it.
```json
{
    "mykey": "myvalue",
    "$F5TelemetryEventCategory": "raw"
}
```

Does this work for your use case?
