### ISSUE TITLE
Support custom endpoints for S3/CloudWatch in AWS

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-telemetry-streaming#173]
### Is your feature request related to a problem? Please describe.
A customer is using the S3 consumer for TS and it appears to be sending the data appropriately. However, the data source is an on-prem BIG-IP. For data sources in AWS, I see that routing of a prefix list to the vpce can achieve the reachability desired<sup>1</sup>. However, for devices reaching S3 over a Direct Connect link, a custom endpoint that exists in an existing cloud subnet is needed since the AWS services' prefixes won't be routed end-to-end to the cloud<sub>2</sub>. 

An example of the AWS SDK overwriting an endpoint: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Endpoint.html

Sources: 
1 - https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html#accessing-bucket-and-aps-from-interface-endpoints
2 - https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-access-direct-connect/

### Describe the solution you'd like
A field would be added to the S3 consumer declaration with a custom endpoint field that would override the default gateways.

### Describe alternatives you've considered
The only way I can think to overcome this requirement is to route the AWS services' prefixes into the cloud over the Direct Connect, but that would be too cumbersome as it would need piped from source to destination VPC and could cause conflict with other services' connections.

### Additional context
None at this time.

**Comment by dstokesf5** [comment]
This has been resolved in the 1.25.0 release.
