### ISSUE TITLE
Prometheus pull consumer metrics are labeled as gauges when they should be labeled as counters.

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/f5-telemetry-streaming#175]
### Environment
 * Telemetry Streaming Version: 1.12 to 1.24 
 * BIG-IP Version: 13.1.x to 15.1.x 

### Summary
Prometheus pull consumer metrics are labeled as gauges when they should be labeled as counters.  

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "Telemetry",
    "My_Poller": {
        "class": "Telemetry_System_Poller",
        "interval": 60
    },
    "Custom_Endpoints": {
    "class": "Telemetry_Endpoints",
        "items": {
             "detailedCPU": {
                 "name": "detailedCPU",
                 "path": "/mgmt/tm/sys/host-info"
             },
             "systemHostname": {
                 "name": "system",
                 "path": "/mgmt/tm/sys/global-settings"
            }
        }
    },
    "Custom_System_Poller1": {
        "class": "Telemetry_System_Poller",
        "interval": 60,
        "endpointList": "Custom_Endpoints"
    },
    "My_Pull_Consumer": {
        "class": "Telemetry_Pull_Consumer",
       "type": "Prometheus",
        "systemPoller": ["My_Poller", "Custom_System_Poller1"]
    },
    "My_System": {
        "class": "Telemetry_System",
        "enable": "true",
        "systemPoller": ["My_Poller", "Custom_System_Poller1"]
    }
   }

```

2. Observe the following when the PULL consumer endpoint is queried:
`GET /mgmt/shared/telemetry/pullconsumer/My_Pull_Consumer` 
```
# HELP f5_numberReqs numberReqs
# TYPE f5_numberReqs gauge
f5_numberReqs{httpProfiles="/Common/http"} 5402028
  
# HELP f5_serverside_bitsOut serverside.bitsOut
# TYPE f5_serverside_bitsOut gauge
f5_serverside_bitsOut{pools="/Common/http_pool"} 8470816
f5_serverside_bitsOut{pools="/Common/http_pool",members="/Common/x.x.x.x:80"} 8470816
```

### Expected Behavior
Any metric that is a number that only increases (unless there is a counter reset) should be labeled as a counter. [Counter types](https://prometheus.io/docs/concepts/metric_types/)

### Actual Behavior
It seems all metrics provided by the Prometheus pull consumer are labeled as gauges. Some of the metric should be labeled as gauges however there are a large number of metrics that should be labeled as counters. 

Prometheus interprets the data differently for counters. There are certain functions that should not be used on gauges such as [rate()](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate).  

The customer I am working with is seeing massive artificial graphing anomalys when their dashboards running rate() function against an F5 metric (currently gauge) experiences a counter reset. The customer has opened TS issue for this in the past [here](https://github.com/F5Networks/f5-telemetry-streaming/issues/126) and [here](https://github.com/F5Networks/f5-telemetry-streaming/issues/89).

We believe this is the first step to fixing the massive graphing anomalys because the underlying metric should be classified as a counter rather than gauge.

**Comment by ghalevy** [comment]
Please prioritize this issue in next release, it is very impactful to my use case.

**Comment by delgadillo22** [comment]
We are looking into this. Stay tuned.

**Comment by megamattzilla** [comment]
Upon further testing it appears simply changing the label of these metrics to counter wont resolve our underlying issue.  

It is more accurate to label counter type metrics as counters so this git issue is still valid; however this does not change the outcome when rate() function is applied. 

1.) Example when a metric (f5_2xx) labeled as counter experiences a dip:
![prometheus_dip](https://user-images.githubusercontent.com/45299091/140560810-b43af741-5c6a-4b52-ab49-b88bdfc20bb4.png)

2.) The rate function still shows a massive comsmetic issue: 
![prometheus_dip_rate](https://user-images.githubusercontent.com/45299091/140560827-e96ded17-6eaf-413b-8fcf-b8108b10b975.png)

We do not yet understand why TS Prometheus PULL consumer is intermittently showing a "counter" metric as decreasing (but not zero) and then returning to normal on the next scrape interval (see screenshot number 1). 

We have a support SR open for this. Any tips on debugging TS would be appreciated. Is there a way to validate what data is returned on a PULL consumer request to TS?

**Comment by dstokesf5** [comment]
@megamattzilla Do you see the same data anomalies when forwarding data through an Open Telemetry Collector?
* https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#opentelemetry-exporter-experimental
* https://opentelemetry.io/docs/collector/getting-started/

**Comment by mjmenger** [comment]
If you experience this issue try implementing the workaround described in https://support.f5.com/csp/article/K21811305
