### ISSUE TITLE
Trace not working on System_Poller when using Pull Consumer (Prometheus) 

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/f5-telemetry-streaming#180]
### Environment
 * Telemetry Streaming Version: 1.20.1 and later 
 * BIG-IP Version: 13.1.4 

### Summary
When enabling the trace functionality on a system_poller using a Pull consumer, no trace file is generated. 

### Steps To Reproduce
1. Submit the following declaration:
```json
{
"My_Pull_Consumer": {
    "type": "Prometheus",
    "class": "Telemetry_Pull_Consumer",
    "systemPoller": "My_Poller"
},
"My_Poller": {
        "class": "Telemetry_System_Poller",
        "interval": 0,
        "trace": true
    },
"My_System": {
        "class": "Telemetry_System",
        "enable": "true",
        "systemPoller": "My_Poller"
    },
"class": "Telemetry",
"schemaVersion": "1.20.1"
}

```

2. The Declaration is successfully submitted. The Pull consumer works as expected however no trace file is generated in /var/tmp/telemetry. 

### Expected Behavior
A trace file to be generated in /var/tmp/telemetry containing the data from the system_poller when called by the Pull consumer. 

### Actual Behavior
No Trace file. 

I did notice if I set the system_poller interval to 60, a trace file is generated every 60 seconds- however it does not contain any data which is gathered by the system_poller when called by the Pull consumer- so it is not relevant data.

**Comment by dstokesf5** [comment]
This has been added to our internal product backlog as AUTOTOOL-2902.
