### ISSUE TITLE
Data of type F5Telemetry_ASM was dropped: The number of custom fields 501 is above the limit of 500 fields per data type.

### ISSUE THREAD

**Issue by ilhamsetiapambudi** [F5Networks/f5-telemetry-streaming#181]
### Environment
 * Telemetry Streaming Version:
 * BIG-IP Version: 15.1.2.1
 * TS Version: 1.20.1
 * AS3 Version: 3.29.0

### Summary
1. We will be telemetry streaming ASM (Application Security Manager) to Azure Log Analytic.
2. When performing Telemetry Streaming ASM all logs can be received in Azure Log Analytics.
3. When adding configuration for Telemetry Streaming ASM, Azure Log analytics has an error **Data of type F5Telemetry_ASM was dropped: The number of custom fields 501 is above the limit of 500 fields per data type.** So for now azure log analytic does not received ASM logs.
4. Error **Data of type F5Telemetry_ASM was dropped: The number of custom fields 501 is above the limit of 500 fields per data type** still appears

### Steps To Reproduce
Declaration JSON using POSTMAN. Steps to reproduce the behavior:
1. Submit the following declaration:
```json
{
    "class": "Telemetry",
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514
    },
    "Poller": {
        "class": "Telemetry_System_Poller",
        "interval": 60,
        "enable": true,
        "trace": false,
        "allowSelfSignedCert": false,
        "host": "localhost",
        "port": 8100,
        "protocol": "http",
        "actions": [
            {
                "enable": true,
                "includeData": {},
                "locations": {
                    "system": true,
		    "ASM_CL":true,
                    "event_CL":true,
                    "system_CL":true,
                    "virtualServers": true
                }
            },
            {
                "includeData": {},
                "locations": {
                    "virtualServers": {
                        ".*": {
                            "vsInfo": true,
                            "name": true,
                            "clientside.bitsIn": true,
                            "clientside.bitsOut": true,
                            "clientside.maxConns": true,
                            "clientside.totConns": true
                        }
                    }
                }    
            }
        ]
    },
    "Pull_Consumer": {
        "class": "Telemetry_Pull_Consumer",
        "type": "default",
        "systemPoller": [
            "Poller"
        ]
    },
    "Azure_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Azure_Log_Analytics",
        "workspaceId": "***",
        "passphrase": {
            "cipherText": "****"
        }
    }
}

```

### Expected Behavior
All ASM logs will be logged in Azure Log Analytics and not exceed 500 fields limit.

### Actual Behavior
Error **Data of type F5Telemetry_ASM was dropped: The number of custom fields 501 is above the limit of 500 fields per data type** on ASM part

**Comment by dstokesf5** [comment]
Have you tried using the format property to resolve this issue? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#format-property
