### ISSUE TITLE
Unable to get metrics

### ISSUE THREAD

**Issue by for-mat** [F5Networks/f5-telemetry-streaming#182]
### Environment
 * Telemetry Streaming Version: f5-telemetry-1.19.0-3.noarch   and  f5-telemetry-1.15.0-4.noarch
 * BIG-IP Version: BIG-IP 13.1.3.6 Build 0.0.4 Point Release 6

### Summary
After running it for a while, I couldn't get metrics, not in either version.  But the other F5 devices are working fine.

{
    "code": 400,
    "message": "remoteSender:10.0.x.x, method:GET ",
    "referer": "10.0.x.x",
    "restOperationId": 7644013068,
    "errorStack": [
        "java.util.concurrent.TimeoutException: remoteSender:10.0.x.x, method:GET ",
        "at com.f5.rest.common.RestWorker.logAndFailExpiredOperation(RestWorker.java:3153)",
        "at com.f5.rest.common.RestWorker.checkForExpiredOperations(RestWorker.java:3142)",
        "at com.f5.rest.common.RestServer.checkAndExpirePendingWorkerOperations(RestServer.java:1457)",
        "at com.f5.rest.common.RestServer.access$400(RestServer.java:48)",
        "at com.f5.rest.common.RestServer$4.run(RestServer.java:1430)",
        "at com.f5.rest.common.ScheduleTaskManager$2$1.run(ScheduleTaskManager.java:123)",
        "at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)",
        "at java.util.concurrent.FutureTask.run(FutureTask.java:262)",
        "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)",
        "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)",
        "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)",
        "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)",
        "at java.lang.Thread.run(Thread.java:748)\n"
    ],
    "kind": ":resterrorresponse"
}

### Steps To Reproduce
After reinstallation, it will resume and run for a period of time

**Comment by dstokesf5** [comment]
It is possible that you are encountering problems with restjavad memory usage. Have you tried increasing the memory provisioned for restjavad? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/troubleshooting.html?highlight=restjavad#why-is-my-big-ip-experiencing-occasional-high-cpu-usage-and-slower-performance

**Comment by aheilmaier** [comment]
I have the same Problem (timeout exception), but increasing memory to restjavad is not an option in production env.

Telemetry Streaming Version: f5-telemetry-1.20.1
BIG-IP Version: BIG-IP 13.1.3.6

just waiting until we can upgrade to higher BIG-IP Version.
