### ISSUE TITLE
upload of declaration for Telemetry_System_Poller to BIG-IP failes with 502 error

### ISSUE THREAD

**Issue by aheilmaier** [F5Networks/f5-telemetry-streaming#185]
### Environment
 * Telemetry Streaming Version: 1.20.1
 * BIG-IP Version: 13.1.3.6

### Summary
Trying to upload a `Telemetry_System_Poller` `action` filter with `locations`.
But upload works until 5 `locations`.
Whenn adding the 6'th `location` upload failes with 502 bad gateway.

(not sure about the filter correctness, but filter works until 5'th location definition)
I need to filter because I hope to mitigate the timeout issue related to #182 and also want to reduce the amount of scraping due to high number of vserver and admin partitions on the system

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "Telemetry",
    "My_Poller": {
        "class": "Telemetry_System_Poller",
        "interval": 0,
		"actions": [
			{
				"includeData": {},
				"ifAnyMatch": [
					{
						"virtualServers": {
							"/adom_A/*": {}
						}
					},
					{
						"virtualServers": {
							"/adom_B/*": {}
						}
					}
				],
				"locations":
					{
						"virtualServers": {
							"/adom_.*": true
						},
						"pools": {
							"/adom_.*": true
						},
						"system": {},
						"ltmPolicies": {
							"/adom_.*": true
						},
						"httpProfiles": {
							"/adom_.*": true
						},
						"clientSslProfiles": {
							"/adom_.*": true
						},
						"serverSslProfiles": {
							"/adom_.*": true
						},
						"iRules": {
							"/adom_.*": true
						}
					}
			}
		]
    },
    "My_System": {
        "class": "Telemetry_System",
        "enable": "true",
        "systemPoller": "My_Poller"
    },
    "prometheus_pull_consumer": {
        "class": "Telemetry_Pull_Consumer",
        "type": "Prometheus",
        "systemPoller": "My_Poller"
    }
}
```

2. Observe the following error response:
```bash
.....
> POST /mgmt/shared/telemetry/declare HTTP/1.1

> Host: <BIGIP>

> Authorization: Basic <AUTH>

> User-Agent: curl/7.53.0

> Accept: */*

> Content-Type: application/json

> Content-Length: 1131

> Expect: 100-continue

{ [5 bytes data]

< HTTP/1.1 100 Continue

} [5 bytes data]

* We are completely uploaded and fine

{ [5 bytes data]

< HTTP/1.1 100 Continue

< Pragma: no-cache

< Cache-Control: no-store, no-cache, must-revalidate
....
< Server: com.f5.rest.common.RestRequestSender

100  1131    0     0  100  1131      0     17  0:01:06  0:01:03  0:00:03     0{ [5 bytes data]

< HTTP/1.1 502 Bad Gateway
...

```

### Expected Behavior
I expect `200 OK`
When it works until 5'th location I do not see `100 Continue`

### Actual Behavior
I do get an `502 Bad Gateway`

**Comment by dstokesf5** [comment]
Thank you for your feedback. I am unable to reproduce this issue. I believe the 502 status code is coming from the iContrtol REST system, and the request is likely not even reaching the Telemetry Streaming code. This issue may be caused by the restjavad process (part of the iControl REST system) not having enough memory. Does increasing the memory allocated to restjavad resolve your issue?

How to increase restjavad memory allocation: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/best-practices.html#workarounds
