### ISSUE TITLE
Add support for ELK 8.x

### ISSUE THREAD

**Issue by emmanuelcormier** [F5Networks/f5-telemetry-streaming#192]
### Is your feature request related to a problem? Please describe.
Support for ELK version 8.x.

### Describe the solution you'd like
Currently, TS (from 1.24) only supports ELK up to version 7.x.
[https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#elasticsearch-ref](url)

### Describe alternatives you've considered
None.

### Additional context
N/A

**Comment by dstokesf5** [comment]
Did you encounter any specific issues with ELK version 8.x?

**Comment by dstokesf5** [comment]
We have enabled v8.x in our testing and have not seen any problems so far.
