### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by adnanenglish** [F5Networks/f5-telemetry-streaming#193]
cat ../var/config/rest/iapps/f5-telemetry/version -->  1.25.0-2
  
 Our intention is to facilitate F5 telemetry streaming to Kafka servers. For that we have installed the RPM file on our BIG IP and have enabled the stream profile and http analytics profile to a Virtual server for testing. The REST API declaration is as follows:

{
  "class": "Telemetry",
  "My_System": {
    "class": "Telemetry_System",
    "systemPoller": {
      "interval": 60
    }
  },
  "My_Listener": {
    "class": "Telemetry_Listener",
    "port": 6514
  },
  "My_Consumer": {
    "class": "Telemetry_Consumer",
    "type": "Kafka",
    "host": "test.com",
    "protocol": "binaryTcpTls",
    "allowSelfSignedCert": true,
    "port": 6667,
    "topic": "JSON_F5_Telemetry"
  },
  "controls": {
         "class": "Controls",
         "logLevel": "info"
     }
}

We tried to manipulate multiple parameters in the declaration but nothing seems to help get info onto Kafka. Firewall rules are allowed and we are able to see traffic allowed to the host in the declaration. If we could get some assistance on where we are doing it wrong it will help us to achieve what is desired.

**Comment by dstokesf5** [comment]
Do you see any error output in `/var/log/restnoded/restnoded.log`?

**Comment by adnanenglish** [comment]
Wed, 16 Feb 2022 15:04:20 GMT - severe: [telemetry.Kafka.f5telemetry_default::My_Consumer] error: TopicAuthorizationFailed
Wed, 16 Feb 2022 15:05:42 GMT - warning: [telemetry.f5telemetry_default::My_System::SystemPoller_1.timer] SlidingTimer: configured interval of 60s., but took 90.859s.
Wed, 16 Feb 2022 15:05:42 GMT - info: [telemetry] Total Memory Provisioned (node process): 1433 MB. Memory Threshold: 1290 MB (90%)
Wed, 16 Feb 2022 15:05:42 GMT - info: [telemetry] Monitor checks updated. Interval: 15s | Memory Threshold: 1290 MB

**Comment by dstokesf5** [comment]
It looks like further authentication is needed. Have you tied setting the authentication settings (authenticationProtocol, username, password, privateKey, clientCertificate, rootCertificate) to match your Kafka configuration?

**Comment by adnanenglish** [comment]
Thank you.. I will work on that.
