### ISSUE TITLE
Random system events ingesting into Splunk via TS

### ISSUE THREAD

**Issue by milanp-crest** [F5Networks/f5-telemetry-streaming#196]
### Environment
 * Telemetry Streaming Version: 1.23.0
 * BIG-IP Version: 16.1.0

### Summary
We noticed that below events are generated very frequently when we are collecting the iControl events via TS using the following TS json configuration into Splunk. These events are not providing much value to SIEM perspective, but it will keep getting ingested into the Splunk and will lead to higher index costing to the user. Can we please make sure that these events won't get generated.

### Steps To Reproduce
Steps to reproduce the behaviour:
1. Submit the following declaration:
```json
{
   "class":"Telemetry_Namespace",
   "Endpoints_Profiles":{
      "class":"Telemetry_Endpoints",
      "enable":"true",
      "items":{
         "apiCallName":{
            "name":"sysID",
            "path":"mgmt/shared/identified-devices/config/device-info"
         },
         "system":{
            "path":"/mgmt/tm/sys/global-settings?$select=hostname"
         }
      }
   },
   "Custom_System":{
      "class":"Telemetry_System",
      "systemPoller":[
         "Custom_System_Poller1"
      ]
   },
   "Custom_System_Poller1":{
      "class":"Telemetry_System_Poller",
      "interval":"300",
      "endpointList":"Endpoints_Profiles"
   },
   "My_Consumer":{
      "class":"Telemetry_Consumer",
      "type":"Splunk",
      "host":"<Splunk host>",
      "protocol":"http",
      "port":"8088",
      "passphrase":{
         "cipherText":"<Splunk hec token>"
      }
   }
}
```

2. Observe the following error response:
```json
200 success
```

### Expected Behaviour
We are able to collect the proper events for iControl. But along with it following events are also coming. which should not be coming from TS. 

Events to stop from TS:
{"telemetryServiceInfo":{"pollingInterval":300,"cycleStart":"2022-02-18T08:59:38.388Z","cycleEnd":"2022-02-18T08:59:39.300Z"},"telemetryEventCategory":"systemInfo"}

### Actual Behaviour
Along with the iControl events following event is also getting ingested continuously.
{"telemetryServiceInfo":{"pollingInterval":300,"cycleStart":"2022-02-18T08:59:38.388Z","cycleEnd":"2022-02-18T08:59:39.300Z"},"telemetryEventCategory":"systemInfo"}

**Comment by dstokesf5** [comment]
Are you seeing two types of events? One containing the custom endpoint data and one that is essentially empty?
