### ISSUE TITLE
BIGIP Prometheus reports wrong metric type (gauge/counter)

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/f5-telemetry-streaming#199]
### Environment
 * Telemetry Streaming Version: 1.26
 * BIG-IP Version: 16.1

### Summary
All BIGIP metrics in Prometheus are reported as gauge even though some of them are counters 

![image](https://user-images.githubusercontent.com/11005568/159910394-bc7ca450-7b39-43ad-ad47-8f371cb63ab1.png)

### Expected Behavior
Correct the type of metrics

**Comment by dstokesf5** [comment]
Unfortunately the iControl REST API that Telemetry Streaming uses to gather this data does not provide information about the data type. Furthermore, we do not have the resources to create and maintain the data needed to enhance iControl REST output with this information.
