### ISSUE TITLE
BIG-IQ (CM/LM) device monitoring

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-telemetry-streaming#200]
### Is your feature request related to a problem? Please describe.

Today, BIG-IQ does not have the capability to install TS rpm and be monitored just like BIG-IP. 

It's acknowledged that BIQ sits in control plane but still an element that needs to be monitor nonetheless as LM is critical in the licensing workflow. Note also that SNMP is being deprecated in the environment in favor of tools like prometheus, which can be configured to scrape static endpoints.

### Describe the solution you'd like

Provide the ability to install TS on BIG-IQ (CM/LM) at least providing basic stats monitoring to be able to determine status of BIG-IQ itself.

### Describe alternatives you've considered

SNMP, but it is deprecated in the environment that will be used in. 

Node-exporter, but it's not possible to install unofficial packages on F5 devices.
https://prometheus.io/docs/guides/node-exporter/
https://github.com/ExpressenAB/bigip_exporter

### Additional context
C3771114 raised to confirm current status and alternatives.

**Comment by dstokesf5** [comment]
Thank you for your feedback. Unfortunately, we do not have the resources to address this feature request.
