### ISSUE TITLE
Azure table F5Telemetry_* dropped for 500+ fields.

### ISSUE THREAD

**Issue by dylanthomaswtit** [F5Networks/f5-telemetry-streaming#202]
### Environment
 * Telemetry Streaming Version: 1.25
 * BIG-IP Version: 15.1.5

### Summary
We deployed TS to send to Azure Log Analytics Workspace. We set the format to propertyBased in our JSON declaration as suggested in the support article K42151385, however we are receiving an error that we are still exceeding the custom field count of 500. In working with our F5 contact, we were asked to create a bug report to track this issue.

### Steps To Reproduce
I am providing our TS declaration and some of the relevant configuration below. The logs we are seeing in Azure are: "Data of type F5Telemetry_* was dropped: The number of customer fields 501 is above the limit of 500 fields per data type"

1. Submit the following declaration:
```json
{
  "class": "Telemetry",
  "controls": {
    "class": "Controls",
    "logLevel": "debug",
    "debug": true
  },
  "My_System": {
    "class": "Telemetry_System",
    "systemPoller": {
      "interval": 60
    }
  },
  "My_Listener": {
    "class": "Telemetry_Listener",
    "port": 6514
  },
  "My_Consumer": {
    "class": "Telemetry_Consumer",
    "type": "Azure_Log_Analytics",
    "workspaceId": "<PRUNED>",
    "passphrase": {
      "cipherText": "<PRUNED>"
    },
    "format": "propertyBased"
  }
}
```
Security Log Profiles:
```tcl
security log profile telemetry_afm_security_log_profile {
    network {
        telemetry {
            filter {
                log-acl-match-accept enabled
                log-acl-match-drop enabled
                log-acl-match-reject enabled
                log-ip-errors enabled
                log-tcp-errors enabled
                log-tcp-events enabled
            }
            publisher telemetry_afm_publisher
        }
    }
}
security log profile telemetry_asm_security_log_profile {
    application {
        telemetry {
            filter {
                request-type {
                    values { all }
                }
            }
            local-storage disabled
            logger-type remote
            remote-storage splunk
            servers {
                255.255.255.254:syslog-tls { }
            }
        }
    }
    bot-defense {
        telemetry_asm_security_log_profile {
            filter {
                log-alarm enabled
                log-block enabled
                log-rate-limit enabled
            }
            local-publisher local-db-publisher
            remote-publisher telemetry_publisher
        }
    }
    dos-application {
        telemetry_asm_security_log_profile {
            local-publisher local-db-publisher
            remote-publisher telemetry_publisher
        }
    }
}
ltm profile request-log telemetry_traffic_log_profile {
    app-service none
    request-log-pool telemetry
    request-log-protocol mds-tcp
    request-log-template event_source=\"request_logging\",hostname=\"$BIGIP_HOSTNAME\",client_ip=\"$CLIENT_IP\",server_ip=\"$SERVER_IP\",http_method=\"$HTTP_METHOD\",http_uri=\"$HTTP_URI\",virtual_name=\"$VIRTUAL_NAME\",event_timestamp=\"$DATE_HTTP\"
    request-logging enabled
    response-log-pool telemetry
    response-log-protocol mds-tcp
    response-log-template event_source=\"response_logging\",hostname=\"$BIGIP_HOSTNAME\",client_ip=\"$CLIENT_IP\",server_ip=\"$SERVER_IP\",http_method=\"$HTTP_METHOD\",http_uri=\"$HTTP_URI\",virtual_name=\"$VIRTUAL_NAME\",event_timestamp=\"$DATE_HTTP\",http_statcode=\"$HTTP_STATCODE\",http_status=\"$HTTP_STATUS\",response_ms=\"$RESPONSE_MSECS\"
    response-logging enabled
}
```

2. Observe the following error response:
Azure LA Workspace:
Data of type F5Telemetry_* was dropped: The number of customer fields 501 is above the limit of 500 fields per data type

### Expected Behavior
In referencing support article K42151385, it appears we have the suggested fix applied to have our logs successfully received in Azure.

### Actual Behavior
Configuring TS as suggested results in Azure log drops.

**Comment by dstokesf5** [comment]
Thank you for your feedback. Is the error message specifically saying `F5Telemetry_*`, or are you simplifying the error message. If you could provide a specific table name and a count of the number of relevant items on the BIG-IP, that may help us narrow down the issue.

**Comment by dylanthomaswtit** [comment]
![azure_errors](https://user-images.githubusercontent.com/102540100/161095694-a5b0fc2e-e522-4c54-849f-763adf97557b.png)
This is the exact error message and I'm sharing the screenshot that we were provided.

**Comment by dstokesf5** [comment]
Thank you for posting that screenshot. That error is not what I was expecting to see, and is not something I have seen before. I am checking with the developers to see if they have a better idea of what is going on here.

**Comment by npmaslow** [comment]
Are there any additional ways to limit the number of fields? I am working with a customer where they are seeing this error (appended) even when using 1.28 with the format propertyBased option.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/32770395/169558341-95809993-9d54-4f55-8382-7f8610fca096.png)

**Comment by dstokesf5** [comment]
@npmaslow are you able to provide a trace file from the consumer? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/troubleshooting.html#tracing

That will give us a better idea of what Telemetry Streaming is send to Azure.

**Comment by peoplesmeat** [comment]
We are seeing the same issue.
![Screen Shot 2022-06-15 at 9 18 05 AM](https://user-images.githubusercontent.com/1972806/173836520-3d04c9e6-7550-474d-87fb-5979574ee730.png)

**Comment by dstokesf5** [comment]
It looks like we have solved this issue as generically as we can, and now we need to focus on individual tables. @peoplesmeat please open a new issue for the F5Telemetry_iRules table.

**Comment by dstokesf5** [comment]
@npmaslow we could still use those trace files to see what is going on here. If the trace files contain sensitive data, please open a support case to send us the data.
