### ISSUE TITLE
Google Cloud Monitoring Errors in Create TimeSeries API calls

### ISSUE THREAD

**Issue by CarlB-dev** [F5Networks/f5-telemetry-streaming#210]
### Environment
 * Telemetry Streaming Version: 1.29(also same results with 1.27.1 and 1.25)
 * BIG-IP Version:16.1.2.2

### Summary
Shortly after posting a TS declaration, the Restnoded logs show a 400 error message and you cannot find your metrics in the Google console --> metrics explorer.  Within the Google Console API explorer, you see that every call to google.monitoring.v3.MetricService.CreateTimeSeries is failing and the status code is a 400.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
  "class": "Telemetry",
  "controls": {
    "class": "Controls",
    "logLevel": "info",
    "debug": false
},
  "My_System": {
      "class": "Telemetry_System",
      "systemPoller": {
          "interval": 60
      }
  },
  "My_Listener": {
      "class": "Telemetry_Listener",
      "trace": false,
      "port": 6514
  },
  "My_Consumer": {
      "class": "Telemetry_Consumer",
      "type": "Google_Cloud_Monitoring",
      "trace": false,
      "projectId": "f5-gcs-4261-sales-agility2022",
      "serviceEmail": "student72-bigip@f5-gcs-4261-sales-agility2022.iam.gserviceaccount.com",
      "reportInstanceMetadata": true,
      "useServiceAccountToken": true 
  }
}
```

2. Observe the following error response:
From the RESTNODED.log file:
Mon, 13 Jun 2022 21:55:51 GMT - severe: [telemetry.Google_Cloud_Monitoring.f5telemetry_default::My_Consumer] error: Bad status code: 400 Bad Request for https://monitoring.googleapis.com/v3/projects/f5-gcs-4261-sales-agility2022/timeSeries
Mon, 13 Jun 2022 21:56:51 GMT - severe: [telemetry.Google_Cloud_Monitoring.f5telemetry_default::My_Consumer] error: Bad status code: 400 Bad Request for https://monitoring.googleapis.com/v3/projects/f5-gcs-4261-sales-agility2022/timeSeries

### Expected Behavior
In this example we are using the service account of the BIG-IP to authenticate against the Google environment and create any of the needed elements to display metrics that the BIG-IP publishes.  The BIG-IP service account has the following IAM Roles: Monitoring Editor and Monitoring Metric Writer

### Actual Behavior
TS declaration posts successfully however the data is never displayed in Google Monitoring Metrics Explorer due to the failure of the CreateTimeSeries API Calls.

@memes

![API_Errors_TS_1](https://user-images.githubusercontent.com/44070777/173453347-1be8e5ae-d2fc-4801-a135-8d0cedbbcaa9.png)
![API_Errors_TS_2](https://user-images.githubusercontent.com/44070777/173453369-64e52aed-0407-436a-8664-62a193b696c8.png)
![iamRolesBIGIP](https://user-images.githubusercontent.com/44070777/173457905-04c1e333-33bb-4388-ad7c-a89b159db550.png)

**Comment by dstokesf5** [comment]
@CarlB-dev Can you please provide some trace data to help us resolve your issue? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/troubleshooting.html#tracing

If the trace data contains sensitive information, please open a support case to send it to us.
