### ISSUE TITLE
Telemetry Fails on Azure Clouds Other Than AzurePublic and AzureUSGovernment

### ISSUE THREAD

**Issue by blheatwole** [F5Networks/f5-telemetry-streaming#213]
### Environment
 * Telemetry Streaming Version: 1.30
 * BIG-IP Version: BIG-IP 16.1.2.2 Build 0.0.28 Point Release 2

### Summary
The URLs to send telemetry to Azure are hard-coded and limited to AzurePublic and AzureUSGovernment. See https://github.com/F5Networks/f5-telemetry-streaming/blob/fd875070204d1b91bfd71fda7ff4dbd5a4a6b788/src/lib/consumers/shared/azureUtil.js#L60

### Steps To Reproduce
1. Install F5-telemetry in AzureGerman, AzureChina, AzureSecret or some other Azure cloud that is not AzurePublic or AzureUSGovernment.
2. Configure F5-telemetry to send to Log Analytics: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#microsoft-azure-log-analytics

### Expected Behavior
Logs are streamed to Log Analytics

### Actual Behavior
F5 Telemetry attempts to ship the logs to 'azure.com' which (if accessible) does not know about the Log Analytics workspace and the request fails.

**Comment by blheatwole** [comment]
Please add an optional configuration value where we can directly set the management and op insights URLs.

Note that in some clouds the actual URLs used cannot be publicly published, and so relying solely on hard-coded values can never support all clouds/regions.

**Comment by mdditt2000** [comment]
Created TS-697 for PM tracking

**Comment by blheatwole** [comment]
I'm cleaning up the docs and tests to submit a PR for this later today
