### ISSUE TITLE
Question: F5 Telemetry to only send specific partition.

### ISSUE THREAD

**Issue by jjt8572** [F5Networks/f5-telemetry-streaming#214]
Trying to narrow down stats to a specific partition.

After virtualServers           ".*": {   is telling you all partitions, if i wanted to do a specific partition what is the correct syntax for instance /Common/?

 We tried 
              "./Common/*": {             
              "./HSec_RD1_Dev-QA /*": {         
              "/HSec_RD1_Dev-QA /*": {    **without the period**
once we tried specific partitions we quit getting any status in Datadog.

 "virtualServers": {
              ".*": {
                "name": true,
                "pool": true,
                "availabilityState": true,
                "clientside.curConns": true,
                "clientside.pktsIn": true,
                "clientside.pktsOut": true
              }
            },
            "pools": {
              ".*": {
                "name": true,
                "members": {
                  ".*": {
                    "addr": true,
                    "monitorStatus": true,
                    "availabilityState": true,
                    "serverside.curConns": true,
                    "serverside.pktsIn": true,
                    "sevrverside.pktsOut": true
                  }

**Comment by dstokesf5** [comment]
Please resubmit your issue using one of the provided issue templates. This helps us better understand and track your issue.
