### ISSUE TITLE
Dial-In feature on F5 Telemetry

### ISSUE THREAD

**Issue by samourai5** [F5Networks/f5-telemetry-streaming#215]
### Is your feature request related to a problem? Please describe.
no, the request is not related to problem, but I ask you because the feature exist with other vendors like Cisco or Nokia ..

### Describe the solution you'd like
Hello, 
I ask you for "Dial-in Telemetry" feature, in order that Data collector initiate GRPC Connection to F5 device/VM.
The idea is to simplify a failure management on Collector, it means,  instead of changing the address of the collector on the F5, I prefer to let this be managed on the collector side

### Describe alternatives you've considered
The idea is to configure several Telemetry Collector on F5, without sending the Telemetry DATA, the F5 device will wait for connection from one of the collectors.

### Additional context
this is example for Nokia implementation : https://infocenter.nokia.com/public/7750SR222R1A/index.jsp?topic=%2Fcom.nokia.System_Mgmt_Guide%2Fdial-in_telemet-d1206e1276.html&cp=26_10_1_1_0_0

also, I attach a picture for Cisco Model.

![image](https://user-images.githubusercontent.com/111439930/185150732-50e6065a-b793-4dcb-bd49-1fbf83d630a8.png)

**Comment by dstokesf5** [comment]
A dial-in approach can be achieved using one of the available pull consumers: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/pull-consumers.html#pull-consumers

Does this work for your use case?
