### ISSUE TITLE
Data of type F5Telemetry_iRules was dropped because number of fields * is above the limit of 500 custom fields per data type

### ISSUE THREAD

**Issue by imashish87** [F5Networks/f5-telemetry-streaming#222]
Summary
We deployed TS to send to Azure Log Analytics Workspace. We set the format to propertyBased in our JSON declaration as suggested in the support article K42151385, however we are receiving an error that we are still exceeding the custom field count of 500. In working with our F5 contact, we were asked to create a bug report to track this issue.

-->

### Environment
 * Telemetry Streaming Version: f5-telemetry-1.30.0-1.noarch.rpm
 * BIG-IP Version: 15.1.5.1

Summary
We deployed TS to send to Azure Log Analytics Workspace. We set the format to propertyBased in our JSON declaration as suggested in the support article K42151385, however we are receiving an error that we are still exceeding the custom field count of 500. In working with our F5 contact, we were asked to create a bug report to track this issue.

### Steps To Reproduce
1. Submit the following declaration:
{
  "class": "Telemetry",
  "controls": {
    "class": "Controls",
    "logLevel": "debug",
    "debug": true
  },
  "My_System": {
    "class": "Telemetry_System",
    "systemPoller": {
      "interval": 60
    }
  },
  "My_Listener": {
    "class": "Telemetry_Listener",
    "port": 6514
  },
  "My_Consumer": {
    "class": "Telemetry_Consumer",
    "type": "Azure_Log_Analytics",
    "workspaceId": "<PRUNED>",
    "passphrase": {
      "cipherText": "<PRUNED>"
    },
    "format": "propertyBased"
  }
}

2. Observe the following error response:
```json
{
    "code": 500,
    "message": "Something went wrong",
    "restOperationId": 23018917,
    "kind": ":resterrorresponse"
}

**Comment by sunitharonan** [comment]
@imashish87 Please open a support ticket and upload a qkview in order for us to investigate more.
