### ISSUE TITLE
Multiple Telemetry_System_Poller declarations with different intervals sending "null" host to Splunk #C3873547

### ISSUE THREAD

**Issue by johnebgood** [F5Networks/f5-telemetry-streaming#224]
### Environment
 * Telemetry Streaming Version: 1.27.1
 * BIG-IP Version: BIG-IP v15.1.5 (Build 0.0.10)
 * Case#: C3873547

### Summary
When configuring multiple Telemetry_System_Poller's only the system poller will contain the "host" field with the correct value. Other pollers send "host":"null" to Splunk. Aside from the Splunk host metadata the bigip data and polling intervals are correct, only the "host" key is incorrectly set to "null".

Please also include information about the reproducibility and the severity/impact of the issue:
I have been able to reproduce this in multiple BIG-IP and Splunk environments. I used http on the Splunk HTTP Event Collector to observe the raw data going out the door from the BIG-IP. This is 100% validated and revalidated with tcpdump on the BIG-IP side when setting and sending the JSON structure to Splunk. This is _not_ happening on the Splunk side.

### Steps To Reproduce
1. Submit the following declaration:
```
{
	"class": "Telemetry",
	"My_System": {
		"class": "Telemetry_System",
		"enable": "true",
		"systemPoller": [
			"My_PollerSystem",
			"My_PollerVS",
			"My_PollerCert"
		],
		"allowSelfSignedCert": true
	},
	"My_PollerSystem": {
		"class": "Telemetry_System_Poller",
		"interval": 60,
		"actions": [
			{
				"includeData": {},
				"locations": {
					"system": true
				}
			}
		],
		"allowSelfSignedCert": true
	},
	"My_PollerVS": {
		"class": "Telemetry_System_Poller",
		"interval": 90,
		"actions": [
			{
				"includeData": {},
				"locations": {
					"virtualServers": true,
					"pools": true
				}
			}
		],
		"allowSelfSignedCert": true
	},
	"My_PollerCert": {
		"class": "Telemetry_System_Poller",
		"interval": 120,
		"actions": [
			{
				"includeData": {},
				"locations": {
					"sslCerts": true
				}
			}
		],
		"allowSelfSignedCert": true
	},
	"Splunk_Consumer": {
		"class": "Telemetry_Consumer",
		"type": "Splunk",
		"host": "10.1.10.136",
		"protocol": "https",
		"port": 8088,
		"passphrase": {
			"cipherText": "YOUR_API_KEY"
		},
		"allowSelfSignedCert": true
	}
}
```

2. I disabled https on the Splunk HEC input and saw this is the data going out the door on the BIG-IP for non-system telemetry.
```
POST /services/collector/event HTTP/1.1
Authorization: Splunk 3e4dXXXXXXXXXXXXXXXXXXXX59
Content-Length: 1868
User-Agent: f5-telemetry/1.27.1
host: 10.1.10.136:8088
Connection: close

{"time":1663006442000,"host":"null","source":"f5.telemetry","sourcetype":"f5:telemetry:json","event":{"pools":{...

```

### Expected Behavior
The host key value should have the hostname instead of "null" for all telemetry messages as shown here with the "system" telemetry which is working, host is configured as "bigip1".
{"time":1663006502000,"host":"bigip1","source":"f5.telemetry","sourcetype":"f5:telemetry:json","event":{"system...

### Actual Behavior
{"time":1663006442000,"host":"**null**","source":"f5.telemetry","sourcetype":"f5:telemetry:json","event":{"pools":{...

Splunk and tcpdump screenshots attached.

![image](https://user-images.githubusercontent.com/663211/189732045-12f27e4c-9512-4fcb-b218-c97ac6589c2f.png)
![image](https://user-images.githubusercontent.com/663211/189732942-dc40a489-c4cf-40e3-bc27-0df03861ebce.png)
![image](https://user-images.githubusercontent.com/663211/189733117-f7299330-05ec-4eca-a764-213c81e737e5.png)

**Comment by johnebgood** [comment]
I think I found where this is presenting. If "globalCtx.event.data.hostname" isn't set "null" is set in the data being sent to Splunk. The Splunk host metadata field should always be the origin of the device sending the data regardless of what data is being sent.

[https://github.com/F5Networks/f5-telemetry-streaming/blob/master/src/lib/consumers/Splunk/dataMapping.js](https://github.com/F5Networks/f5-telemetry-streaming/blob/master/src/lib/consumers/Splunk/dataMapping.js)

```

function defaultFormat(globalCtx) {
    const data = globalCtx.event.data;

    // certain events may not have system object
    let time = Date.parse(new Date());
    let host = 'null';

    if (data.system) {
        if (data.system.systemTimestamp) {
            time = Date.parse(data.system.systemTimestamp);
        }
        if (data.system.hostname) {
            host = data.system.hostname;
        }
    } else if (data.hostname) {
        host = data.hostname;
    }

    return {
        time,
        host,
        source: 'f5.telemetry',
        sourcetype: 'f5:telemetry:json',
        event: data
    };
}
```

**Comment by mdditt2000** [comment]
Created Jira TS-703 and prioritizing in the next sprint. Will update if status changes.

**Comment by mdditt2000** [comment]
Resolved by adding the following action

They can try to **update actions for each system poller to include hostname:**

For example:

```
"actions": [
                       {
                               "includeData": {},
                               "locations": {
                                      "sslCerts": true,
                                        "system": {
                                            "hostname": true
                                        }
                               }
                       }
            ]
```

**Comment by mdditt2000** [comment]
closing issue
