### ISSUE TITLE
DOCS: Troubleshooting Page: Debug example is missing "Class"

### ISSUE THREAD

**Issue by f5-applebaum** [F5Networks/f5-telemetry-streaming#225]
### Summary

The debug example on the troubleshooting page is missing the "class" attribute.
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/troubleshooting.html#logging

### Steps To Reproduce
Currently says:
```json
{
     "class": "Telemetry",
     "Controls": {
         "logLevel": "debug"
     }
}
```

Should be:
```json
{
     "class": "Telemetry",
     "Controls": {
         "class": "Controls",
         "logLevel": "debug"
     }
}
```

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this issue to our internal product backlog as TS-708.
