### ISSUE TITLE
Post to a Azure consumer via an HTTP proxy

### ISSUE THREAD

**Issue by vkarla2** [F5Networks/f5-telemetry-streaming#227]
### Is your feature request related to a problem? Please describe.
Would like to post to a Azure consumer via an HTTP proxy, similar to what is available via DataDog or Splunk Poller.

### Describe the solution you'd like
A statement similar to the proxy parameter in Splunk poller as described in - https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/declarations.html#specifying-proxy-settings-for-splunk-consumers

### Describe alternatives you've considered
Tried to setup declaration with proxy similar to Splunk proxy declaration, but bypassing configured proxy servers.

...
"My_Consumer": {
    "class": "Telemetry_Consumer",
    "type": "Azure_Log_Analytics",
    "workspaceId": "WorkspaceID",
    "passphrase": "*********",
    "proxy": {
        "host": "10.10.10.10",
        "port": 8080,
        "protocol": "http"
    },
    "useManagedIdentity": false,
    "region": "North Europe"
}
...

**Comment by DahlPatric** [comment]
Also stuck and surprised actually that proxy not supported within type: "Azure_Log_Analytics",


"Sentinel": {
        "class": "Telemetry_Consumer",
        **"type": "Azure_Log_Analytics",**
        "format": "propertyBased",
        "workspaceId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "passphrase": {
            "cipherText": "xxxxxxxxxxxxxxxxxxxxxxxx"
            }
       },
       "proxy": {
                "host": "proxy.company.com",
                "port": 80,
                "protocol": "http"
            } 

"code": 422,
    "message": "java.net.ProtocolException: status:422, body:{\"code\":422,\"message\":\"Unprocessable entity\",\"error\":\"Error: [{\\\"keyword\\\":\\\"required\\\",\\\"dataPath\\\":\\\"/NamespaceSentinelForStats/proxy\\\",\\\"schemaPath\\\":\\\"#/allOf/0/then/required\\\",\\\"params\\\":{\\\"missingProperty\\\":\\\"class\\\"},\\\"message\\\":\\\"should have required property 'class'\\\"},{\\\"keyword\\\":\\\"if\\\",\\\"dataPath\\\":\\\"/NamespaceSentinelForStats\\\",\\\"schemaPath\\\":\\\"#/allOf/0/if\\\",\\\"params\\\":{\\\"failingKeyword\\\":\\\"then\\\"},\\\"message\\\":\\\"should match \\\\\\\"then\\\\\\\" schema\\\"}]\"}",
    "referer": "10.173.118.236",
    "restOperationId": 25351193,
    "kind": ":resterrorresponse"


Documentation is not really clear with types support proxy or not today, not for me at least.
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/schema-reference.html#telemetry-consumer

**Comment by G-gonzalezjimenez** [comment]
Hi, we will update the documentation with the message that Proxy is not supported. TS is on Maintenance mode  https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/

F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product.

Thank you
