### ISSUE TITLE
Adjust payload size from TS to kafka

### ISSUE THREAD

**Issue by amsinha2** [F5Networks/f5-telemetry-streaming#24]
##### ISSUE TYPE

 - Bug Report

##### Telemetry Streaming BUILD/ VERSION

```
1.6.0
```

##### BIGIP VERSION

```
13.1.0.2
```

##### SUMMARY

```
the amount of data sent to kafka is too large for kafka to handle.  is there a way to select what data is sent to the consumer to reduce the payload?
```

##### STEPS TO REPRODUCE

```
{
    "class": "Telemetry",
    "My_Poller": {
        "class": "Telemetry_System_Poller",
        "interval": 60,
        "enable": true,
        "trace": false,
        "allowSelfSignedCert": false,
        "host": "localhost",
        "port": 8100,
        "protocol": "http",
        "tag": {
            "tenant": "`T`",
            "application": "`A`"
        }
    },
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514,
        "enable": true,
        "trace": false,
        "tag": {
            "tenant": "`T`",
            "application": "`A`"
        },
        "match": ""
    },
    "My_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Kafka",
        "host": "<removed>",
        "protocol": "binaryTcpTls",
        "port": 9092,
        "topic": "<removed>"
    }
}
```

##### EXPECTED RESULTS

telemetry data in kafka topic
##### ACTUAL RESULTS

Invalid receive.  size is too large.  
is there is a way to reduce what TS is sending out?

```

```

**Comment by dstokesf5** [comment]
We are already looking into filtering data sent to consumers with internal product backlog item AT-487.

**Comment by dstokesf5** [comment]
Several features for controlling the data that Telemetry Streaming sends out have been added and are documented here: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/data-modification.html

Closing this issue. If you still have a problem, feel free to reopen this issue or create a new one.
