### ISSUE TITLE
Facing the issue with datadog consumer on big Ip

### ISSUE THREAD

**Issue by irparajababu** [F5Networks/f5-telemetry-streaming#242]
Facing the below issue while sending the metrics to datadog through datadog consumer on f5 network load balancer.
Wed, 11 Jan 2023 17:42:26 GMT - severe: [telemetry.DataDog.f5telemetry_default::My_Consumer] Error caught on attempt to send request to 'api.datadoghq.com/api/v2/series'
Traceback:
Error: HTTP error: Error: connect ECONNREFUSED 3.233.153.184:443
    at Request.request.(anonymous function) [as _callback] (/var/config/rest/iapps/f5-telemetry/lib/utils/requests.js:181:24)
    at self.callback (/var/config/rest/iapps/f5-telemetry/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/var/config/rest/iapps/f5-telemetry/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Wed, 11 Jan 2023 17:42:26 GMT - severe: [telemetry.DataDog.f5telemetry_default::My_Consumer] Unable to send 33165 bytes of data. Error: HTTP error: Error: connect ECONNREFUSED 3.233.153.184:443
Wed, 11 Jan 2023 17:42:26 GMT - severe: [telemetry.DataDog.f5telemetry_default::My_Consumer] Error caught on attempt to send request to 'http-intake.logs.datadoghq.com/api/v2/logs'
Traceback:

### Environment
 * Telemetry Streaming Version: 1.32.0
 * BIG-IP Version: BIG-IP 15.1.5.1 Build 0.0.14 Point Release 1

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "Telemetry",
    "controls": {
         "class": "Controls",
         "logLevel": "debug",
         "debug": true
     },
	"My_System": {
		"class": "Telemetry_System",
		"systemPoller": {
			"interval": 60,
			"actions": [{
				"includeData": {},
                "locations": {
                    "system": true
                }
            }]
		}
	},
	"My_Listener": {
		"class": "Telemetry_Listener",
        "trace": true,
		"port": 6514
	},
    "My_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "DataDog",
        "apiKey": "",
        "compressionType": "gzip",
        "service": "f5-telemetry"
    }
}
```

### Expected Behavior
It should be sent metrics to datadog with above telemetry streaming.

### Actual Behavior
Getting the above error connection refused the datadog URLs.
--i>

**Comment by G-gonzalezjimenez** [comment]
Hi, have you tried with v 1.33?

**Comment by G-gonzalezjimenez** [comment]
Hi, F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product. If you have a business case for this, please let me know and I will let you know how to contact us. Thank you
