### ISSUE TITLE
Telemetry Streaming interfere with SSL Orchestrator UI Loading

### ISSUE THREAD

**Issue by hparr** [F5Networks/f5-telemetry-streaming#244]
### Environment
 * Telemetry Streaming Version: 1.30, 1.31, 1.32
 * BIG-IP Version: 16.1.2 and 16.1.3.   
 * SSLO 9.1 and 9.3

### Summary
 When running SSL Orchestrator with a moderately large configuration users are not able to restart BIG-IP services or reboot BIG-IP once telemetry streaming is installed.   If you have SSL O configured and deployed and install TS everything works fine.  If you reboot or restart BIG-IP services (restnoded explicitly) as the SSL O UI will hang. 

### Steps To Reproduce
Install and configure SSL Orchestrator.
Install TS (the config can be empty)
Restart restnoded

BIG-IP UI for SSLO Will fail to load. 

TS Declaration

{
  "class": "Telemetry"
}

### Expected Behavior
Both rest services are useable. 

### Actual Behavior
SSL O fails to load Web UI.

Logs

Working

Fri, 03 Feb 2023 21:56:25 GMT - info: [SSLO] [SsloRestoreWorker]  Starting SSLO Restore process
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [SsloRestoreWorker]  All the blocks are present in both iFile & iApp
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - fine: [SSLO] [SsloRestoreWorker]  Both mcp data from self links/app service are present
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 393 closed
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 400 closed
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 392 closed
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 396 closed
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 391 closed
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 397 closed
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 439 opened
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 440 opened
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 441 opened
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 442 opened
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 443 opened
Fri, 03 Feb 2023 21:56:26 GMT - finest: socket 444 opened
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [RestConcurrencyController] reached concurrency limit. Running tasks: 10
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [interceptionRuleWorker] !!!!!!!![IRWorker] saving state
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [interceptionRuleWorker] !!!!!!!![IRWorker] saving state
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [interceptionRuleWorker] !!!!!!!![IRWorker] saving state
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [interceptionRuleWorker] !!!!!!!![IRWorker] saving state
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [interceptionRuleWorker] !!!!!!!![IRWorker] saving state
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [topologyReconcileDataWorker] saving state
Fri, 03 Feb 2023 21:56:26 GMT - fine: [SSLO] [InlineIpSubIndexWorker] Restore IP table successfully
Fri, 03 Feb 2023 21:56:26 GMT - info: [SSLO] [upgradeWorker] Starting Upgrade process
Fri, 03 Feb 2023 21:56:28 GMT - info: [SSLO] [UpgradeUtils] [upgradeUtils] Checking for config upgrade eligibility.
Fri, 03 Feb 2023 21:56:29 GMT - info: [WorkerStateManager] Storage worker reports no key for: /shared/iapp/f5-iappslx-ssl-orchestrator/persistBlock
Fri, 03 Feb 2023 21:56:29 GMT - info: [SSLO] [UpgradeUtils] upgradeEligibleObjects NO Upgrade required.
Fri, 03 Feb 2023 21:56:29 GMT - info: [SSLO] [upgradeWorker] Config in latest version, no upgrade performed.
Fri, 03 Feb 2023 21:56:31 GMT - finest: socket 441 closed
Fri, 03 Feb 2023 21:56:31 GMT - finest: socket 399 closed
Fri, 03 Feb 2023 21:56:31 GMT - finest: socket 440 closed
Fri, 03 Feb 2023 21:56:31 GMT - finest: socket 443 closed
Fri, 03 Feb 2023 21:56:31 GMT - finest: socket 442 closed
Fri, 03 Feb 2023 21:56:31 GMT - finest: socket 444 closed
Fri, 03 Feb 2023 21:56:31 GMT - finest: socket 439 closed
Fri, 03 Feb 2023 21:56:34 GMT - finest: socket 398 closed
Fri, 03 Feb 2023 21:56:51 GMT - info: [SSLO] [cmiSyncStatusWorker] Difference detected in sync-status, publishing to subscribers
                                                                                                    

Broken

See attached file.   The SIGTERM at the start is the restart of restnoded after the install of TS.  

[Broken-logs.pdf](https://github.com/F5Networks/f5-telemetry-streaming/files/10678719/Broken-logs.pdf)

By editing the interceptionRuleWorker.js  we can see that the worker is not getting post onGet

If you remove TS the SSL O web UI functions as expected.

**Comment by G-gonzalezjimenez** [comment]
Hi, have you tried V 1.33?

F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product. If you have a business case for this, please let me know and I will let you know how to contact us. Thank you

**Comment by grf5** [comment]
I'm experiencing the same issue with release 1.33. Downgrading to 1.32 fixes the issue. This is on 16.1.4 with SSLO 16.1.4-9.1.4. Restarting restjavad is not addressing the issue.
