### ISSUE TITLE
F5 streaming telemetery

### ISSUE THREAD

**Issue by elias-p** [F5Networks/f5-telemetry-streaming#245]
I am trying to connect the F5 on oracle cloud to azure Log analytics workspace , however the declaration page didn't have space for value to add the Log analytics URL or IP address. how to achieve that? the issue is related to ticket  PR # 216 github.com  enhancement request but looks like the pull request has not been implmented.

please let me know.  

Eli

**Comment by G-gonzalezjimenez** [comment]
Hi, F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product. If you have a business case for this, please let me know and I will let you know how to contact us. Thank you
