### ISSUE TITLE
F5 metrics streaming to aws cloudwatch from oracle

### ISSUE THREAD

**Issue by elias-p** [F5Networks/f5-telemetry-streaming#247]
Hello,
I am looking to stream F5 metrics on oracle OCI steaming and use the KAFKA declaration since the streaming kafka compatible.  however, didn't able to connect. is there anyone able to do that?

**Comment by G-gonzalezjimenez** [comment]
Hi, F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product. If you have a business case for this, please let me know and I will let you know how to contact us. Thank you
