### ISSUE TITLE
Data available in iControl REST is missing from Telemetry Streaming.

### ISSUE THREAD

**Issue by cbarlock** [F5Networks/f5-telemetry-streaming#249]
### Is your feature request related to a problem? Please describe.
I'm migrating an application that is using iControl REST API calls to Telemetry Streaming.   Not all the data that we are gathering via iControl is available from TS.  So far, I've identified these bits of data that we collect from iControl that I can't find in TS:

- From /mgmt/tm/cm/device, we collect the edition attribute
- From /mgmt/tm/net/self, we collect the name, floating, address and vlan attributes
- From /mgmt/tm/ltm/virtual, we collect the sourceAddressTranslation.type attribute

### Describe the solution you'd like
I'd like to see these attributes available from TS.  (My guess is that there is a lot of information available in iControl that is not in TS, but that is only a guess.  If I'm right, is there a plan to get all the missing bits in TS?)

### Describe alternatives you've considered
I have to make iControl REST API calls to collect the bits I can't get from TS.

**Comment by G-gonzalezjimenez** [comment]
F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product. If you have a business case for this, please let me know and I will let you know how to contact us. Thank you
