### ISSUE TITLE
Opentelemetry: add prefix to metrics 

### ISSUE THREAD

**Issue by jjepwu** [F5Networks/f5-telemetry-streaming#252]
### Is your feature request related to a problem? Please describe.
Opentelemetry metrics are sent without any prefix

### Describe the solution you'd like
We would like be able to see and quickly view data that is emitting from F5 devices. "namespace" should be sufficient if it is already used in other consumers. 

Example: namespace = "f5"
Metric should read as follows: f5_httpProfiles_2xxResp or f5:httpProfiles_2xxResp

**Comment by G-gonzalezjimenez** [comment]
F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product. If you have a business case for this, please let me know and I will let you know how to contact us. Thank you
