### ISSUE TITLE
Context Propagation support for OpenTelemetry

### ISSUE THREAD

**Issue by gjelenc** [F5Networks/f5-telemetry-streaming#253]
Add support for context propagation [Trace Context](https://w3c.github.io/trace-context/) for [OpenTelemetry](https://opentelemetry.io/docs/concepts/signals/traces/#context-propagation)

**Comment by G-gonzalezjimenez** [comment]
F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product. If you have a business case for this, please let me know and I will let you know how to contact us.  Thank you
