### ISSUE TITLE
RFE: Retrieve full interface statistics (remove filters for drops, errors and pkts in/out)

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-telemetry-streaming#264]
### Is your feature request related to a problem? Please describe.
I'm trying to use Telemetry Streaming to view all interface statistics and have found that some critical fields are filtered out. 

### Describe the solution you'd like
I would like line 289 of /var/config/rest/iapps/f5-telemetry/lib/properties.json modified to remove the following values:

**"counters.errorsAll", "counters.dropsAll", "counters.pktsIn", "counters.pktsOut"**

Configuration in 1.33:

```json
        "networkInterfaces": {
            "structure": { "parentKey": "system" },
            "key": "networkInterfaces",
            "normalization": [
                {
                    "filterKeys": { "exclude": [ "counters.errorsAll", "counters.dropsAll", "counters.pktsIn", "counters.pktsOut", "mediaActive", "tmName" ] }
                },
                {
                    "renameKeys": { "patterns": { "net/interface": { "pattern": "([0-9]+\\.[0-9]+|(?!\/)mgmt(?=\/))" } } }
                }
            ]
        }
```

### Describe alternatives you've considered
No clear documentation of the includeData field shows how to use the field to include missing data, but I suspect the data is filtered out before it can be considered. 

https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/data-modification.html

**Comment by petrov-serg** [comment]
Did you tried custom endpoints? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/custom-endpoints.html

**Comment by cwise24** [comment]
Custom endpoints can reveal the data, however formatting shown is not wanted by customer. But the excluded data (dropsAll, errorsAll) is odd data to exclude for network troubleshooting. There should be a way to include those values in default reporting.

**Comment by cwise24** [comment]
We have manually edited properties.json file to see requested formatting, but advised this is not a good fix.
`"networkInterfaces": {
            "structure": { "parentKey": "system" },
            "key": "networkInterfaces",
            "normalization": [
                {
                    "filterKeys": { "exclude": [ ] }
                },
                {
                    "renameKeys": { "patterns": { "net/interface": { "pattern": "([0-9]+\\.[0-9]+|(?!\/)mgmt(?=\/))" } } }`

**Comment by PrestonTaylor** [comment]
For clarification when using a Prometheus pull consumer the Custom endpoint returns data with no tags. So rather than `f5_counters_bitsIn{networkInterfaces="0.1"} 111 ` it appears as `f5_int_info_0_1_stats_counters_bitsIn 111` which makes it difficult to query in prometheus and each interface metrics appears as a unique metric rather than the same metric with different labels. This isn't mission critical by any means but is a break from standards.


Additionally I'm confused what the need would be to filter metrics under the telemetry library properties as shown above when that filtering can be defined in the "Telemetry_System_Poller" class that is supported for customers to manage.

**Comment by G-gonzalezjimenez** [comment]
Hi, Thank you for your comments and requests. TS has been moved to maintenance mode as stated here:
https://github.com/F5Networks/f5-telemetry-streaming
and here
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/

Unfortunately, we won't be doing this enhancement, we are focused on providing bug fixes and security updates on TS.

Thank you
