### ISSUE TITLE
The sys db variables for increasing memory to restjavad have changed

### ISSUE THREAD

**Issue by jayf5** [F5Networks/f5-telemetry-streaming#268]
### Environment
 * Telemetry Streaming Version:  1.33.0
 * BIG-IP Version: 17.1.1

### Summary

In the latest versions of TMOS, the db variables used to adjust memory for restjavad have changed, and as a result it is no longer possible to increase memory to the telemetry streaming app.

Docs on the change:  https://my.f5.com/manage/s/article/K000133258

### Steps To Reproduce

Using the docs here:  https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/troubleshooting.html#restjavad  try and increase the memory.  Notice that it does not work.

### Expected Behavior
Users should be able to increase memory

### Actual Behavior
The memory does not increase.

https://github.com/F5Networks/f5-telemetry-streaming/blob/master/src/lib/utils/device.js#L853

device.js is using a deprecated sys db variable "restjavad.useextramb" do detect when it is safe to increase memory and this db var has ben removed from the latest versions of TMOS.

So please update the code to fix this, and also adjust the documentation to reference the current db variables.

**Comment by jayf5** [comment]
Just wanted to make a note - the method for giving restjavad more memory has changed several different times and it was ultimately deemed implausible to try and **calculate** the amount of memory to give restjavad.  So instead we created provision.restjavad.extramb and let customers specify how much they want to give it with some basic checks to make sure it's not too low or too high (check out /service/restjavad/run on a 17.1.1 BIGIP for details). 

Assuming that telemetry-streaming doesn't **dependI** on restjavad having more memory, I would recommend a similar approach here - try and make it user configurable within limits.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: NEXTACC-370.

**Comment by LeonardosGitHub** [comment]
+1

**Comment by pgouband** [comment]
Hi,

It's fixed in version 1.35
