### ISSUE TITLE
Prometheus Pull: Authenticate with Client Cert (without username and password) to the BigIP API /PullConsumer/

### ISSUE THREAD

**Issue by Nachtfalkeaw** [F5Networks/f5-telemetry-streaming#273]
### Is your feature request related to a problem? Please describe.
Using a username and password and put this into a configuration file in cleartext in prometheus is not the best idea.
It would be good if it is possible that Prometheus could use a client certificate to authenticate at the "Telemetry_Pull_Consumer" Endpoint of the Big-IP to collect the metrics.

### Describe the solution you'd like
Authentication using a client certificate (without username and password)

**Comment by G-gonzalezjimenez** [comment]
Hi, thank you for your comments and suggestions. Telemetry Streaming was moved to maintenance mode last year.  

F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product.

https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/

We are not taking any requests for enhancements or new features.

Thank you
