### ISSUE TITLE
ASM telemetry is not streamed. LTM & APM no problem.

### ISSUE THREAD

**Issue by leamese** [F5Networks/f5-telemetry-streaming#279]
### Environment
 * Telemetry Streaming Version: 1.35.0
 * BIG-IP Version: 16.1.4.2

### Summary
I am sending telemetry data for LTM, APM and ASM to elastic via the elastic integration and the Generic_HTTP method.
LTM & APM logs are sucessfully received & displayed.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "Telemetry",
		"My_System": {
        "class": "Telemetry_System",
        "systemPoller": {
            "interval": 60
        },
        "enable": true,
        "host": "localhost",
        "port": 8100,
        "protocol": "http",
        "allowSelfSignedCert": true
	},
	"My_Listener": {
        "class": "Telemetry_Listener",
            "port": 6514,
            "enable": true,
            "trace": false,
            "match": "",
            "actions": [
                {
                    "setTag": {
                        "tenant": "`T`",
                        "application": "`A`"
                    },
                    "enable": true
                }
            ]
        },
	"My_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Generic_HTTP",
        "host": "10.34.15.249",
        "protocol": "https",
        "port": 9570,
        "path": "/",
        "method": "POST",
        "headers": [
            {
                "name": "content-type",
                "value": "application/json"
            }
        ],
        "outputMode": "processed",
        "compressionType": "gzip",
        "customOpts": [
            { "name": "keepAlive", "value": true },
            { "name": "keepAliveMsecs", "value": 30000 },
            { "name": "maxSockets", "value": 30 },
            { "name": "maxFreeSockets", "value": 30 }
        ],
        "enable": true,
        "trace": false,
        "allowSelfSignedCert": true
    }
}
```

Configuration: 
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/event-listener.html?highlight=event#asm
create security log profile profile_logging_asm_telemetry  application replace-all-with { telemetry { filter replace-all-with { request-type { values replace-all-with { all } } } logger-type remote remote-storage splunk servers replace-all-with { 255.255.255.254:6514 {} } } } 

2. Observe the following error response:

no error

### Expected Behavior
ASM telemetry logs are send out the system with regarding the configuration.

### Actual Behavior
I took a packet capture and see the LTM telemetry logs flowing out. But no ASM logs, so they are not leaving the system.

Are there specific locations i can look to troubleshoot? I have tried traces and debugging. The traces cycle a lot so it is hard to see if ASM telemetry is processed.

**Comment by pgouband** [comment]
Hi @leamese,

The troubleshooting documentation is here:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/troubleshooting.html

Also you can open a support case via https://my.f5.com/manage/s/

**Comment by leamese** [comment]
vs_telemetry_local had to be a standard VS. Performance L4 does not work for ASM.
