### ISSUE TITLE
Documentation request - character encodings and illegal characters

### ISSUE THREAD

**Issue by ryn9** [F5Networks/f5-telemetry-streaming#28]
##### ISSUE TYPE
 - Documentation Report

##### Telemetry Streaming BUILD/ VERSION
N/A

##### BIGIP VERSION
N/A

##### SUMMARY
F5 logs may be produced with various character encodings or bytestreams that include illegal characters for a specified encoding. Many of the consumers provided are expecting to be provided clean UTF-8 encoded output. I do not believe the documentation describes what character encoding f5-telemetry-streaming deals with, how it may be configured, and what it does when an illegally encoded character is received.

To note - varying character encodings and illegal characters in the bytestreams are very common in ASM logs.

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have created internal product backlog item AUTOTOOL-938 to track your request.

**Comment by ryn9** [comment]
In the interim - can we get an engineer provided statement on this matter?

**Comment by dstokesf5** [comment]
Part of what we need to do for this task is to review what TS is actually doing in these cases. From my understanding, TS simply forwards the log data as it gets it without making any guarantees about encoding or illegal characters.

**Comment by ryn9** [comment]
Many thanks for your reply. 
Hope we can hear back on this soon.

**Comment by dstokesf5** [comment]
This was resolved in version 1.9.0. If you are still experiencing an issue, please create a new issue or reopen this one.
