### ISSUE TITLE
Add support for additional consumers (Redis)

### ISSUE THREAD

**Issue by jsevedge** [F5Networks/f5-telemetry-streaming#3]
Please provide options to output for additional consumers.

For example:
Kafka
Elastic Search / Logstash
Redis
Generic http/https

**Comment by jsevedge** [comment]
Issues created to track adding support for Redis and generic http, internal ID's respectively 87 and 88.

**Comment by jsevedge** [comment]
@ryn9 Generic HTTP is now supported: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/userguide/setting-up-consumer.html#generic-http

Leaving this open however for Redis consumer.

**Comment by focrensh** [comment]
Redis tracked under AT-480

**Comment by M0JFP** [comment]
**
export to BMC TrueSight would also be useful Please..

**Comment by dstokesf5** [comment]
Thank you for your feedback. At this time we are focusing Telemetry Streaming on OpenTelemetry use cases, and we are no longer accepting requests for additional consumers. The growing list of supported consumers has become a strain on our limited development resources. If you have a strong business case for a new consumer, I suggest reaching out to product management or F5 support.
