### ISSUE TITLE
Ability to use IAM Role for AWS CloudWatch (and S3)

### ISSUE THREAD

**Issue by LeonardosGitHub** [F5Networks/f5-telemetry-streaming#31]
### Is your feature request related to a problem? Please describe.
Currently when using TS and AWS CloudWatch it requires IAM User secrets to be able to send data to CloudWatch.  I'd like to be able to use the IAM Role assigned to the BIG-IP to send the data to CloudWatch.

### Describe the solution you'd like
The ability to use IAM Role, with appropriate CloudWatch permissions, assigned to the BIG-IP as the authentication/authorization to CloudWatch. 

### Describe alternatives you've considered
The internal "Cloud" team doesn't allow IAM User secrets in AWS, the requirement is to use Roles assigned to the EC2/BIG-IP instead of Users.

### Additional context
N/A

**Comment by dstokesf5** [comment]
Looking into the feasibility of this. Added into our internal product backlog as AUTOTOOL-1068.

**Comment by dstokesf5** [comment]
This was resolved in version 1.9.0. If you are still experiencing an issue, please create a new issue or reopen this one.
