### ISSUE TITLE
Support of IBM Qradar

### ISSUE THREAD

**Issue by lyesber** [F5Networks/f5-telemetry-streaming#33]
Hello,

Is there any plan to support in the future IBM Qradar?

Thanks for your answer and your great work.

Best Regards,

**Comment by dstokesf5** [comment]
Support for IBM Qradar is in the internal product backlog as AUTOTOOL-507. However it is not currently a high priority item.

**Comment by lyesber** [comment]
Thanks a lot for you feedback

**Comment by lyesber** [comment]
Hello,

I checked the latest release v1.14.0, still no IBM Qradar support.
Can you tell me when it's going to be added?

Thanks for your help,

**Comment by dstokesf5** [comment]
This issue is still in our backlog, but is not planned for any upcoming releases. If this feature is critical for your use case, I suggest opening an issue with F5 Support as suggested in the Readme: https://github.com/F5Networks/f5-telemetry-streaming#filing-issues-and-getting-help.

**Comment by ChrisNelsonF5** [comment]
RFE Case# C3431036 created

**Comment by dstokesf5** [comment]
Thank you for your feedback. At this time we are focusing Telemetry Streaming on OpenTelemetry use cases, and we are no longer accepting requests for additional consumers. The growing list of supported consumers has become a strain on our limited development resources. If you have a strong business case for a new consumer, I suggest reaching out to product management or F5 support.
