### ISSUE TITLE
Document how to remove a TS declaration

### ISSUE THREAD

**Issue by aknot242** [F5Networks/f5-telemetry-streaming#34]
### Environment
 * Telemetry Streaming Version: N/A
 * BIG-IP Version: N/A

### Summary
The documentation does not indicate how to remove a TS declaration. Since there is no **DELETE** verb support to accomplish this, special instruction is especially required. It has been reported that you need to POST a declaration with an empty _Telemetry_ class such as: 

```json
{
    "class": "Telemetry"
}
```

Can you please add this somewhere in the documentation?

**Comment by dstokesf5** [comment]
Thank you for reporting this. It is already being tracked in our internal product backlog as AUTOTOOL-1177.

**Comment by dstokesf5** [comment]
The documentation on how to do this has been updated: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/deleting-ts-config.html

Closing this issue.
