### ISSUE TITLE
Statsd Consumer failed to send syslog message

### ISSUE THREAD

**Issue by liaojianxiong** [F5Networks/f5-telemetry-streaming#37]
I have configured my log filter destination to port 6514, and then I configure two Consumer.  ElasticSearch Consumer goes well and ELK successfully received the log like this:

data.data:<182>Feb 24 19:57:37 l4.gf.com info logger[4929]: [ssl_req][24/Feb/2020:19:57:37 +0800] 10.1.1.1 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "/xui/update/configuration/alert/statusmenu/coloradvisory" 1929 data.hostname:l4.gf.com telemetryEventCategory:syslog _id:2Pw6d3ABV9NNJmo06vEP _type:f5.telemetry _index:ts3_index _score:0

But I found Statsd Consumer failed to send syslog with the debug message "[telemetry.Statsd] Event is not systemInfo, skipping". I don't know why Statsd Consumer filter what I want to send!!

I found Statsd Consumer is the only way to send message by UDP in the TS homepage. Is it any other solution if I want to send my syslog by UDP?

TS version:
```json
{
    "nodeVersion": "v8.11.1",
    "version": "1.9.0",
    "release": "1",
    "schemaCurrent": "0.9.0",
    "schemaMinimum": "1.9.0"
}
```

LTM version: BIG-IP 14.1.0 Build 0.0.116 Final

My conf: 
```json
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-telemetry-streaming/master/src/nodejs/schema/base_schema.json",
    "class": "Telemetry",
    "controls": {
         "class": "Controls",
         "logLevel": "info"
     },
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514
    },
    "My_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "ElasticSearch",
        "host": "10.1.10.151",
        "index": "ts3_index",
        "port": 9200,
        "protocol": "http",
        "dataType": "f5.telemetry"
    },
    "My_Second_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Statsd",
        "host": "10.1.10.152",
        "protocol":"udp",
        "port":6666
    }
}
```

**Comment by dstokesf5** [comment]
Statsd is meant to gather metrics, not logs. For that reason, the statsd consumer in Telemetry Streaming will only forward metrics with the statsd consumer. This is working as expected.

**Comment by liaojianxiong** [comment]
@dstokesf5 Thank you for your answer.  I found Statsd Consumer is the only way to send message by UDP in the TS homepage. Is there any other solution if I want to send my syslog by UDP with TS?

**Comment by dstokesf5** [comment]
I do not think that is currently support by Telemetry Streaming. I suggest creating a feature request for adding a generic UDP consumer. This consumer would likely be similar to the generic HTTP consumer that already exists: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#generic-http

**Comment by dstokesf5** [comment]
Thank you for opening the RFE ticket. Closing this one.
