### ISSUE TITLE
RFE: adding a generic UDP consumer

### ISSUE THREAD

**Issue by liaojianxiong** [F5Networks/f5-telemetry-streaming#38]
I found Statsd Consumer is the only way to send message by UDP in the TS homepage right now, but Statsd Consumer just only receive metrics and filter other logs.  We need a generic UDP consumer in my Account. 
Pls. find https://github.com/F5Networks/f5-telemetry-streaming/issues/37

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal product backlog as AUTOTOOL-1348.

**Comment by dstokesf5** [comment]
Thank you for your feedback. At this time we are focusing Telemetry Streaming on OpenTelemetry use cases, and we are no longer accepting requests for additional consumers. The growing list of supported consumers has become a strain on our limited development resources. If you have a strong business case for a new consumer, I suggest reaching out to product management or F5 support.
