### ISSUE TITLE
Issues in forwarding ASM logs to Splunk

### ISSUE THREAD

**Issue by anithamareedu** [F5Networks/f5-telemetry-streaming#40]
### Environment
 * Telemetry Streaming Version: 1.8
 * BIG-IP Version:15.0.1

### Summary
Please also include information about the reproducibility and the severity/impact of the issue.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
   "class": "Telemetry",
   "controls": {
     "class": "Controls",
     "logLevel": "debug"
   },
   "My_Poller": {
     "class": "Telemetry_System_Poller",
     "interval": 60,
     "enable": "false"
   },
   "My_Listener": {
     "class": "Telemetry_Listener",
     "port": 6514
   },
    "My_Consumer1": {
        "class": "Telemetry_Consumer",
        "allowSelfSignedCert":true,
        "type": "Splunk",
        "host": "
        "protocol": "https",
        "port": 8088,
        "passphrase": {
            "cipherText": 
        } 
```

2. Observe the following error response:
```json
{
    "message": "success",
    "declaration": {
        "class": "Telemetry",
        "controls": {
            "class": "Controls",
            "logLevel": "debug",
            "debug": false
        },
```

### Expected Behavior
According to the TS declaration I am expecting the ASM logs to be sent to the Splunk via TS
### Actual Behavior
I dont see any ASM logs in the Splunk but when I generate the AFM, LTM , I am able to see them in the Splunk.

Your help would be greatly appreciated.

Please include any applicable error output.

**Comment by focrensh** [comment]
After reviewing and testing in lab using AS3 for configuration, ASM logs were received into splunk. Provided declarations and it is working for @anithamareedu as well.
