### ISSUE TITLE
Ability to use IAM Role with AWS S3

### ISSUE THREAD

**Issue by LeonardosGitHub** [F5Networks/f5-telemetry-streaming#41]
### Is your feature request related to a problem? Please describe.
Currently when using TS and AWS S3 it requires IAM User secrets to be able to send data to AWS S3. I'd like to be able to use the IAM Role assigned to the BIG-IP to send the data to S3.

### Describe the solution you'd like
The ability to use IAM Role, with appropriate AWS S3 permissions, assigned to the BIG-IP as the authentication/authorization to AWS S3.

### Describe alternatives you've considered
The internal "Cloud" team doesn't allow IAM User secrets in AWS, the requirement is to use Roles assigned to the EC2/BIG-IP instead of Users.

**Comment by dstokesf5** [comment]
Thank you for your feedback, this is being tracked in our internal product backlog as AUTOTOOL-1340.

**Comment by dstokesf5** [comment]
This issue has been resolved as part of the 1.12.0 release.
