### ISSUE TITLE
Support Elasticsearch 7

### ISSUE THREAD

**Issue by boeboe** [F5Networks/f5-telemetry-streaming#47]
**Scenario**

Using the latest Elastic Search 7.6.1, I was able to make TS ElasticSearch Consumer working. However, when I tried to manually create the index, with my own custom mappings for certain integer and ip fields, I bumped on issues that ElasticSearch starts to reject the data being send by TS.

**Issue**

There has been a breaking change introduced in the 7.x ES APIs with regards to mapping types

https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

This is what our TS ES Consumer creates if you let index and mapping creation done automatically.

	{
	  "mapping": {
		"f5.telemetry": {
		  "properties": {
			"data": {
			  "properties": {
				"application": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"client_ip": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"client_port": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"event_source": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"event_timestamp": {
				  "type": "date"
				},
				"hostname": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"http_method": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"http_status": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"http_uri": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"response_msecs": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"response_size": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"server_ip": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"server_port": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"tenant": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"virtual_ip": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"virtual_name": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				},
				"virtual_pool_name": {
				  "type": "text",
				  "fields": {
					"keyword": {
					  "type": "keyword",
					  "ignore_above": 256
					}
				  }
				}
			  }
			},
			"telemetryEventCategory": {
			  "type": "text",
			  "fields": {
				"keyword": {
				  "type": "keyword",
				  "ignore_above": 256
				}
			  }
			}
		  }
		}
	  }
	}

The _f5.telemetry_ key in here is what is causing the problem. One can not create such index/map definition anymore in the ES 7.x REST API. The reason why users need to be able to create their own mapping and indexes, is because the want integers and ips being indexed correctly in order to be able to create rich dashboards.

To be more precise, this is not possible in ES API 7.x

	{
	  "aliases":{
	  },
	  "mappings":{
		"f5.telemetry":{
		  "properties":{
			"data":{
			  "properties":{
				"application":{
				  "type":"text",
				  "fields":{
					"keyword":{
					  "type":"keyword",
					  "ignore_above":256
					}
				  }
				},
				"client_ip":{
				  "type":"ip"
				},
				"client_port":{
				  "type":"integer"
				},
				"event_source":{
				  "type":"text",
				  "fields":{
					"keyword":{
					  "type":"keyword",
					  "ignore_above":256
					}
				  }
				},
				"event_timestamp":{
				  "type":"date"
				},
				"hostname":{
				  "type":"text",
				  "fields":{
					"keyword":{
					  "type":"keyword",
					  "ignore_above":256
					}
				  }
				},
				"http_method":{
				  "type":"text",
				  "fields":{
					"keyword":{
					  "type":"keyword",
					  "ignore_above":256
					}
				  }
				},
				"http_status":{
				  "type":"integer"
				},
				"http_uri":{
				  "type":"text",
				  "fields":{
					"keyword":{
					  "type":"keyword",
					  "ignore_above":256
					}
				  }
				},
				"response_msecs":{
				  "type":"integer"
				},
				"response_size":{
				  "type":"integer"
				},
				"server_ip":{
				  "type":"ip"
				},
				"server_port":{
				  "type":"integer"
				},
				"tenant":{
				  "type":"text",
				  "fields":{
					"keyword":{
					  "type":"keyword",
					  "ignore_above":256
					}
				  }
				},
				"virtual_ip":{
				  "type":"ip"
				},
				"virtual_name":{
				  "type":"text",
				  "fields":{
					"keyword":{
					  "type":"keyword",
					  "ignore_above":256
					}
				  }
				},
				"virtual_pool_name":{
				  "type":"text",
				  "fields":{
					"keyword":{
					  "type":"keyword",
					  "ignore_above":256
					}
				  }
				}
			  }
			},
			"telemetryEventCategory":{
			  "type":"text",
			  "fields":{
				"keyword":{
				  "type":"keyword",
				  "ignore_above":256
				}
			  }
			}
		  }
		}
	  },
	  "settings":{
		"index":{
		  "number_of_shards":"1",
		  "number_of_replicas":"1",
		  "mapping": {
			"ignore_malformed": "true"
			}
		}
	  }
	}

Error traces that eventually led me to the explanation on why I did not receive any data in my own created index/mappings

	[2020-04-20T22:35:56,998][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [elk] failed to put mappings on indices [[[bigip/l26KWsyfSYW2HHgjGCmSXQ]]], type [f5.telemetry]
	java.lang.IllegalArgumentException: Rejecting mapping update to [bigip] as the final mapping would have more than 1 type: [_doc, f5.telemetry]
		at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:272) ~[elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:238) ~[elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) [elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.6.1.jar:7.6.1]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.6.1.jar:7.6.1]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

I have tried to play with the barely documented _"apiVersion": "7.6"_ field in a hope that this would send ES 7.x compatible data that would lead to compatible indices and mappings, but failed to find a solution this way. The API version fields seems to have no effect or it is unclear what versions are supported.

**Solutions**

Document our ES API compatibility. Also document the apiVersion field in more detail. Provide an example on the index/mapping creation customers can use in order to bootstrap ELK stack onboarding.

In the long run... provide support for ES 7.x without using the deprecated mapping types. 

**Note**

I can confirm that this strategy to create your own index works on ES 6.7.

**Comment by dstokesf5** [comment]
Thank you for reporting this, I am working on getting a note added to the documentation. I am going to re-purpose this ticket to track Elasticsearch 7 support.

**Comment by dstokesf5** [comment]
Added AUTOTOOL-1523 to our internal product backlog for supporting Elasticsearch 7.

**Comment by DanielLu1127** [comment]
Hi, as I'm also encountering the same issue to push BIG-IP TS to ES version 7.6.2, get below error.

Thu, 30 Apr 2020 10:34:49 GMT - severe: [telemetry.ElasticSearch.My_Consumer] error: [illegal_argument_exception] Limit of total fields [1000] in index [testindex] has been exceeded

What should I do to adjust the ES or BIG-IP TS to compatible with ES version 7.6.2 ?

Or we just wait for TS to tune the API json mapping tree ?

**Comment by aknot242** [comment]
@boeboe and @DanielLu1127 I had to deal with some of those issues before I could send TS messages to ES. https://github.com/aknot242/ansible-uber-demo/blob/master/ansible/roles/servers/tasks/elasticsearch.yml

Later, I ran into the '_doc' issue highlighted above and had to adjust for that too: https://github.com/aknot242/ansible-uber-demo/blob/4eb7d186d3644080b7ad78096dd57145984d281d/ansible/roles/big-ip/templates/ts-declaration.j2#L27

**Comment by mikeoleary** [comment]
@dstokesf5 for reference, I have another customer that is actively looking for support for Elasticsearch 7 also. Any update on planned support would be much appreciated.

**Comment by BenEkpy** [comment]
+1 on ElasticSearch7 support. Any News ?

**Comment by dstokesf5** [comment]
This issue was resolved in the 1.24.0 release of Telemetry Streaming.
