### ISSUE TITLE
Can Host: use a DNSNAME Cname in My_Consumer

### ISSUE THREAD

**Issue by jbloves2ski2** [F5Networks/f5-telemetry-streaming#50]
My_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Splunk",
        **"host": "192.168.165.135",**  We tried using a DNS CName here and it failed.
        "protocol": "https",
        "port": 8088,
        "allowSelfSignedCert": true,
        "passphrase": {
            "cipherText": "93ee3601-6b40-4e63-86ab-ec93faeda362"

**Comment by dstokesf5** [comment]
Please resubmit this issue following the template: https://github.com/F5Networks/f5-telemetry-streaming/issues/new/choose
