### ISSUE TITLE
Output System Poller information to Cloudwatch > Metrics

### ISSUE THREAD

**Issue by LeonardosGitHub** [F5Networks/f5-telemetry-streaming#53]
### Request for new feature
The requested feature would be able to output all the "System poller" information as a custom metric to Cloudwatch > Metrics.  

### Describe the solution you'd like
Using the role assigned the BIG-IP to authenticate to AWS API(or CLI), [using either CLI or API to publish metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html), send custom metrics about the BIG-IP to CloudWatch Metrics.  This would include system data about virtual servers, pools, etc.that is outputted as part of the "System Poller" functionality of TS.

**Comment by dstokesf5** [comment]
I have added this to our internal backlog as AUTOTOOL-1627. Right now adding new consumers is not a high priority. If this is blocking a customer, please escalate this request through F5 support.

**Comment by dstokesf5** [comment]
This was added in v1.14.0. Closing this issue.
