### ISSUE TITLE
Azure log analytics OMS workspace example uses wrong table queries

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-telemetry-streaming#54]
### Environment
 * Telemetry Streaming Version: 1.11.0
 * BIG-IP Version: 15.1.0.2 in Azure

### Summary
The example for Azure Log Analytics push consumer has an example json file, but it uses the wrong table names. As a result, when you load the omsview dashboard, you receive errors from Azure stating that the tables are unresolvable.

https://github.com/F5Networks/f5-telemetry-streaming/blob/master/examples/consumers/azure_log_analytics/telemetry_dashboard.omsview

### Steps To Reproduce
1. Download https://github.com/F5Networks/f5-telemetry-streaming/blob/master/examples/consumers/azure_log_analytics/telemetry_dashboard.omsview
2. Upload to Azure Log Analytics Workspace in View Designer
3. Save file
4. Open dashboard and you will receive about 6 errors and various tables do not load.

Reference this doc:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#microsoft-azure-log-analytics

### Expected Behavior
Loading a supplied omsview file should result in successful graphs.

### Actual Behavior
Error from Azure saying the tables are incorrect.

### Workaround
1. Find five (5) references to F5Telemetry_event_CL and replace with F5Telemetry_ASM_CL
```
"Query": "F5Telemetry_ASM_CL | where isnotempty(attack_type_s)",

"Query": "F5Telemetry_ASM_CL | where isnotempty(attack_type_s) | summarize AggregatedValue = count() by ip_client_s | count",

"Query": "F5Telemetry_ASM_CL | where isnotempty(attack_type_s) | summarize AggregatedValue = count() by ip_client_s | sort by AggregatedValue desc",

"Query": "F5Telemetry_ASM_CL | where isnotempty(attack_type_s) | summarize AggregatedValue = count() by attack_type_s | count",

"Query": "F5Telemetry_ASM_CL | where isnotempty(attack_type_s) | summarize AggregatedValue = count() by attack_type_s | sort by AggregatedValue desc",
```

2. Find one (1) reference to F5Telemetry_event_CL and replace with F5Telemetry_LTM_CL
```
"Query": "F5Telemetry_LTM_CL | where event_source_s == \"request_logging\"",
```

**Comment by Mikej81** [comment]
I thought I created an issue for this, looks like I thought that I thought I created an issue for this...

**Comment by dstokesf5** [comment]
@Mikej81 You did create an issue for this: #39 .

Closing this one as a duplicate.
