### ISSUE TITLE
Log event too large

### ISSUE THREAD

**Issue by aslampatel1** [F5Networks/f5-telemetry-streaming#56]
Tue, 09 Jun 2020 10:13:10 GMT - severe: [telemetry.AWS_CloudWatch.My_Consumer] error: Log event too large: 273181 bytes exceeds limit of 262144
how can I update this limit? I'm unable to locate this variable. thanks

**Comment by dstokesf5** [comment]
Please resubmit this issue using the appropriate template: https://github.com/F5Networks/f5-telemetry-streaming/issues/new/choose
