### ISSUE TITLE
Buffer output to consumers

### ISSUE THREAD

**Issue by ryn9** [F5Networks/f5-telemetry-streaming#58]
### Is your feature request related to a problem? Please describe.
n/a

### Describe the solution you'd like
TS should buffer output to consumers.
Currently TS losses data if it is unable to upload to upstream consumer.

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by dstokesf5** [comment]
Thank you for submitting feedback. However this request is very vague and leaves a lot of questions about requirements.
* How long do you expect TS to buffer the data? If it buffers all events indefinitely, the buffer could easily get large enough to cause problems for the BIG-IP.
* Do you expect this data buffering to happen on all consumer data? Just forwarded event data? Just system poller data?
* How much control do you expect to have over the buffering?

**Comment by ryn9** [comment]
@dstokesf5 I would suggest something like a maximum size configuration for the buffer, where once the maximum size is reached old data is purged from the buffer.  Definitely open to options, as the current state (no buffering capabilities at all) is rough.

**Comment by dstokesf5** [comment]
For buffering, I suggest setting up an OpenTelemetry collector with a fast and reliable network connection to your BIG-IP. Then you can let it handle the data buffering by using the new OpenTelemetry consumer in Telemetry Streaming: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#opent

Does this work for your use case?
