### ISSUE TITLE
docker container (feature request)

### ISSUE THREAD

**Issue by M0JFP** [F5Networks/f5-telemetry-streaming#6]
Feature idea

Can we have the Telemetry api in a docker container like DO and AS3?

**Comment by jsevedge** [comment]
Thanks for the request @M0JFP. This is something that is definitely on our radar, tracking via internal ID 135.

**Comment by dstokesf5** [comment]
The internal product backlog item has migrated to AUTOTOOL-1497.

**Comment by dstokesf5** [comment]
Unfortunately, supporting Telemetry Streaming in a container is no longer on our road map.
