### ISSUE TITLE
TS Cipher Uses

### ISSUE THREAD

**Issue by jba3126tsys** [F5Networks/f5-telemetry-streaming#61]
We are working to generate a report with TLS/SSL version and Ciphers in use.  Unfortunately, the Ciphers in the cipherUses item is only showing ChaCha20Poly1305Bulk.  Is there a way to adjust to get a custom list or all?

**Comment by dstokesf5** [comment]
Please resubmit this issue with one of the available templates: https://github.com/F5Networks/f5-telemetry-streaming/issues/new/choose
