### ISSUE TITLE
Ciphers Stats in Client-SSL Profile

### ISSUE THREAD

**Issue by jba3126tsys** [F5Networks/f5-telemetry-streaming#62]
### Is your feature request related to a problem? Please describe.
We are using Splunk and the vanilla TS documented declaration for polling local and sending to Splunk.  When looking at the cipher stats (cipherUses) in Splunk the only suite I see is chacha20Poly1305Bulk.  I'm uncertain if this is an issue i.e. bug, feature, or configuration.  I've done my best to find details or documentation for adjusting this level of detail.  

### Describe the solution you'd like
We would like to customize this list of cipher stats to match our cipher profile/cipher groups.  For example, we would like to see common.cipherUses.aesGcmBulk which we see when sending a REST call to https://localhost/mgmt/tm/ltm/profile/client-ssl/stats

### Describe alternatives you've considered
We've considered using either python scripts, Ansible playbook, or pull consumers to retrieve the stats.

**Comment by dstokesf5** [comment]
This is a bit of an odd one. It looks like we are currently excluding most cipherUses properties, but the exclusion is being applied incompletely. I have added AUTOTOOL-1679 to our internal product backlog to remove this partial exclusion.

**Comment by curtkersey** [comment]
@dstokesf5 - is there any way to craft a TS declaration to get all the SSL ciphers in the output?  I have tried to come up with one, but no luck so far.  Otherwise, any idea on an ETA for a fix?  Thanks!

**Comment by dstokesf5** [comment]
You may be able to use the custom endpoint feature to work around this issue: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/custom-endpoints.html

i do not currently have an ETA for resolving this issue.

**Comment by dstokesf5** [comment]
This was resolved in v.1.14.0. Closing.
