### ISSUE TITLE
Telemetry doesn't log F5 Virtual server statistics to Azure Sentinel 

### ISSUE THREAD

**Issue by Shaurinshah** [F5Networks/f5-telemetry-streaming#63]
F5Telemetry_AFM_CL and F5Telemetry_ASM_CL shows the security logging but F5Telemetry_AVR_CL doesn't log the Virtual Server stats. 
Looking for the data like Concurrent connections, server connection, client connection etc. 
Using this query
F5Telemetry_AVR_CL
| where virtual_server_s  contains "abc.com"

**Comment by dstokesf5** [comment]
Please resubmit this issue using the appropriate issue template: https://github.com/F5Networks/f5-telemetry-streaming/issues/new/choose
