### ISSUE TITLE
Handle DOS and BOT logs

### ISSUE THREAD

**Issue by ryn9** [F5Networks/f5-telemetry-streaming#64]
### Is your feature request related to a problem? Please describe.
n/a

### Describe the solution you'd like
TS should handle DOS and BOT logs
DOS and BOT logging should be able to be sent to the publisher "telemetry_publisher", appropriately parsed and handled by the TS module, and given appropriate "telemetryEventCategory" fields.

Additionally the documentation should be update to reflect support for these logs types.
Minimum documentation to be updated:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/event-listener.html
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/output-example.html  

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by dstokesf5** [comment]
Any logs sent to a Telemetry Streaming's event listener should be processed and forwarded by Telemetry Streaming. What kind of issues are experiencing with trying to forward DOS and Bot logs?
