### ISSUE TITLE
Documentation: Custom Endpoint example is incorrect

### ISSUE THREAD

**Issue by curtkersey** [F5Networks/f5-telemetry-streaming#65]
### Environment
 * Telemetry Streaming Version: 1.12.0
 * BIG-IP Version: 15.0.1.0.0.11

### Summary
While working to deploy a custom endpoint configuration using the example provided (https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/custom-endpoints.html), I found a few issues that prevent it from working as advertised.  I have updated the declaration -- below.  There are other issues related that I will file separately.

### Steps To Reproduce
1. Submit the following declaration:
```json

{
    "class": "Telemetry",

    "controls": {
        "class": "Controls",
        "logLevel": "info",
        "debug": true
    },

    "Endpoints_Profiles": {
        "class": "Telemetry_Endpoints",
        "basePath": "/mgmt/tm/ltm/profile",
        "items": {
            "radiusProfiles": {
                "name": "radiusProfiles",
                "path": "radius/stats"
            },
            "ipOtherProfiles": {
                "name": "ipOtherProfiles",
                "path": "ipother/stats"
            }
        },
        "enable": true
    },

    "Endpoints_Misc": {
        "class": "Telemetry_Endpoints",
        "items": {
            "clientside.totConns": {
                "name": "virtualTotConns",
                "path": "/mgmt/tm/ltm/virtual/stats?$select=clientside.totConns"
            },
            "virtualAddress": {
                "path": "/mgmt/tm/ltm/virtual-address/stats"
            }
        },
        "enable": true
    },

    "Custom_System": {
        "class": "Telemetry_System",
        "systemPoller": [
            "Custom_System_Poller1",
            "Custom_System_Poller2",
            {
                "interval": 60
            }
        ],
        "enable": true
    },

    "Custom_System_Poller1": {
    	"class": "Telemetry_System_Poller",
        "interval": 60,
        "enable": true,
        "endpointList": "Endpoints_Profiles"
    },

    "Custom_System_Poller2": {
    	"class": "Telemetry_System_Poller",
        "interval": 60,
        "enable": true,
        "endpointList": [
            "Endpoints_Misc/clientside.totConns",
            {
                "path": "/mgmt/tm/net/vlan/stats",
                "name": "requiredWhenInline"
            }
        ]
    },

    "Default_System": {
        "class": "Telemetry_System",
        "systemPoller": {
            "interval": 360
        }
    }
}
```

2. Observe the following error response:
I did not see any errors reported - got back a HTTP 200 OK; however, the declaration does not work.

### Expected Behavior
By using the example, I expected to get a working configuration, but it did not work.

### Actual Behavior
Data was not gathered as intended for Custom Endpoint.

**Comment by dstokesf5** [comment]
Can you please elaborate on what changes you needed to make, and what issues you were seeing before making those changes?

**Comment by curtkersey** [comment]
@dstokesf5 If you save my file and do a diff between them, you will see the problems -- there were a few.

**Comment by dstokesf5** [comment]
That does not help me understand why you made the changes. Going through the diff I generally see the following changes:
1. Added controls object
2. Added/updated enable fields
3. Removed trace
4. Changed the interval on Custom_System_Poller2
5. Fixed some paths

1, 2, 3, and 4 should not be needed. I see that Custom_System_Poller1 is disabled in the example, and should be changed as you suggest. This is not really wrong, but it is quite misleading for this example. Similarly, removing all uses of enable and trace would make the example a little clearer. Obviously item 5 should be fixed.

**Comment by dstokesf5** [comment]
I have added AUTOTOOL-1700 to our internal product backlog to to make the changes I mentioned in my previous post.

**Comment by curtkersey** [comment]
@dstokesf5 - the two critical updates are the enable/disable and the paths.  The current declaration has the first custom endpoint as not 'enable', so that means there is no data sent.  Secondly, the path in "/mgmt/tm/net/vlan/stats" is incorrect, which means no data there either.

Also, based on issue #67, you may need the "controls" section to have that debug data available  via the GET request that the docs show - as indicated in your response to issue #66.

**Comment by dstokesf5** [comment]
The documentation has been updated. Closing this issue.
