### ISSUE TITLE
Documentation: Custom Endpoint updates

### ISSUE THREAD

**Issue by curtkersey** [F5Networks/f5-telemetry-streaming#67]
### Environment
 * Telemetry Streaming Version: 1.12.0
 * BIG-IP Version: 15.0.1.0.0.11

### Summary
While working with example of Custom Endpoints (https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/custom-endpoints.html), I found the documentation for how to retrieve values from the custom endpoints unclear.  For the example on how to retrieve the data, it has the following:

`GET /mgmt/shared/telemetry/systempoller/Custom_System/Custom_System_Poller1`

In reality, you need to do a `GET` request to `https://<management_ip_address>//mgmt/shared/telemetry/systempoller/Custom_System/Custom_System_Poller1` in order to be able to retrieve the data.

All of the examples should be updated to make this more clear.

### Steps To Reproduce
Documentation issue - no steps to reproduce; just need to make it more clear.

**Comment by dstokesf5** [comment]
The documentation here is unclear about the fact that it is using a debug feature to confirm the data gathered by custom endpoints. I have added AUTOTOOL-1698 to clarify the custom endpoint documentation by including additional information about this debug functionality.

**Comment by dstokesf5** [comment]
The documentation has been updated. Closing this issue.
