### ISSUE TITLE
Sending syslog data

### ISSUE THREAD

**Issue by usrlocalbins** [F5Networks/f5-telemetry-streaming#68]
Have a bit of a challenge getting syslog data to send through telemetry.  This is working via QA devices that previously had the legacy Splunk iApp installed.  Through telemetry I was able to get one system to work via a mix of configuration of the legacy iApp and the Event Listener class documentation however, this only works on one device in a pair.

**Comment by dstokesf5** [comment]
Please resubmit your issue following one of the provided templates: https://github.com/F5Networks/f5-telemetry-streaming/issues/new/choose
