### ISSUE TITLE
Documentation Request - F5Telemetry_system_CL  Table Descriptions

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-telemetry-streaming#69]
### Documentation Request - F5Telemetry_system_CL  Table Descriptions
F5 Telemetry Streaming pulls data points from internal resources of the BIG-IP, these data sources don't appear to have any descriptions. Though some of them contain names that are easy enough to guess at, having a real descriptor either in TS native or in the TS Documentation would be beneficial.

### Describe the solution you'd like
Documentation descriptors for TS for the F5Telemetry_system_CL  table

### Describe alternatives you've considered
There is no documentation on this, their arent alternatives.

### Additional context
Customer request

Example of TS table F5Telemetry_system_CL, there are likely more not expressed below

Raw | data
-- | --
diskStorage__var_apm_mount_apmclients_7183_2020_108_2059_4753_0_iso_name_s | /var/apm/mount/apmclients-7183.2020.108.2059-4753.0.iso
diskStorage__mnt_tm_install_20579_qtZJB__run_1024_blocks_s |  
diskStorage__mnt_tm_install_20579_qtZJB__run_Capacity_s |  
diskStorage__mnt_tm_install_20579_qtZJB__run_name_s |  
diskStorage__mnt_tm_install_20579_qtZJB__shared_1024_blocks_s |  
diskStorage__mnt_tm_install_20579_qtZJB__shared_Capacity_s |  
diskStorage__mnt_tm_install_20579_qtZJB__shared_name_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_1024_blocks_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_Capacity_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_name_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_config_1024_blocks_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_config_Capacity_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_config_name_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_usr_1024_blocks_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_usr_Capacity_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_usr_name_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_var_1024_blocks_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_var_Capacity_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_var_name_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_run_1024_blocks_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_run_Capacity_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_run_name_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_shared_Capacity_s |  
diskStorage__mnt_tm_install_20579_wOjGpY_shared_name_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_Capacity_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_name_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_config_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_config_Capacity_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_config_name_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_usr_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_usr_Capacity_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_usr_name_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_var_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_var_Capacity_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_var_name_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_run_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_run_Capacity_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_run_name_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_shared_Capacity_s |  
diskStorage__mnt_tm_install_17313_9GPRxd_shared_name_s |  
diskStorage__mnt_tm_install_17313_D5NVPc_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_D5NVPc_Capacity_s |  
diskStorage__mnt_tm_install_17313_D5NVPc_name_s |  
diskStorage__mnt_tm_install_17313_0eEmRL_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_0eEmRL_Capacity_s |  
diskStorage__mnt_tm_install_17313_0eEmRL_name_s |  
diskStorage__mnt_tm_install_17313_UQaXbe_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_UQaXbe_Capacity_s |  
diskStorage__mnt_tm_install_17313_UQaXbe_name_s |  
diskStorage__mnt_tm_install_17313_Ms8Zu__run_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_Ms8Zu__run_Capacity_s |  
diskStorage__mnt_tm_install_17313_Ms8Zu__run_name_s |  
diskStorage__mnt_tm_install_17313_Ms8Zu__shared_1024_blocks_s |  
diskStorage__mnt_tm_install_17313_Ms8Zu__shared_Capacity_s |  
diskStorage__mnt_tm_install_17313_Ms8Zu__shared_name_s |  
lastAsmChange_s |  
lastAfmDeploy_s |  
diskStorage__mnt_tm_install_26978_X7QikJ_run_1024_blocks_s |  
diskStorage__mnt_tm_install_26978_X7QikJ_run_Capacity_s |  
diskStorage__mnt_tm_install_26978_X7QikJ_run_name_s |  
diskStorage__mnt_tm_install_26978_X7QikJ_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_26978_X7QikJ_shared_Capacity_s |  
diskStorage__mnt_tm_install_26978_X7QikJ_shared_name_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_1024_blocks_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_Capacity_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_name_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_config_1024_blocks_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_config_Capacity_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_config_name_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_usr_1024_blocks_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_usr_Capacity_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_usr_name_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_var_1024_blocks_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_var_Capacity_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_var_name_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_run_1024_blocks_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_run_Capacity_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_run_name_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_shared_Capacity_s |  
diskStorage__mnt_tm_install_26978_yMX8mN_shared_name_s |  
diskStorage__mnt_tm_install_26184__vRvO0_1024_blocks_s |  
diskStorage__mnt_tm_install_26184__vRvO0_Capacity_s |  
diskStorage__mnt_tm_install_26184__vRvO0_name_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_Capacity_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_name_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_config_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_config_Capacity_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_config_name_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_usr_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_usr_Capacity_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_usr_name_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_var_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_var_Capacity_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_var_name_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_run_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_run_Capacity_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_run_name_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_shared_Capacity_s |  
diskStorage__mnt_tm_install_26184_3LbhxJ_shared_name_s |  
diskStorage__mnt_tm_install_26184_G21NeD_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_G21NeD_Capacity_s |  
diskStorage__mnt_tm_install_26184_G21NeD_name_s |  
diskStorage__mnt_tm_install_26184_Bkh8hB_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_Bkh8hB_Capacity_s |  
diskStorage__mnt_tm_install_26184_Bkh8hB_name_s |  
diskStorage__mnt_tm_install_26184_Zj1cot_run_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_Zj1cot_run_Capacity_s |  
diskStorage__mnt_tm_install_26184_Zj1cot_run_name_s |  
diskStorage__mnt_tm_install_26184_Zj1cot_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_26184_Zj1cot_shared_Capacity_s |  
diskStorage__mnt_tm_install_26184_Zj1cot_shared_name_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_Capacity_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_name_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_config_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_config_Capacity_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_config_name_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_usr_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_usr_Capacity_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_usr_name_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_var_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_var_Capacity_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_var_name_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_run_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_run_Capacity_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_run_name_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_shared_Capacity_s |  
diskStorage__mnt_tm_install_32523_5AFfHy_shared_name_s |  
diskStorage__mnt_tm_install_32523_R68NFJ_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_R68NFJ_Capacity_s |  
diskStorage__mnt_tm_install_32523_R68NFJ_name_s |  
diskStorage__mnt_tm_install_32523_w8iI4R_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_w8iI4R_Capacity_s |  
diskStorage__mnt_tm_install_32523_w8iI4R_name_s |  
diskStorage__mnt_tm_install_32523_zn7Gft_run_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_zn7Gft_run_Capacity_s |  
diskStorage__mnt_tm_install_32523_zn7Gft_run_name_s |  
diskStorage__mnt_tm_install_32523_zn7Gft_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_32523_zn7Gft_shared_Capacity_s |  
diskStorage__mnt_tm_install_32523_zn7Gft_shared_name_s |  
diskStorage__mnt_tm_install_10569_Ri2418_run_1024_blocks_s |  
diskStorage__mnt_tm_install_10569_Ri2418_run_Capacity_s |  
diskStorage__mnt_tm_install_10569_Ri2418_run_name_s |  
diskStorage__mnt_tm_install_10569_Ri2418_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_10569_Ri2418_shared_Capacity_s |  
diskStorage__mnt_tm_install_10569_Ri2418_shared_name_s |  
diskStorage__mnt_tm_install_10569_B8csar_1024_blocks_s |  
diskStorage__mnt_tm_install_10569_B8csar_Capacity_s |  
diskStorage__mnt_tm_install_10569_B8csar_name_s |  
diskStorage__mnt_tm_install_10569_B8csar_config_1024_blocks_s |  
diskStorage__mnt_tm_install_10569_B8csar_config_Capacity_s |  
diskStorage__mnt_tm_install_10569_B8csar_config_name_s |  
diskStorage__mnt_tm_install_10569_B8csar_usr_1024_blocks_s |  
diskStorage__mnt_tm_install_10569_B8csar_usr_Capacity_s |  
diskStorage__mnt_tm_install_10569_B8csar_usr_name_s |  
diskStorage__mnt_tm_install_10569_B8csar_var_1024_blocks_s |  
diskStorage__mnt_tm_install_10569_B8csar_var_Capacity_s |  
diskStorage__mnt_tm_install_10569_B8csar_var_name_s |  
diskStorage__mnt_tm_install_10569_B8csar_run_1024_blocks_s |  
diskStorage__mnt_tm_install_10569_B8csar_run_Capacity_s |  
diskStorage__mnt_tm_install_10569_B8csar_run_name_s |  
diskStorage__mnt_tm_install_10569_B8csar_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_10569_B8csar_shared_Capacity_s |  
diskStorage__mnt_tm_install_10569_B8csar_shared_name_s |  
diskStorage__mnt_tm_install_20002_ogdVve_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_ogdVve_Capacity_s |  
diskStorage__mnt_tm_install_20002_ogdVve_name_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_Capacity_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_name_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_config_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_config_Capacity_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_config_name_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_usr_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_usr_Capacity_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_usr_name_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_var_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_var_Capacity_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_var_name_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_run_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_run_Capacity_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_run_name_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_shared_Capacity_s |  
diskStorage__mnt_tm_install_20002_NnfjkS_shared_name_s |  
diskStorage__mnt_tm_install_20002_fB3zhp_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_fB3zhp_Capacity_s |  
diskStorage__mnt_tm_install_20002_fB3zhp_name_s |  
diskStorage__mnt_tm_install_20002_E9DYpM_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_E9DYpM_Capacity_s |  
diskStorage__mnt_tm_install_20002_E9DYpM_name_s |  
diskStorage__mnt_tm_install_20002_2Wmh7J_run_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_2Wmh7J_run_Capacity_s |  
diskStorage__mnt_tm_install_20002_2Wmh7J_run_name_s |  
diskStorage__mnt_tm_install_20002_2Wmh7J_shared_1024_blocks_s |  
diskStorage__mnt_tm_install_20002_2Wmh7J_shared_Capacity_s |  
diskStorage__mnt_tm_install_20002_2Wmh7J_shared_name_s |  
provisioning_tam_name_s |  
provisioning_tam_level_s |  
provisioning_vcmp_name_s |  
provisioning_vcmp_level_s |  
lastAsmChange_t | null
hostname_s | calalang-azure-0.westus2.cloudapp.azure.com
machineId_g | d7369a2e-dc26-4450-a81c-8c37b7f095ca
version_s | 15.1.0.4
versionBuild_s | 0.0.6
location_s | missing data
description_s | missing data
marketingName_s | BIG-IP Virtual Edition
platformId_s | Z100
chassisId_s | e2251f07-2ec7-eb48-d5c8c60ca901
baseMac_s | 00:0D:3A:F9:9B:49
callBackUrl_s | https://10.0.1.4
configReady_s | yes
licenseReady_s | yes
provisionReady_s | yes
syncMode_s | standalone
syncColor_s | green
syncStatus_s | Standalone
syncSummary_s |  
failoverStatus_s | ACTIVE
failoverColor_s | green
systemTimestamp_t | 2020-07-15T18:13:00Z
cpu_d | 9
memory_d | 57
tmmCpu_d | 2
tmmMemory_d | 16
tmmTraffic_clientSideTraffic_bitsIn_d | 14838094424
tmmTraffic_clientSideTraffic_bitsOut_d | 17246341264
tmmTraffic_serverSideTraffic_bitsIn_d | 14778672568
tmmTraffic_serverSideTraffic_bitsOut_d | 17062870168
diskStorage___1024_blocks_s | 428150
diskStorage___Capacity_s | 21%
diskStorage___name_s | /
diskStorage__dev_1024_blocks_s | 7176328
diskStorage__dev_Capacity_s | 1%
diskStorage__dev_name_s | /dev
diskStorage__dev_shm_1024_blocks_s | 7184840
diskStorage__dev_shm_Capacity_s | 7%
diskStorage__dev_shm_name_s | /dev/shm
diskStorage__run_1024_blocks_s | 7184840
diskStorage__run_Capacity_s | 1%
diskStorage__run_name_s | /run
diskStorage__sys_fs_cgroup_1024_blocks_s | 7184840
diskStorage__sys_fs_cgroup_Capacity_s | 0%
diskStorage__sys_fs_cgroup_name_s | /sys/fs/cgroup
diskStorage__usr_1024_blocks_s | 5186648
diskStorage__usr_Capacity_s | 86%
diskStorage__usr_name_s | /usr
diskStorage__shared_1024_blocks_s | 20642428
diskStorage__shared_Capacity_s | 22%
diskStorage__shared_name_s | /shared
diskStorage__shared_rrd_1_2_1024_blocks_s | 7184840
diskStorage__shared_rrd_1_2_Capacity_s | 1%
diskStorage__shared_rrd_1_2_name_s | /shared/rrd.1.2
diskStorage__var_1024_blocks_s | 3030800
diskStorage__var_Capacity_s | 49%
diskStorage__var_name_s | /var
diskStorage__config_1024_blocks_s | 2171984
diskStorage__config_Capacity_s | 38%
diskStorage__config_name_s | /config
diskStorage__var_prompt_1024_blocks_s | 4096
diskStorage__var_prompt_Capacity_s | 1%
diskStorage__var_prompt_name_s | /var/prompt
diskStorage__var_tmstat_1024_blocks_s | 7184840
diskStorage__var_tmstat_Capacity_s | 1%
diskStorage__var_tmstat_name_s | /var/tmstat
diskStorage__var_log_1024_blocks_s | 3023760
diskStorage__var_log_Capacity_s | 43%
diskStorage__var_log_name_s | /var/log
diskStorage__var_loipc_1024_blocks_s | 7184840
diskStorage__var_loipc_Capacity_s | 0%
diskStorage__var_loipc_name_s | /var/loipc
diskStorage__var_lib_mysql_1024_blocks_s | 12385456
diskStorage__var_lib_mysql_Capacity_s | 9%
diskStorage__var_lib_mysql_name_s | /var/lib/mysql
diskStorage__var_apm_mount_apmclients_7180_2019_119_331_4683_0_iso_1024_blocks_s |  
diskStorage__var_apm_mount_apmclients_7180_2019_119_331_4683_0_iso_Capacity_s |  
diskStorage__var_apm_mount_apmclients_7180_2019_119_331_4683_0_iso_name_s |  
diskStorage__mnt_sshplugin_tempfs_1024_blocks_s | 7184840
diskStorage__mnt_sshplugin_tempfs_Capacity_s | 0%
diskStorage__mnt_sshplugin_tempfs_name_s | /mnt/sshplugin_tempfs
diskStorage__var_asmdata1_1024_blocks_s | 4184792
diskStorage__var_asmdata1_Capacity_s | 4%
diskStorage__var_asmdata1_name_s | /var/asmdata1
diskStorage__shared_avr_1024_blocks_s | 3930792
diskStorage__shared_avr_Capacity_s | 2%
diskStorage__shared_avr_name_s | /shared/avr
diskLatency_sda_r_s_s | 1.4
diskLatency_sda_w_s_s | 15.4
diskLatency_sda__util_s | 0.54
diskLatency_sda_name_s | sda
diskLatency_sdb_r_s_s | 1
diskLatency_sdb_w_s_s | 0
diskLatency_sdb__util_s | 0.02
diskLatency_sdb_name_s | sdb
diskLatency_dm_0_r_s_s | 0
diskLatency_dm_0_w_s_s | 0
diskLatency_dm_0__util_s | 0
diskLatency_dm_0_name_s | dm-0
diskLatency_dm_1_r_s_s | 0.12
diskLatency_dm_1_w_s_s | 13.21
diskLatency_dm_1__util_s | 0.02
diskLatency_dm_1_name_s | dm-1
diskLatency_dm_2_r_s_s | 0.02
diskLatency_dm_2_w_s_s | 11.18
diskLatency_dm_2__util_s | 0.02
diskLatency_dm_2_name_s | dm-2
diskLatency_dm_3_r_s_s | 0.05
diskLatency_dm_3_w_s_s | 0.1
diskLatency_dm_3__util_s | 0
diskLatency_dm_3_name_s | dm-3
diskLatency_dm_4_r_s_s | 0
diskLatency_dm_4_w_s_s | 0
diskLatency_dm_4__util_s | 0
diskLatency_dm_4_name_s | dm-4
diskLatency_dm_5_r_s_s | 0
diskLatency_dm_5_w_s_s | 0
diskLatency_dm_5__util_s | 0
diskLatency_dm_5_name_s | dm-5
diskLatency_dm_6_r_s_s | 0
diskLatency_dm_6_w_s_s | 0.01
diskLatency_dm_6__util_s | 0
diskLatency_dm_6_name_s | dm-6
diskLatency_dm_7_r_s_s | 0
diskLatency_dm_7_w_s_s | 0
diskLatency_dm_7__util_s | 0
diskLatency_dm_7_name_s | dm-7
diskLatency_dm_8_r_s_s | 0
diskLatency_dm_8_w_s_s | 0
diskLatency_dm_8__util_s | 0
diskLatency_dm_8_name_s | dm-8
diskLatency_dm_9_r_s_s | 0
diskLatency_dm_9_w_s_s | 0
diskLatency_dm_9__util_s | 0
diskLatency_dm_9_name_s | dm-9
diskLatency_dm_10_r_s_s | 0
diskLatency_dm_10_w_s_s | 0
diskLatency_dm_10__util_s | 0
diskLatency_dm_10_name_s | dm-10
diskLatency_dm_11_r_s_s | 0
diskLatency_dm_11_w_s_s | 0
diskLatency_dm_11__util_s | 0
diskLatency_dm_11_name_s | dm-11
diskLatency_dm_12_r_s_s | 0
diskLatency_dm_12_w_s_s | 0
diskLatency_dm_12__util_s | 0
diskLatency_dm_12_name_s | dm-12
diskLatency_dm_13_r_s_s | 0.01
diskLatency_dm_13_w_s_s | 1.96
diskLatency_dm_13__util_s | 0.03
diskLatency_dm_13_name_s | dm-13
diskLatency_dm_14_r_s_s | 0.14
diskLatency_dm_14_w_s_s | 0
diskLatency_dm_14__util_s | 0.01
diskLatency_dm_14_name_s | dm-14
diskLatency_dm_15_r_s_s | 0.01
diskLatency_dm_15_w_s_s | 0.37
diskLatency_dm_15__util_s | 0.01
diskLatency_dm_15_name_s | dm-15
diskLatency_dm_16_r_s_s | 0.07
diskLatency_dm_16_w_s_s | 10.82
diskLatency_dm_16__util_s | 0.46
diskLatency_dm_16_name_s | dm-16
diskLatency_dm_17_r_s_s | 0.01
diskLatency_dm_17_w_s_s | 2.08
diskLatency_dm_17__util_s | 0.01
diskLatency_dm_17_name_s | dm-17
networkInterfaces_1_1_counters_bitsIn_d | 10548055864
networkInterfaces_1_1_counters_bitsOut_d | 12496435288
networkInterfaces_1_1_status_s | up
networkInterfaces_1_1_name_s | 1.1
networkInterfaces_1_2_counters_bitsIn_d | 3121282648
networkInterfaces_1_2_counters_bitsOut_d | 7202962048
networkInterfaces_1_2_status_s | up
networkInterfaces_1_2_name_s | 1.2
networkInterfaces_mgmt_counters_bitsIn_d | 73196933512
networkInterfaces_mgmt_counters_bitsOut_d | 17991348000
networkInterfaces_mgmt_status_s | up
networkInterfaces_mgmt_name_s | mgmt
provisioning_afm_name_s | afm
provisioning_afm_level_s | nominal
provisioning_am_name_s | am
provisioning_am_level_s | none
provisioning_apm_name_s | apm
provisioning_apm_level_s | nominal
provisioning_asm_name_s | asm
provisioning_asm_level_s | nominal
provisioning_avr_name_s | avr
provisioning_avr_level_s | nominal
provisioning_cgnat_name_s | cgnat
provisioning_cgnat_level_s | none
provisioning_dos_name_s | dos
provisioning_dos_level_s | none
provisioning_fps_name_s | fps
provisioning_fps_level_s | nominal
provisioning_gtm_name_s | gtm
provisioning_gtm_level_s | nominal
provisioning_ilx_name_s | ilx
provisioning_ilx_level_s | nominal
provisioning_lc_name_s | lc
provisioning_lc_level_s | none
provisioning_ltm_name_s | ltm
provisioning_ltm_level_s | nominal
provisioning_pem_name_s | pem
provisioning_pem_level_s | none
provisioning_sslo_name_s | sslo
provisioning_sslo_level_s | nominal
provisioning_swg_name_s | swg
provisioning_swg_level_s | none
provisioning_urldb_name_s | urldb
provisioning_urldb_level_s | none
asmState_s | Policies Consistent
apmState_s | 0
afmState_s | quiescent
lastAfmDeploy_t | 2020-07-09T05:01:15Z
ltmConfigTime_t | 2020-07-15T18:12:37Z
gtmConfigTime_t | 2020-05-01T19:24:59Z
Type | F5Telemetry_system_CL
_ResourceId |

**Comment by dstokesf5** [comment]
I have added AUTOTOOL-1958 to our backlog to get this endpoint information into our documentation.

**Comment by moremammal** [comment]
Maybe we could prioritize some of the more basic metrics? They are not as self-explanatory as they seem.  Customer needs clearer definitions for

- cpu_d and tmmCpu_d
- memory_d and tmmMemory_d

What are the units of measurement for each of these?
Are we including the tmm value in the system metric, or does system indicate management host resources for either or both of these.

These do not appear to line up with the counters accessble via SNMP or tmsh.

**Comment by dstokesf5** [comment]
@moremammal AUTOTOOL-1958 was completed and the endpoint information can be found here: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/poller-default-output-reference.html

You should be able to see what iControl REST endpoints the data is coming from, and then check the relevant iControl REST documentation: https://clouddocs.f5.com/api/icontrol-rest/
