### ISSUE TITLE
Output Format - ECS

### ISSUE THREAD

**Issue by Sakorah** [F5Networks/f5-telemetry-streaming#7]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
From ECS site:
```
The Elastic Common Schema (ECS) defines a common set of fields for ingesting data into Elasticsearch. A common schema helps you correlate data from sources like logs and metrics or IT operations analytics and security analytics.
```

This might be a nice way to export data to Logstash or Elasticsearch and not have to modify and parse the data again to be compatible to ECS

Infos are here: https://github.com/elastic/ecs

Looking for Feedback :)

**Comment by jsevedge** [comment]
@Sakorah Interesting, it seems ECS provides a spec a publisher (such as TS) should use when formatting the event so different sources look the same in ES.  Meaning the ask here is to map TS data JSON output to ECS specific structure and typing.  Does that summarize what you are looking for?

**Comment by bnenjk84** [comment]
@jsevedge - I have been working on traditional logging methods and mapping them into ECS - ie logs from LTM, AVR, DNS, ASM, TMOS and putting them into the Elastic Common Schema -> Ive built these using a module for Elastic filebeat as well as Logstash - I am just about to look at TS into Elastic with ECS field mappings as well as correct data types so items like GEO Location and additional data enrichment through threat intel services can be made available - currently the JSON that comes through from TS without any mappings or an index mapping incorrectly identifies IP address data types.

Interested to discuss this further.

**Comment by jsevedge** [comment]
+ @focrensh

**Comment by focrensh** [comment]
AT-589 for tracking. What would be the flow here?

- TS (map to ECS objects) >> consumer?

- TS >> (ECS parser) >> consumer?

- other

**Comment by abraxxa** [comment]
We would like to be able to configure an ECS output format with e.g. a Generic consumer (suggestion 1). The consumer would be Logstash in our case as we enrich the logs further.

**Comment by RemcoAA** [comment]
Has somebody already managed to ingest the telemetry data into elastic using the ECS format and could share how this is done?

**Comment by dstokesf5** [comment]
Thank you for your feedback. At this time we are focusing Telemetry Streaming on OpenTelemetry use cases, and we are no longer accepting requests for additional consumers. The growing list of supported consumers has become a strain on our limited development resources. If you have a strong business case for a new consumer, I suggest reaching out to product management or F5 support.
