### ISSUE TITLE
Documentation Request - F5Telemetry_virtualServers_CL Table Descriptions

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-telemetry-streaming#70]
### Documentation Request - F5Telemetry_virtualServers_CL Table Descriptions
F5 Telemetry Streaming pulls data points from internal resources of the BIG-IP, these data sources don't appear to have any descriptions. Though some of them contain names that are easy enough to guess at, having a real descriptor either in TS native or in the TS Documentation would be beneficial.

### Describe the solution you'd like
Documentation descriptors for TS for the F5Telemetry_virtualServers_CL   table

### Describe alternatives you've considered
There is no documentation on this, their arent alternatives.

### Additional context
Customer request

Example of TS table F5Telemetry_virtualServers_CL, there are likely more not expressed below.

Raw | data
-- | --
_prodAzureNGINX_azure_nginx_app_01_serviceMain_clientside_bitsIn_d | 9670024
_prodAzureNGINX_azure_nginx_app_01_serviceMain_clientside_bitsOut_d | 32571368
_prodAzureNGINX_azure_nginx_app_01_serviceMain_clientside_curConns_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_destination_s | any:443
_prodAzureNGINX_azure_nginx_app_01_serviceMain_mr_msgIn_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_mr_msgOut_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_mr_reqIn_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_mr_reqOut_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_mr_respIn_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_mr_respOut_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_availabilityState_s | available
_prodAzureNGINX_azure_nginx_app_01_serviceMain_enabledState_s | disabled
_prodAzureNGINX_azure_nginx_app_01_serviceMain_name_s | /prodAzureNGINX/azure_nginx_app_01/serviceMain
_prodAzureNGINX_azure_nginx_app_01_serviceMain_ipProtocol_s | tcp
_prodAzureNGINX_azure_nginx_app_01_serviceMain_mask_s | any
_prodAzureNGINX_azure_nginx_app_01_serviceMain_profiles__Common_f5_tcp_progressive_name_s | /Common/f5-tcp-progressive
_prodAzureNGINX_azure_nginx_app_01_serviceMain_profiles__Common_http_name_s | /Common/http
_prodAzureNGINX_azure_nginx_app_01_serviceMain_profiles__Common_websecurity_name_s | /Common/websecurity
_prodAzureNGINX_azure_nginx_app_01_serviceMain_profiles__prodAzureNGINX_azure_nginx_app_01_ASM_autoScaleAS3Template_OWASP_Auto_Tune_name_s | /prodAzureNGINX/azure_nginx_app_01/ASM_autoScaleAS3Template_OWASP_Auto_Tune
_prodAzureNGINX_azure_nginx_app_01_serviceMain_profiles__prodAzureNGINX_azure_nginx_app_01_TLS_Offload_name_s | /prodAzureNGINX/azure_nginx_app_01/TLS_Offload
_prodAzureNGINX_azure_nginx_app_01_serviceMain_profiles__prodAzureNGINX_azure_nginx_app_01_statsProfile_name_s | /prodAzureNGINX/azure_nginx_app_01/statsProfile
_prodAzureNGINX_azure_nginx_app_01_serviceMain_tenant_s |  
_prodAzureNGINX_azure_nginx_app_01_serviceMain_application_s |  
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__clientside_bitsIn_d | 6043832
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__clientside_bitsOut_d | 4008640
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__clientside_curConns_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__destination_s | any:80
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__mr_msgIn_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__mr_msgOut_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__mr_reqIn_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__mr_reqOut_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__mr_respIn_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__mr_respOut_d | 0
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__availabilityState_s | unknown
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__enabledState_s | disabled
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__name_s | /prodAzureNGINX/azure_nginx_app_01/serviceMain-Redirect-
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__ipProtocol_s | tcp
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__mask_s | any
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__profiles__Common_f5_tcp_progressive_name_s | /Common/f5-tcp-progressive
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__profiles__Common_http_name_s | /Common/http
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__tenant_s |  
_prodAzureNGINX_azure_nginx_app_01_serviceMain_Redirect__application_s |  
Type | F5Telemetry_virtualServers_CL

**Comment by dstokesf5** [comment]
The data for this table is pulled from the `/mgmt/tm/ltm/virtual` and `/mgmt/tm/ltm/virtual/stats` iControl REST endpoints.

**Comment by dstokesf5** [comment]
I have added AUTOTOOL-1958 to our backlog to get this endpoint information into our documentation.

**Comment by dstokesf5** [comment]
The documentation was updated with release 1.17.0.
