### ISSUE TITLE
random dips in bits in/out on pools and virtual servers

### ISSUE THREAD

**Issue by wwsean08** [F5Networks/f5-telemetry-streaming#75]
### Environment
 * Telemetry Streaming Version: 1.13
 * BIG-IP Version: 14.1.2.6

### Summary
Using the prometheus pull consumer sometimes bits in/out decrease.  This likely isn't specific to prometheus, but it's the only consumer I've actually used.  By doing this it causes some really weird spikes in graphs.

raw data:
![image](https://user-images.githubusercontent.com/839261/89567866-409a0e80-d7d7-11ea-9027-a87b3ba40af8.png)

processed (causing a spike due to the bad data):
![image](https://user-images.githubusercontent.com/839261/89567890-4c85d080-d7d7-11ea-8502-d81f1edf3c1d.png)

### Steps To Reproduce
I don't have a good reproduction scenario, however I've only been running this a short time, and I am an internal user at F5 I can work with the team internally to inspect the BIG-IPs, their configuration and determine what causes this.

### Expected Behavior
Bits in/out should always increase until either the BIG-IP is rebooted or there is a counter rollover or potentially when failing over to the backup system in an HA pair.

### Actual Behavior
Occasionally the bits in/out decreases then goes back to where it was before (with whatever changes would be expected in that timeframe)

**Comment by dstokesf5** [comment]
Thank you for reporting this. I have added it to our internal product backlog as AUTOTOOL-1819.

**Comment by dstokesf5** [comment]
This was determined to be a problem with how BIG-IP gathers pool metrics. We have added the following entry to our [FAQ](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/faq.html):
>Why am I seeing a decrease in some pool level metrics?
>
>The BIG-IP system tracks pool level metrics by aggregating node metrics. If a node is deleted, you will see a decrease in some pool metrics, such as the bits in and out.

Closing this issue.
