### ISSUE TITLE
DNS logging profile via TS does not report AVR logs in Splunk

### ISSUE THREAD

**Issue by satish-deepspace** [F5Networks/f5-telemetry-streaming#77]
### Environment
 * Telemetry Streaming Version:
 * BIG-IP Version:

### Summary
Report DNS stats using DNS log profile on DNS-VIP via Telemetric Streaming to Splunk
I did the following in order to get DNS req/resp logging for the VIP configured on port 53 with UDP profile + DNS profile now with backend pool as unbound-DNS servers. 
 
But I wasn’t able to see logs on DNS req/resp in splunk via ts when I have selected ts_splunk_pub in step-1
### Steps To Reproduce
1.Step:-1 (DNS_Log_profile with ts_splunk_pub)
![image](https://user-images.githubusercontent.com/28033062/90942510-fa45d180-e3ca-11ea-8065-91728e66a393.png)

2.Step-2: (DNS_Service_add_dns_log_profile)
![image](https://user-images.githubusercontent.com/28033062/90942522-05006680-e3cb-11ea-8ca6-2bf5ea425f92.png)

3.Step-3 (add_dns_service_profile_vip) with AVR
![image](https://user-images.githubusercontent.com/28033062/90942582-37aa5f00-e3cb-11ea-9ef2-db26d4a72646.png)

### Expected Behavior
Should see DNS request/response logs in Splunk

### Actual Behavior
Do not see any DNS logs

**Comment by dstokesf5** [comment]
Do you have AVR configured to send data to Telemetry Streaming? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/avr.html

**Comment by satish-deepspace** [comment]
@dstokesf5 : yes AVR is provisioned and is configured to sent logs to ts publisher

**Comment by satish-deepspace** [comment]
This is a non-issue, F%-AVR was sending logs to published, had to reduce AVR log aggregating time interval from default of 300secs
