### ISSUE TITLE
How do I get the SSL client TPS and Total new connections

### ISSUE THREAD

**Issue by for-mat** [F5Networks/f5-telemetry-streaming#78]
Through the endpoint, can I get to the CPU usage, detailed totConn, but for the SSL client ,I didn't find them 
if it is need to be calculated, please tell me how to get them

**Comment by dstokesf5** [comment]
Please resubmit this issue following one of our issue templates: https://github.com/F5Networks/f5-telemetry-streaming/issues/new/choose
