### ISSUE TITLE
How do I get the SSL client TPS and Total new connections

### ISSUE THREAD

**Issue by for-mat** [F5Networks/f5-telemetry-streaming#79]
### Is your feature request related to a problem? Please describe.
Through the endpoint, can I get to the CPU usage, detailed totConn, but for the SSL client ,I didn't find them.
if it is need to be calculated, please tell me how to get them

### Describe the solution you'd like
I hope to find specific data, or get these data through calculations

**Comment by dstokesf5** [comment]
It looks like ssl profile stats include totNativeConns and totCompatConns to match the SNMP data mentioned in this K article: https://support.f5.com/csp/article/K6644. Unfortunately, it looks like TS is filtering that data out. I have added AUTOTOOL-2280 to our internal product backlog to expose them.

**Comment by dstokesf5** [comment]
This issue was resolved in the 1.19.0 release.
