### ISSUE TITLE
gNMI Support for Pull Consumer

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-telemetry-streaming#80]
### Is your feature request related to a problem? Please describe.
gNMI is an open standard with an ietf spec, though the solution can be used to control configuration, it can also be used to GET RPC information. Adding the option in the Pull consumers would allow more customer use cases. Both Google and Cisco support gNMI.

### Describe the solution you'd like
Support the gNMI standard as a Pull consumer, this would need to be formatted to the standard.

gNMI RPCs (II)
➔ Get
◆ Snapshot of path state at a particular time.
◆ Typical use case is for configuration state retrieval.
◆ Scaling implications of serialising large object for target.

Specifications: https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md

### Describe alternatives you've considered
There isn't one, we would have to use an external translator, then harvest from that. This situation is overhead.

### Additional context
This is for a customer of TS, I can provide names with a private message.

**Comment by dstokesf5** [comment]
Can you elaborate a bit more on what data you expect to see from this new pull consumer? Would we be able to take the default pull consumer JSON output and wrap it into an update message with the json_val encoding? Or do we need further transformation of the data?

**Comment by jmcalalang** [comment]
Right now the requestor would just like the ability to poll format, if all that's needed is a wrapper I think that covers the bases. They've only asked about telemetry data, so the configuration management part of the protocol isn't in scope.

**Comment by dstokesf5** [comment]
Thank you for your feedback. At this time we are focusing Telemetry Streaming on OpenTelemetry use cases, and we are no longer accepting requests for additional consumers. The growing list of supported consumers has become a strain on our limited development resources. If you have a strong business case for a new consumer, I suggest reaching out to product management or F5 support.
