### ISSUE TITLE
When using custom endpoints and poller reporting to Statsd, the hostname for the report is always base-bigip-com 

### ISSUE THREAD

**Issue by jussisjostrom** [F5Networks/f5-telemetry-streaming#82]
### Environment
 * Telemetry Streaming Version: "version":"1.14.0"
 * BIG-IP Version: 14.1.2.7

### Summary
When defining custom endpoints and custom poller, there is not the correct hostname in the report sent to data consumer (noticed and tested with Statsd+grahpite). Hostname is base-bigip-com, instead of real hostname. This causes stats report to be sorted under hostname base-bigip-com, and rendering aggregation of statistics over multiple BIGIP's impossible.

This issue is reproducible.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
	"cgnatPBAStats": {
		"class": "Telemetry_Endpoints",
		"items": {
			"PBAStats": {
				"name": "pbaStats",
				"path": "/mgmt/tm/security/nat/source-translation/stats"
			}
		}
	},
	"cgnatPoller": {
		"class": "Telemetry_System_Poller",
		"interval": 60,
		"enable": true,
		"endpointList": "cgnatPBAStats"
	},
	"customEndpointsSystem": {
		"class": "Telemetry_System",
		"enable": true,
		"systemPoller": [
			"cgnatPoller",
			{ 
				"interval": 60
			}
		]
	},
	"MyConsumer": {
		"class": "Telemetry_Consumer",
		"type": "Statsd",
		"host": "192.168.2.8",
		"protocol": "udp",
		"port": "8125"
	}
}
```

2. TCPDUMP of the packets sent to statsd consumer, shows the hostname field has value base-bigip-com, instead of the correct hostname of the device sending the report from the custom poller.

Compare that to the packet sent by the default system poller, which has the correct hostname set.

Also, visualizing the data sent to statsd using graphite-web, shows that the custom endpoints statistics end up under the host base-bigip-com, while the stats reported by the default system poller ends up under correct hostname(s).

### Expected Behavior
Expected behaviour is that also customized statistics would be reported up under the hostname that sent the statistics.

### Actual Behavior
This is the data-field of packet sent to statsd consumer,  obtained by a custom poller (pbaStats):
0000  66 35 74 65 6c 65 6d 65 74 72 79 2e 62 61 73 65   f5telemetry.base
0010  2d 62 69 67 69 70 2d 63 6f 6d 2e 70 62 61 53 74   -bigip-com.pbaSt
0020  61 74 73 2e 2d 56 4e 46 2d 41 50 4e 30 31 2d 70   ats.-VNF-APN01-p
0030  62 61 2d 73 74 61 74 73 2e 70 63 70 2d 6d 61 70   ba-stats.pcp-map
0040  52 65 73 70 6f 6e 73 65 73 3a 30 7c 67 0a 66 35   Responses:0|g.f5
0050  74 65 6c 65 6d 65 74 72 79 2e 62 61 73 65 2d 62   telemetry.base-b
0060  69 67 69 70 2d 63 6f 6d 2e 70 62 61 53 74 61 74   igip-com.pbaStat
0070  73 2e 2d 56 4e 46 2d 41 50 4e 30 31 2d 70 62 61   s.-VNF-APN01-pba
0080  2d 73 74 61 74 73 2e 70 63 70 2d 70 65 65 72 52   -stats.pcp-peerR
0090  65 71 75 65 73 74 73 3a 30 7c 67 0a 66 35 74 65   equests:0|g.f5te
00a0  6c 65 6d 65 74 72 79 2e 62 61 73 65 2d 62 69 67   lemetry.base-big
00b0  69 70 2d 63 6f 6d 2e 70 62 61 53 74 61 74 73 2e   ip-com.pbaStats.
00c0  2d 56 4e 46 2d 41 50 4e 30 31 2d 70 62 61 2d 73   -VNF-APN01-pba-s
00d0  74 61 74 73 2e 70 63 70 2d 70 65 65 72 52 65 73   tats.pcp-peerRes
00e0  70 6f 6e 73 65 73 3a 30 7c 67 0a 66 35 74 65 6c   ponses:0|g.f5tel
00f0  65 6d 65 74 72 79 2e 62 61 73 65 2d 62 69 67 69   emetry.base-bigi
0100  70 2d 63 6f 6d 2e 74 65 6c 65 6d 65 74 72 79 53   p-com.telemetryS
0110  65 72 76 69 63 65 49 6e 66 6f 2e 70 6f 6c 6c 69   erviceInfo.polli
0120  6e 67 49 6e 74 65 72 76 61 6c 3a 36 30 7c 67      ngInterval:60|g

This is corresponding data-field from same VE, but collect by the default system poller, with correct hostname:
0000  66 35 74 65 6c 65 6d 65 74 72 79 2e 73 6a 6f 73   f5telemetry.sjos
0010  74 72 6f 6d 2d 76 6e 66 30 31 2d 6c 6f 63 61 6c   trom-vnf01-local
0020  2e 76 69 72 74 75 61 6c 53 65 72 76 65 72 73 2e   .virtualServers.
0030  2d 56 4e 46 2d 41 50 4e 30 31 2d 76 73 48 54 54   -VNF-APN01-vsHTT
0040  50 5f 6f 75 74 2e 63 6c 69 65 6e 74 73 69 64 65   P_out.clientside
0050  2d 62 69 74 73 49 6e 3a 33 33 32 39 34 39 36 32   -bitsIn:33294962
0060  34 7c 67 0a 66 35 74 65 6c 65 6d 65 74 72 79 2e   4|g.f5telemetry.
0070  73 6a 6f 73 74 72 6f 6d 2d 76 6e 66 30 31 2d 6c   sjostrom-vnf01-l
0080  6f 63 61 6c 2e 76 69 72 74 75 61 6c 53 65 72 76   ocal.virtualServ
0090  65 72 73 2e 2d 56 4e 46 2d 41 50 4e 30 31 2d 76   ers.-VNF-APN01-v
00a0  73 48 54 54 50 5f 6f 75 74 2e 63 6c 69 65 6e 74   sHTTP_out.client
00b0  73 69 64 65 2d 62 69 74 73 4f 75 74 3a 38 38 30   side-bitsOut:880
00c0  33 33 38 34 39 36 7c 67 0a 66 35 74 65 6c 65 6d   338496|g.f5telem
00d0  65 74 72 79 2e 73 6a 6f 73 74 72 6f 6d 2d 76 6e   etry.sjostrom-vn
00e0  66 30 31 2d 6c 6f 63 61 6c 2e 76 69 72 74 75 61   f01-local.virtua
00f0  6c 53 65 72 76 65 72 73 2e 2d 56 4e 46 2d 41 50   lServers.-VNF-AP
0100  4e 30 31 2d 76 73 48 54 54 50 5f 6f 75 74 2e 63   N01-vsHTTP_out.c
0110  6c 69 65 6e 74 73 69 64 65 2d 63 75 72 43 6f 6e   lientside-curCon
0120  6e 73 3a 30 7c 67 0a 66 35 74 65 6c 65 6d 65 74   ns:0|g.f5telemet
0130  72 79 2e 73 6a 6f 73 74 72 6f 6d 2d 76 6e 66 30   ry.sjostrom-vnf0
0140  31 2d 6c 6f 63 61 6c 2e 76 69 72 74 75 61 6c 53   1-local.virtualS
0150  65 72 76 65 72 73 2e 2d 56 4e 46 2d 41 50 4e 30   ervers.-VNF-APN0
0160  31 2d 76 73 54 43 50 5f 70 38 30 30 30 5f 6f 75   1-vsTCP_p8000_ou
0170  74 2e 63 6c 69 65 6e 74 73 69 64 65 2d 62 69 74   t.clientside-bit
0180  73 49 6e 3a 30 7c 67 0a 66 35 74 65 6c 65 6d 65   sIn:0|g.f5teleme
0190  74 72 79 2e 73 6a 6f 73 74 72 6f 6d 2d 76 6e 66   try.sjostrom-vnf
01a0  30 31 2d 6c 6f 63 61 6c 2e 76 69 72 74 75 61 6c   01-local.virtual
01b0  53 65 72 76 65 72 73 2e 2d 56 4e 46 2d 41 50 4e   Servers.-VNF-APN
01c0  30 31 2d 76 73 54 43 50 5f 70 38 30 30 30 5f 6f   01-vsTCP_p8000_o
01d0  75 74 2e 63 6c 69 65 6e 74 73 69 64 65 2d 62 69   ut.clientside-bi
01e0  74 73 4f 75 74 3a 30 7c 67 0a 66 35 74 65 6c 65   tsOut:0|g.f5tele
01f0  6d 65 74 72 79 2e 73 6a 6f 73 74 72 6f 6d 2d 76   metry.sjostrom-v
0200  6e 66 30 31 2d 6c 6f 63 61 6c 2e 76 69 72 74 75   nf01-local.virtu
0210  61 6c 53 65 72 76 65 72 73 2e 2d 56 4e 46 2d 41   alServers.-VNF-A
0220  50 4e 30 31 2d 76 73 54 43 50 5f 70 38 30 30 30   PN01-vsTCP_p8000
0230  5f 6f 75 74 2e 63 6c 69 65 6e 74 73 69 64 65 2d   _out.clientside-
0240  63 75 72 43 6f 6e 6e 73 3a 30 7c 67 0a 66 35 74   curConns:0|g.f5t
0250  65 6c 65 6d 65 74 72 79 2e 73 6a 6f 73 74 72 6f   elemetry.sjostro
0260  6d 2d 76 6e 66 30 31 2d 6c 6f 63 61 6c 2e 74 65   m-vnf01-local.te
0270  6c 65 6d 65 74 72 79 53 65 72 76 69 63 65 49 6e   lemetryServiceIn
0280  66 6f 2e 70 6f 6c 6c 69 6e 67 49 6e 74 65 72 76   fo.pollingInterv
0290  61 6c 3a 36 30 7c 67                              al:60|g

**Comment by jussisjostrom** [comment]
One workaround seems to be to include system.hostname field in the same list of endpoints: 
<pre>
	"cgnatPBAStats": {
		"class": "Telemetry_Endpoints",
		"items": {
			"PBAStats": {
				"name": "pbaStats",
				"path": "/mgmt/tm/security/nat/source-translation/stats"
			},
			<b>"systemHostname": {
				"name": "system", 
				"path": "/mgmt/tm/sys/global-settings"

			}</b>
		}
	},
</pre>
So, the systemHostname endpoint needs to be added as item to each custom endpoints declaration, to have the hostname set correctly in stats reports sent to statds. 

Ok, so maybe this is not a bug, but a enhancement would be nice, in that the hostname is set correctly also for customized pollers without this additional endpoint,  to get stats under correct host...

**Comment by dstokesf5** [comment]
It looks like the statsd consumer falls back to a hostname of "base.bigip.com" if no hostname exists in the gathered data. I suspect you are also seeing an error in the log messages about not finding the hostname in the gathered data.

I agree that this behavior is undesirable, I have added AUTOTOOL-1893 to our internal product backlog to try and clean up this behavior.

**Comment by dstokesf5** [comment]
We have tried to provide users more warnings about this behavior in v.15.0: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#statsd-ref

Closing this issue.

Additional note, the internal issue number is actually AUTOTOOL-1894.
