### ISSUE TITLE
_ResourceID populated in TS logs

### ISSUE THREAD

**Issue by filip48** [F5Networks/f5-telemetry-streaming#84]
### General issue description

I am unable to reference Telemetry Streaming stats/events in Azure Log Analytics of our Big-IPs deployed to Azure because of empty _ResourceID field. All of the Microsoft native solutions, as well as majority of 3rd party, is populating this field to reference the ID of the VM each log came from.

Currently we are using Telemetry Consumer Azure_Log_Analytics and AS3 declaration to have TS configured.

### Describe the solution you'd like
I would like above mentioned consumer to populate _ResourceID field with proper value, e.g.: "/subscriptions/abcd1234-a1a1-aaaa-bbbb-abcdef123456/resourceGroups/my-resource-group/providers/Microsoft.Compute/virtualMachines/f5vm01"

### Describe alternatives you've considered
I have considered using Generic_HTTP TS consumer but I am unable to generate \<Signature\> variable from "Authorization" header, which is supposed to be dynamic. I believe it is hardcoded in Azure_Log_Analytics consumer. 

### Additional context
Consumers I refer to: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#
Data used in HTTP_Generic: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api

**Comment by dstokesf5** [comment]
This was resolved as part of the 1.16.0 release.
