### ISSUE TITLE
Post to a consumer via an HTTP proxy

### ISSUE THREAD

**Issue by garrancho** [F5Networks/f5-telemetry-streaming#85]
### Is your feature request related to a problem? Please describe.
Would like to post to a consumer via an HTTP proxy, similar to what is available via ihealth poller.

### Describe the solution you'd like
A statement similar to the proxy parameter in iHealth poller as described in -  https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/userguide/telemetry-system.html

### Describe alternatives you've considered
Continue to use analytics iApp.

**Comment by dstokesf5** [comment]
What consumer do you currently need proxy support for? This information would be helpful in case it is not feasible to add proxy support to all consumers at once.

**Comment by garrancho** [comment]
Good point! That would be Splunk ( non-legacy) .

**Comment by dstokesf5** [comment]
Thank  you for your feedback. I have added your feature request to our internal product backlog as AUTOTOOL-1984.

**Comment by dstokesf5** [comment]
This has been resolved as part of the 1.17.0 release.

**Comment by vkarla2** [comment]
Can I ask please if in the newest v1.31.0 release there is support to post to a consumer Azure Log Analytics via an HTTP proxy?
I've tried proxy declaration in consumer field, but not reaching proxy server, going directly to Azure. Thanks for help.
