### ISSUE TITLE
Custom Endpoint output fails to identify Big-IP hostname 

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/f5-telemetry-streaming#87]
### Environment
 * Telemetry Streaming Version: 1.15 and 1.14
 * BIG-IP Version: 15.1.x and 13.1.x 

### Summary
TS Output generated by Custom Endpoint configuration does not identify the Big-IP hostname in the exported metrics. A workaround exists and should be added to the custom endpoints documentation page to avoid confusion: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/custom-endpoints.html  

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "Telemetry",
    "My_System": {
        "class": "Telemetry_System",
        "systemPoller": {
            "interval": 60
        }
    },
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514
    },
    "My_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Statsd",
        "host": "10.5.20.129",
        "protocol": "udp",
        "port": 8125
    },
    "Custom_Endpoints": {
        "class": "Telemetry_Endpoints",
        "items": {
             "detailedCPU": {
                 "name": "detailedCPU",
                 "path": "/mgmt/tm/sys/host-info"
             }
        }
    },
     "Custom_System_Poller1": {
      "class": "Telemetry_System_Poller",
      "interval": 60,
      "endpointList": "Custom_Endpoints"
    }
}
```

2. Observe the exported metrics missing the system hostname:
```
decoded output via tcpdump:  
f5telemetry.hostname-unknown.detailedCPU.sys-host-info-0.sys-hostInfo-0-cpuInfo.sys-hostInfo-0-cpuInfo-0.
f5telemetry.hostname-unknown.detailedCPU.sys-host-info-0.sys-hostInfo-0-cpuInfo.sys-hostInfo-0-cpuInfo-1.
f5telemetry.hostname-unknown.detailedCPU.sys-host-info-0.sys-hostInfo-0-cpuInfo.sys-hostInfo-0-cpuInfo-2.
f5telemetry.hostname-unknown.detailedCPU.sys-host-info-0.sys-hostInfo-0-cpuInfo.sys-hostInfo-0-cpuInfo-3.
```

### Expected Behavior
The custom endpoints output should identify the Big-IP hostname.  
The output from default system poller metrics identifies the hostname as expected. 

Example output from default system poller:  
```
f5telemetry.bigip-1-lab-local.system.tmmTraffic.clientSideTraffic-bitsIn
f5telemetry.bigip-1-lab-local.system.networkInterfaces
```

### Actual Behavior
Output from TS custom endpoint is missing Big-IP hostname field which causes issues when the TS consumer is parsing the data. Output from multiple Big-IPs mix together and you cannot identify custom endpoint metrics from the specific Big-IP that generated the metrics. 

Workaround is to explicitly add an additional custom endpoint entry to look for hostname. 

Using the same TS declaration as above but with the workaround included: 

```json
{
    "class": "Telemetry",
    "My_System": {
        "class": "Telemetry_System",
        "systemPoller": {
            "interval": 60
        }
    },
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514
    },
    "My_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Statsd",
        "host": "10.5.20.129",
        "protocol": "udp",
        "port": 8125
    },
    "Custom_Endpoints": {
        "class": "Telemetry_Endpoints",
        "items": {
             "detailedCPU": {
                 "name": "detailedCPU",
                 "path": "/mgmt/tm/sys/host-info"
             },
             "systemHostname": {
                 "name": "system",
                 "path": "/mgmt/tm/sys/global-settings"
            }
        }
    },
     "Custom_System_Poller1": {
      "class": "Telemetry_System_Poller",
      "interval": 60,
      "endpointList": "Custom_Endpoints"
    }
}
```

After applying the workaround the custom endpoint output correctly identifies the Big-IP hostname:
```
decoded output via tcpdump:  
f5telemetry.bigip-1-lab-local.detailedCPU.sys-host-info-0.sys-hostInfo-0-cpuInfo.sys-hostInfo-0-cpuInfo-0.
f5telemetry.bigip-1-lab-local.detailedCPU.sys-host-info-0.sys-hostInfo-0-cpuInfo.sys-hostInfo-0-cpuInfo-1.
f5telemetry.bigip-1-lab-local.detailedCPU.sys-host-info-0.sys-hostInfo-0-cpuInfo.sys-hostInfo-0-cpuInfo-2.
f5telemetry.bigip-1-lab-local.detailedCPU.sys-host-info-0.sys-hostInfo-0-cpuInfo.sys-hostInfo-0-cpuInfo-3.
```

In the TS custom endpoint documentation page it should call out you need to add a hostname entry in order to have the output correctly identify the Big-IP hostname.  
TS should be modified to automatically identify the Big-IP hostname when configuring a specific custom endpoint.

**Comment by dstokesf5** [comment]
This specifically affects the StatsD consumer, so it is documented there: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#statsd

**Comment by megamattzilla** [comment]
The statsd note you mentioned says if TS cant find the hostname for statsd output, it will use hostname-unknown. 

I found that note when I was researching the problem, but the note does not mention how to workaround the problem. 

To me, it's not intuitive to explicitly add the extra custom endpoint entry to query /mgmt/tm/sys/global-settings so that all the custom endpoint output have the hostname identified correctly. 

The nature of custom endpoints will probably be some specific REST URI to capture something that is not included in the system poller, which will likely not include the hostname.

**Comment by dstokesf5** [comment]
I have added AUTOTOOL-2029 to our internal product backlog to make it more clear in the documentation how to resolve this issue.

**Comment by walterk82** [comment]
There is another workaround for https://github.com/F5Networks/f5-telemetry-streaming/issues/107 as well.

**Comment by dstokesf5** [comment]
The documentation was updated a while ago. Closing this issue.
