### ISSUE TITLE
Feature request: support Prometheus output

### ISSUE THREAD

**Issue by jenningsloy318** [F5Networks/f5-telemetry-streaming#9]
##### ISSUE TYPE
 - Feature Idea
 

##### SUMMARY
Not sure if TS has same functionality with [BigStats](https://github.com/f5devcentral/BigStats),but hope  TS can  provide Prometheus output for better monitoring

**Comment by jsevedge** [comment]
Hello @jenningsloy318.  Thanks for the feedback, internal ID 141 opened to track this.

**Comment by jenningsloy318** [comment]
Hi @jsevedge 

Can you please update the progress of prometheus support?

**Comment by juhtie01** [comment]
@jsevedge we would also be interested in this, are there any updates?

**Comment by neeles83** [comment]
Same here it would be very interesting to output the metrics to telegraf, this way you can consume it by Prometheus, Kafka and thus multiple other destinations. However you can already do this with statsd and forwarding it into telegraf which is then scraped by Prometheus.

**Comment by dstokesf5** [comment]
The internal product backlog item for this has changed to AUTOTOOL-1169. The feature should be available in version 1.12.0.

**Comment by dstokesf5** [comment]
This was resolved with the 1.12.0 release. Closing.

**Comment by neeles83** [comment]
@dstokesf5 Thanks for the notification and closure we will try this for sure!
