### ISSUE TITLE
Kafka push mode - authentication

### ISSUE THREAD

**Issue by pgouband** [F5Networks/f5-telemetry-streaming#90]
### Is your feature request related to a problem? Please describe.
Customer wants to use Kafka in push mode but with authentication.
Currently TS supports SASL-PLAIN or None as option for authentication.
Customer Kafka bus supports the following authentication options:
- TLS client authentication
- SASL SCRAM-SHA-512

### Describe the solution you'd like
Can we add the following authentication method to Kafka push mode consumer?
- TLS client authentication
- SASL SCRAM-SHA-512

**Comment by dstokesf5** [comment]
It looks like we are able to add TLS client authentication, and I have added AUTOTOOL-2028 to our internal product backlog for it.

Unfortunately, it looks like supporting SASL SCRAM-SHA-512 will not be feasible at this time do to Node version restrictions on the BIG-IP platform.

**Comment by pgouband** [comment]
Hi Daniel,

When can we expect the new release with this added feature?

**Comment by dstokesf5** [comment]
It will most likely be in the 1.17.0 release in mid-January.

**Comment by Brianbrifri** [comment]
@dstokesf5 
Looking at the docs here: [https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#kafka](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#kafka)
specifically:
**Protocol: The port of the Kafka system. Options: binaryTcp or binaryTcpTls. Default is binaryTcpTls**

Can you confirm that enabling binaryTcpTls will in fact send the credentials over TLS?

**Comment by dstokesf5** [comment]
When the binaryTcpTls option is used, the traffic sent from Telemetry Streaming to Kafka will use TLS. This includes the credentials and messages that Telemetry Streaming sends.

**Comment by Brianbrifri** [comment]
Thanks very much! I appreciate the response and the clarification.

**Comment by dstokesf5** [comment]
This has been resolved as part of the 1.17.0 release.
