### ISSUE TITLE
Post to F5 Beacon consumer via an HTTP proxy

### ISSUE THREAD

**Issue by alaari-f5** [F5Networks/f5-telemetry-streaming#92]
**Feature Request:**

I would like to post to the F5 Beacon consumer (which uses Generic HTTP) via an HTTP proxy.

**Comment by dstokesf5** [comment]
This has been added to our internal product backlog as AUTOTOOL-2043.

**Comment by dstokesf5** [comment]
This has been resolved as part of the 1.17.0 release.
