### ISSUE TITLE
Not able to uninstall plugin via API call or through WebUI

### ISSUE THREAD

**Issue by anesh** [F5Networks/f5-telemetry-streaming#98]
### Environment
 * Plugin in version 1.15.0
 * vCMP Guest TMOS 14.1.2.7

### Summary
Not able to uninstall f5-telemetry-streaming plugin via API call or through WebUI

### Steps To Reproduce
1. Perform the below API Call to uninstall package
```
 curl -H "Content-Type: application/json" -k -u username:password -X POST -d '{"operation": "UNINSTALL","packageName": "f5-telemetry-1.15.0-4.noarch"}' https://<device_ip>/mgmt/shared/iapp/package-management-tasks
```
2. Observed the following response:
```json
{
   "packageName":"f5-telemetry-1.15.0-4.noarch",
   "operation":"UNINSTALL",
   "id":"6d338ae0-09f3-4a53-a51e-202959b85e64",
   "status":"CREATED",
   "userReference":{
      "link":"https://localhost/mgmt/shared/authz/users/<username>"
   },
   "identityReferences":[
      {
         "link":"https://localhost/mgmt/shared/authz/users/<username>"
      }
   ],
   "ownerMachineId":"2f802797-07f9-4dd8-9b0d-b1e18f96f310",
   "generation":1,
   "lastUpdateMicros":1605731577522061,
   "kind":"shared:iapp:package-management-tasks:iapppackagemanagementtaskstate",
   "selfLink":"https://localhost/mgmt/shared/iapp/package-management-tasks/6d338ae0-09f3-4a53-a51e-202959b85e64"
}
```

### Expected Behavior
f5-telemetry should be deleted from /var/config/rest/iapps

### Actual Behavior
f5-telemetry folder continues to exist in /var/config/rest/iapps and also in Webui

**Comment by anesh** [comment]
Below is what i get when i check the status of the uninstall



'''
 curl -u username:pass http://localhost/mgmt/shared/iapp/package-management-tasks/6d338ae0-09f3-4a53-a51e-202959b85e64 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   766  100   766    0     0  26370      0 --:--:-- --:--:-- --:--:-- 27357
{
  "packageName": "f5-telemetry-1.15.0-4.noarch",
  "operation": "UNINSTALL",
  "id": "6d338ae0-09f3-4a53-a51e-202959b85e64",
  "status": "FAILED",
  "startTime": "2020-11-18T15:32:57.529-0500",
  "endTime": "2020-11-18T15:33:57.820-0500",
  "errorMessage": "Package f5-telemetry: Cannot remove. Stuck at version 1.15.0 with status DELETING",
  "userReference": {
    "link": "https://localhost/mgmt/shared/authz/users/aneke"
  },
  "identityReferences": [
    {
      "link": "https://localhost/mgmt/shared/authz/users/aneke"
    }
  ],
  "ownerMachineId": "2f802797-07f9-4dd8-9b0d-b1e18f96f310",
  "generation": 3,
  "lastUpdateMicros": 1605731637820602,
  "kind": "shared:iapp:package-management-tasks:iapppackagemanagementtaskstate",
  "selfLink": "https://localhost/mgmt/shared/iapp/package-management-tasks/6d338ae0-09f3-4a53-a51e-202959b85e64"
}
'''

**Comment by dstokesf5** [comment]
This looks like a problem with the iControl LX Extension framework that Telemetry Streaming is built on top of. Do you see similar issues with other extensions?

**Comment by anesh** [comment]
> This looks like a problem with the iControl LX Extension framework that Telemetry Streaming is built on top of. Do you see similar issues with other extensions?

This is the only extension i tried..is there a workaround to delete?

**Comment by dstokesf5** [comment]
Are you able to delete through the GUI (I know that is not your end goal, but it could be helpful for debugging)? Do you see any errors in `/var/log/restnoded/restnoded.log` when the uninstall failure occurs?

**Comment by anesh** [comment]
When uninstall via GUI i see below error
![image](https://user-images.githubusercontent.com/532993/100138612-4a19b600-2e5c-11eb-870b-d6b2573ea922.png)

**Comment by anesh** [comment]
> Are you able to delete through the GUI (I know that is not your end goal, but it could be helpful for debugging)? Do you see any errors in `/var/log/restnoded/restnoded.log` when the uninstall failure occurs?

When uninstall via GUI i see below error
![image](https://user-images.githubusercontent.com/532993/100138679-63226700-2e5c-11eb-9be9-32b1b7e0d064.png)

**Comment by dstokesf5** [comment]
That is definitely a problem with the iControl LX Extension framework that goes beyond what we can attempt to fix in Telemetry Streaming. I suggest opening a case with F5 support.

**Comment by anesh** [comment]
Case is #1-6856307386 is already open, have not received any support so far, the knowledge required to support components of the F5 Automation Tool chain is severely lacking

**Comment by anesh** [comment]
.

**Comment by dstokesf5** [comment]
Thank you for the case number. I will see if I can provide support with some additional information to help them along.

**Comment by anesh** [comment]
the solution was to run ```clear-rest-storage``` which uninstalls all plugins and not just telemetry
